net-misc/ntp/files/ntp.conf, net-misc/ntp/files/ntpdate.service, net-misc/ntp/files/sntp.service, sys-apps/systemd/systemd-9999.ebuild
We set up a vendor pool zone, let's use it instead of coreos'.
Fixes flatcar-linux/Flatcar#2
=> ntp,systemd: switch to flatcar's NTP zone

coreos-base/coreos-metadata/coreos-metadata-9999.ebuild, coreos-base/coreos-metadata/files/coreos-metadata-sshkeys@.service, coreos-base/coreos-metadata/files/coreos-metadata.service, coreos-base/oem-digitalocean/files/base/base.ign, coreos-base/oem-ec2-compat/files/base/base-ec2.ign, coreos-base/oem-gce/files/base/base.ign, coreos-base/oem-oracle-oci/files/base/base.ign, coreos-base/oem-packet/files/base/base.ign, coreos-base/oem-packet/files/units/packet-phone-home.service
There's no need to rename this since coreos-metadata is just the name of
the project.
=> Change back flatcar-metadata to coreos-metadata

app-arch/torcx/torcx-9999.ebuild
This was breaking our symlink `/usr/lib/coreos` -> `/usr/lib/flatcar`
since it was make a copy of it before creating an actual `coreos`
directory, ending up with this structure:
```
core@machine ~ $ ls -ld /usr/lib/core*
drwxr-xr-x. 2 root root 4096 Sep 13 15:37 /usr/lib/coreos
lrwxrwxrwx. 1 root root    7 Sep 13 15:41 /usr/lib/coreos.backup.0000 -> flatcar
```
Without that symlink, applications expecting it broke, like, for
example, the `kubelet-wrapper` systemd service.
=> app-arch/torcx: switch libcoreosdir to /usr/lib/flatcar

eclass/coreos-kernel.eclass, sys-kernel/coreos-kernel/coreos-kernel-4.19.0.ebuild
We should not change `$COREOS_SOURCE_NAME` to `linux-4.19.0-flatcar`, because `$KERNEL_DIR` depends on the variable. Since $KERNEL_DIR `/usr/src/linux-4.19.0-flatcar` does not exist, kernel module builds will fail. That's because coreos-sources distributes the kernel source with the name of "-coreos". It's hard to change the name without touching a lot of places.
So let's set `$COREOS_SOURCE_NAME` back to `linux-4.19.0-coreos`, and explicitly define `$KV_OUT_DIR` that uses `$FLATCAR_SOURCE_NAME`, e.g. `/usr/src/linux-4.19.0-flatcar`. That way, we can minimize a mount of changes.
=> sys-kernel: set KV_OUT_DIR explicitly instead of COREOS_SOURCE_NAME.

eclass/coreos-kernel.eclass
Since 653e4d0852431a0daef77314a921e25562b2a53b, $KERNEL_DIR is broken again. It needs to be `-coreos`, not `-flatcar`.
To fix that, define another variable $COREOS_KERNEL_SOURCE_NAME, which
is `/usr/src/linux-*-coreos`
=> eclass: make again KERNEL_DIR have coreos kernel name

sys-kernel/coreos-kernel/coreos-kernel-4.14.79.ebuild
`FLATCAR_SOURCE_NAME` does not exist. Use only `COREOS_SOURCE_NAME`.
=> sys-kernel: make KV_OUT_DIR use again COREOS_SOURCE_NAME

coreos-base/update_engine/update_engine-9999.ebuild, sys-apps/baselayout/baselayout-9999.ebuild, sys-kernel/bootengine/bootengine-9999.ebuild
So far the Flatcar SDK has installed following packages from the upstream master, not the flatcar-master branch. It should actually install the `flatcar-master` branch, to avoid build errors.
* baselayout: without this fix, build fails when trying to copy `env.d/99flatcar_ldpath` from the baselayout repo.
* update_engine: without this fix, build fails with errors when trying to access to `/usr/bin/postinst`, which is symlink to `/usr/sbin/flatcar-postinst`.
* bootengine: without this fix, the systemd service `initrd-setup-root.service` fails when `/sbin/initrd-setup-root` in initrd tries to run `/usr/sbin/coreos-tmpfiles` instead of `/usr/sbin/flatcar-tmpfiles`.
=> sys-apps: fix baselayout commit to flatcar-master branch

eclass/coreos-kernel.eclass
In case of a suffix `$COREOS_SOURCE_REVISION` expliticly given by the user, like `-r1`, `$COREOS_SOURCE_NAME` should not include the revision suffix. That's because the individual coreos-kernel*ebuild will make use of `$COREOS_SOURCE_NAME` as a base of `$KV_OUT_DIR`.
Otherwise the build will fail because `/build/amd64-usr/lib/modules/4.14.96-flatcar-r1` does not exist. More precisely, that's because `$KV_FULL` given by the upstream eclass does not include the suffix, e.g. `/build/amd64-usr/lib/modules/4.14.96-flatcar`,
=> eclass: trim suffix REVISION from COREOS_SOURCE_VERSION

coreos-base/coreos-init/coreos-init-9999.ebuild
Since we added several systemd-networkd config files to [flatcar-linux/init](https://github.com/flatcar-linux/init), we need to also update coreos-init to pull the newest commit of coreos-init.
See also https://github.com/flatcar-linux/init/pull/6
=> coreos-base/coreos-init: add more systemd-networkd configs

coreos-base/coreos/coreos-0.0.1.ebuild
To make the new tools `bpftool` and `cgroupid` included in the final image, we need to add the tools to the coreos packages list.
=> coreos-base: add bpftool and cgroupid to the base packages list

profiles/coreos/amd64/generic/make.defaults, profiles/coreos/amd64/sdk/make.defaults
To be able to prevent the Spectre v2, we should add the following CFLAGS `-mindirect-branch=thunk` and `-mindirect-branch-register` for the general profile.
See also:
https://security.googleblog.com/2018/01/more-details-about-mitigations-for-cpu_4.html
https://groups.google.com/forum/#!topic/linux.gentoo.user/6xUuPccmxtU
=> profiles: add CFLAGS to prevent the Spectre v2

app-emulation/cri-o/cri-o-1.13.5.ebuild, app-emulation/cri-o/files/0001-Remove-go-build-i-flag.patch, coreos-base/coreos/coreos-0.0.1.ebuild, coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
There has been a corner case where `make bin/crio` failed like that:
```
go build runtime/cgo: open /usr/lib/go1.12/pkg/linux_amd64/runtime/cgo.a: permission denied
make: *** [Makefile:99: bin/crio] Error 1
```
The failure happens only under certain circumstances, for example in Jenkins pipelines, where the standard Go runtime path `/usr/lib/go1.12` is not writable for normal users like `jenkins`. On the other hand, the failure is not reproducible when testing locally, nor when testing with the root user who can write to the Go runtime path.
What happens is, the standard Go runtime sometime has incorrect timestamps or checksums of `cgo.a`, which makes `go build -i` think that it has to install its own library to the system directory. That's obviously not what the build process should do. …
=> app-emulation/cri-o: disable go build install flag

sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
To get pre-defined kernel-specific variables, the ebuild needs to inherit `linux-info`.
Otherwise the `$KV_FULL` simply becomes an empty string. As a result, most firmware files are not installed.
=> sys-kernel/coreos-firmware: add a missing linux-info dependency

sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
In order to build `coreos-firmware` correctly, we need to set `$KERNEL_DIR` and `$KBUILD_OUTPUT` before doing `inherit linux-info`. Otherwise `$KV_FULL` ends up being an invalid path, and as a result, `coreos-firmware` becomes an empty package.
Also we should make `coreos-firmware` depend on `coreos-sources` and `coreos-modules`, to be able to get a correct list of kernel modules.
We should exclude files that does include a space character `' '` from the firmwares list, to avoid kola tests errors like the following.
```
--- FAIL: cl.filesystem/blacklist (0.20s)
files.go:210: Blacklisted files or directories found:
/usr/lib64/firmware/brcm/brcmfmac43430a0-sdio.ONDA-V80 PLUS.txt
```
=> sys-kernel: fix kernel build path issues to build coreos-firmware

app-emulation/cri-o/cri-o-1.14.4.ebuild
`conmon` is installed as `/usr/libexec/crio/conmon`, so an example config of crio should also have the path without `local`.
=> app-emulation: fix path to conmon in the example crio.conf

profiles/coreos/amd64/generic/package.use, profiles/coreos/amd64/sdk/package.use, profiles/coreos/amd64/sdk/use.mask
To be able to fix the issue of torcx tarballs not being able to have selinux contexts, we need to enable selinux for the sdk profile.
Also enable selinux for tar package in the generic profile.
=> profiles: enable selinux for tar,coreutils for sdk profile

profiles/coreos/targets/generic/oem-aci/package.provided
To fix the recent issues about `oem-gce.service` crashlooping, we need to bring back python 2.7 instead of 3.6.5 in `package.provided`.
Otherwise `oem-gce.service` will not start.
See also https://github.com/coreos/bugs/issues/2608,
https://github.com/coreos/coreos-overlay/pull/3746
=> profiles/oem-aci: bring back python 2.7 to fix oem-gce crashlooping

sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
When the Manifest was updated in
e0e285c0bf7a6953fafbe10a5539bc8c84dbf48f
the commit reference in coreos-firmware-99999999.ebuild
was still pointing to the old file.
This led to a failed download verification.
Use the commit ID which the Manifest expects to be used
for the download.
=> sys-kernel: Update commit reference to match the Manifest

coreos-devel/mantle/mantle-9999.ebuild, sys-apps/ignition/ignition-9999.ebuild
See https://github.com/flatcar-linux/mantle/pull/26 and https://github.com/flatcar-linux/scripts/pull/22 which in combination with this PR do what https://github.com/flatcar-linux/ignition/issues/2 did for stable/beta/alpha.
Because https://github.com/flatcar-linux/ignition/pull/4 is not merged yet, this is effectively a downgrade of Ignition. Consider to delay merging this until it can use the latest commit after https://github.com/flatcar-linux/ignition/pull/4 got merged.
=> Use mantle/ignition versions which have the opt/org.flatcar-linux Ignition variable

sys-apps/dbus/dbus-1.10.18-r1.ebuild, sys-apps/dbus/files/CVE-2019-12749.patch
To fix the security issue about authentication bypass, [CVE-2019-12749](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-12749), backport the patch to dbus 1.10.18.
See also https://github.com/coreos/coreos-overlay/pull/3761,
https://security.gentoo.org/glsa/201909-08
=> sys-apps/dbus: fix authentication bypass issue in D-Bus

profiles/coreos/base/package.accept_keywords, profiles/coreos/targets/sdk/package.accept_keywords
To build Flatcar with perl 5.28.2, we need to also add some keywords for related packages.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/10.
=> accept_keywords for perl packages

profiles/coreos/base/package.accept_keywords, profiles/coreos/targets/sdk/package.accept_keywords
We need to add the new keywords to be able to build perl 5.28.
=> profiles: add keywords for perl-Getopt-Long

profiles/coreos/base/package.mask
To avoid slot conflicts between perl versions, we need to pin perl to 5.28.2-r1, and mask other versions.
=> profiles: mask perl 5.26 and 5.30

profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.mask, profiles/coreos/base/package.unmask, profiles/coreos/targets/generic/package.mask, profiles/coreos/targets/sdk/package.accept_keywords, profiles/coreos/targets/sdk/package.mask, profiles/coreos/targets/sdk/package.unmask
To unblock other builds, let's revert perl back to 5.26.1.
together with https://github.com/flatcar-linux/portage-stable/pull/12
=> revert perl to 5.26.1

app-emulation/cri-o/cri-o-1.15.2.ebuild
We should replace `/usr/local/libexec` with `/usr/libexec` also in `crio-wipe.service`.
Otherwise `crio-wipe.service` will not start at all.
Fixes https://github.com/flatcar-linux/Flatcar/issues/9
=> app-emulation/cri-o: fix path prefix in crio-wipe.service

net-libs/rpcsvc-proto/files/rpcsvc-proto-1.3.1-rpcgen-from-host.patch
`rpcsvc-proto` started failing due to a missing binary `rpcgen`, during the Jenkins pipeline for SDK.
We need to have a fallback mechanism for trying both the built-in rpcgen and the host rpcgen.
=> net-libs/rpcsvc-proto: make rpcgen work for both architectures

dev-lang/rust/rust-1.36.0.ebuild
When building ebuilds under catalyst stage4, emerge cannot write data outside of its chroot, under `/tmp` on the host.
That's the reason why the rust installation from toolchain fails like `/tmp/cc.sh: Permission denied`.
That is no issue when building it under local SDK, because in that case there is no toolchain installation involved.
So we should write the temporary scripts under `${S}`, for example, `/mnt/host/source/src/build/catalyst/tmp/coreos-toolchains/stage4-amd64-2303.2.1/`.
=> dev-lang/rust: store shell scripts under source dir instead of /tmp

profiles/coreos/base/package.accept_keywords
So far libselinux was not installed for arm64, because it was simply masked.
We need to enable keywords for both libselinux and libsepol, to correctly build arm64 images including SELinux libs and binaries.
=> profiles: add libselinux keywords to the base profile

app-admin/kubelet-wrapper/files/kubelet-wrapper, app-admin/kubelet-wrapper/kubelet-wrapper-0.0.4-r2.ebuild, metadata/md5-cache/app-admin/kubelet-wrapper-0.0.4-r2
It is not simple for kubelet-wrapper to use docker, because upper layers like Lokomotive or Typhoon still rely on rkt-specific flags and env variables.
So let's revert it back to rkt, so we can make kubelet-wrapper work again with the existing code.
Note, in the long run, we should figure out how we can make the wrapper work with both docker and rkt, at least for a transition period.
This reverts commit 8a03df3ede2f696f4f6ae03931ff62851c8a37fb.
=> Revert "app-admin/kubelet-wrapper: replace rkt with docker"

coreos-base/oem-gce/files/files/hosts, coreos-base/oem-gce/files/units/oem-gce.service
When a custom DNS server is used on the system, the oem-gce
container cannot resolve metadata.google.internal anymore.
- Add metadata.google.internal to /etc/hosts.
- Bind mount nsswitch.conf for /etc/hosts because
the host's /etc/nsswitch.conf is a symlink to
/usr/share/google-oslogin/nsswitch.conf
but that is not present in the rkt container.
Do not only bind-mount /etc but also the target
of the symlink. With a broken nsswitch.conf
any entries in /etc/hosts are not considered
which makes problems when a custom DNS server
is used.
Note: Should be merged for alpha and edge as well.
=> coreos-base/oem-gce: Fix resolving metadata.google.internal via /etc/hosts

app-arch/torcx/files/docker-1.12-no.json
When /etc/flatcar/docker-1.12 contains "no"
the profile for 18.06 was searched for instead
of 19.03. Keep docker-1.12-no.json in sync
with the latest version in app-torcx/docker/files/.
**Note:** Should be cherry-picked for alpha flatcar-build-2387(.0.0) as well.
=> app-arch/torcx: Fix wrong profile reference

coreos-base/afterburn/files/coreos-metadata.service
Only the file /run/metadata/flatcar was created but
for compatibility we should also keep a symlink to it
at /run/metadata/coreos.
Note: Should also be picked for alpha and edge.
=> coreos-base/afterburn: Create symlink for /run/metadata/coreos

coreos-base/coreos-init/coreos-init-9999.ebuild
Includes https://github.com/flatcar-linux/init/pull/14
**Note:** Should also be picked for edge and alpha channels.
=> coreos-base: Update coreos-init for the installer symlink

app-admin/etcd-wrapper/etcd-wrapper-3.3.18.ebuild, app-admin/etcd-wrapper/files/etcd-member.service, app-admin/etcd-wrapper/files/etcd-wrapper, app-admin/flannel-wrapper/files/flannel-docker-opts.service, app-admin/flannel-wrapper/files/flannel-wrapper, app-admin/flannel-wrapper/files/flanneld.service, app-admin/flannel-wrapper/flannel-wrapper-0.11.0.ebuild, app-admin/toolbox/toolbox-9999.ebuild
We replaced rkt with docker via https://github.com/flatcar-linux/coreos-overlay/pull/103 for Edge, and later got it back to docker via https://github.com/flatcar-linux/coreos-overlay/pull/148.
However, we did not revert commits for other wrappers, like etcd-wrapper or flannel-wrapper.
Let's do the revert for other wrappers as well, to unbreak issues around etcd, which happened with Lokomotive clusters recently.
=> Use rkt again instead of docker in etcd/flannel-wrappers for Edge

profiles/coreos/targets/generic/package.use, profiles/coreos/targets/sdk/package.use
Unlike elfutils 0.169, elfutils 0.178 does not install its static library `libelf.a`, unless a USE flag `static-libs` is specified.
We need to enable `static-libs` for `dev-libs/elfutils`, to avoid build errors from packages like bpftool.
=> profiles: enable static-libs for dev-libs/elfutils

sys-apps/systemd/systemd-9999.ebuild
Update systemd v241 commit to the latest one, to address [CVE-2020-1712](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-1712).
=> sys-apps/systemd: bump systemd v241 to address CVE-2020-1712

sys-apps/ignition/ignition-0.33.0-r2.ebuild, sys-apps/ignition/ignition-9999.ebuild
Contains the fix for QEMU. Should be cherry-picked for Alpha/Edge, too.
=> sys-apps/ignition: Point to current flatcar-master

app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild, app-emulation/docker-runc/files/0001-temporarily-disable-selinux.GetEnabled-error-checks.patch
Do not error out if SELinux is specified but disabled
on the system.
=> app-emulation/docker-runc: Disable SELinux warnings

sys-apps/systemd/systemd-9999.ebuild
With the update to Systemd 243 timesyncd
is not enabled by default.
Force enabling it as we do with networkd
and resolved.
=> sys-apps/systemd: Enable timesyncd

.github/workflows/kernel-apply-patch.sh, .github/workflows/kernel-releases-alpha.yml, .github/workflows/kernel-releases-edge.yml, .github/workflows/setup-flatcar-sdk.sh
This PR add 2 different Github actions that run once in a day, one for Alpha, Kernel 4.19, and the other for Edge, Kernel 5.5.
Because of limitations of Github Actions, i.e. create-pull-request actions, we cannot combine the two actions into one. Also we need to create a patch and apply it to the top source directory, since the create-pull-request action requires the changes in the top
directory.
Although we are not updating `flatcar-master` branch, (only Alpha and Edge) the Github actions files need to be merged to `flatcar-master`, because Github actions can only schedule cron jobs from the default branch, `flatcar-master`.
=> .github: schedule daily Github actions for Kernel

sys-apps/systemd/systemd-9999.ebuild
When the initramfs gave a persistent name to
a network interface, renaming it via Name is
not working with the v238 naming scheme even
if NamePolicy is unset.
Switch to the newest network interface naming
scheme to resolve this issue.
https://github.com/flatcar-linux/Flatcar/issues/36
=> sys-apps/systemd: Set interface naming scheme to latest

coreos-base/update_engine/update_engine-9999.ebuild
Pulls in
https://github.com/flatcar-linux/update_engine/pull/2
=> coreos-base/update_engine: Point to flatcar-master

coreos-base/oem-cloudstack/files/flatcar-setup-environment, coreos-base/oem-exoscale/files/flatcar-setup-environment, coreos-base/oem-interoute/files/flatcar-setup-environment, coreos-base/oem-niftycloud/files/flatcar-setup-environment, coreos-base/oem-rackspace/files/flatcar-setup-environment, coreos-base/oem-vagrant/files/box/configure_networks.rb, coreos-base/oem-vagrant/files/flatcar-setup-environment
The variables in /etc/environment are prefixed with COREOS_,
similar to how afterburn variables are prefixed with COREOS_.
They are not to be renamed.
=> coreos-base/oem-*: Fix coreos-cloudinit (cloud-config) variables

.github/workflows/kernel-apply-patch.sh
In the commit message, we should use a prefix `sys-kernel`, without `coreos-sources`.
Also make the entire Github actions not fail if the current release is already the latest Kernel.
=> .github: fix a commit message and exit code in Kernel workflows

coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
Pulls in
https://github.com/flatcar-linux/coreos-cloudinit/pull/3
=> coreos-base/coreos-cloudinit: Point to flatcar-master

.github/workflows/kernel-releases-alpha.yml, .github/workflows/kernel-releases-edge.yml
To reduce running time of git clone, we should avoid a full git clone of the linux kernel repo.
Instead, we shallow clone the repo, and parse tags list by running `git ls-remote`.
=> .github: git shallow clone instead of full clone for kernel

.github/workflows/go-apply-patch.sh, .github/workflows/go-releases-alpha.yml, .github/workflows/go-releases-edge.yml
Schedule daily Github actions for creating PRs for upstream Go releases, just like Kernel.
Replaces https://github.com/flatcar-linux/coreos-overlay/pull/186
=> .github: schedule daily Github actions for Go

sys-kernel/bootengine/bootengine-9999.ebuild
Pulls in https://github.com/flatcar-linux/bootengine/pull/10
=> sys-kernel/bootengine: Point to flatcar-master

.github/workflows/setup-flatcar-sdk.sh
We need to set up coreos profiles under `/etc/portage/repos.conf`, to be able to run any package-related actions like `emerge` or `egencache`.
Also change permissions for directories, so portage actions could write files.
=> .github: set up coreos profiles after setting up SDK

.github/workflows/docker-apply-patch.sh, .github/workflows/docker-releases-alpha.yml, .github/workflows/docker-releases-edge.yml
Schedule daily Github actions to get upstream Docker releases, for Alpha and Edge.
We need to change more files, as Docker version is used by `torcx` as well as `docker-runc`.
Should be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/221
=> .github: schedule daily Github actions for Docker

.github/workflows/runc-apply-patch.sh, .github/workflows/runc-releases-alpha.yml, .github/workflows/runc-releases-edge.yml
Schedule daily Github actions for upstream runc releases, just like Docker.
In this case, we also need to update multiple repos like `app-emulation/docker`, `app-emulation/containerd`, `app-torcx/docker`, etc.
Depends on https://github.com/flatcar-linux/coreos-overlay/pull/221
=> .github: schedule daily Github actions for runc

.github/workflows/runc-apply-patch.sh
To be able to sort correctly between official releases and rc releases, we need to add some sed tweaks when getting the original runc version.
=> .github: fix sed expressions in runc-apply-patch

profiles/coreos/base/package.use
Enable a USE flag `tracepath` for iputils to get the `/usr/sbin/tracepath` binary file included in Flatcar images.
Note, the `tracepath` flag is not the same as the existing `traceroute` flag, which enables only `tracerout6`.
=> profiles: build tracepath in iputils

.github/workflows/go-apply-patch.sh, .github/workflows/kernel-apply-patch.sh, .github/workflows/kernel-releases-beta.yml, .github/workflows/kernel-releases-stable.yml
Check for upstream Kernel releases once in a day, for Beta and Stable,
just like it has been done for Alpha and Edge.
=> .github: schedule daily Github actions for Kernel in beta, stable

.github/workflows/kernel-releases-edge.yml
Upgrade the base Kernel version from 5.5 to 5.6 for the Edge channel.
=> .github: update Kernel to 5.6 for Edge

.github/workflows/go-apply-patch.sh, .github/workflows/kernel-apply-patch.sh
We need to generate metadata after the main commit was created.
Also run git format-patch for both commits, main and metadata.
=> .github: fix metadata generation for Kernel and Go

profiles/coreos/base/package.accept_keywords
Now that openssh was updated to 8.1, we need to make openssh accept keywords `~arm64` for it, to avoid build failures.
```
emerge-arm64-usr net-misc/openssh
```
=> profiles: accept keywords ~arm64 for openssh 8.1 for alpha

profiles/coreos/base/package.accept_keywords
Now that openssh was updated to 8.1, we need to make openssh accept keywords `~arm64` for it, to avoid build failures.
```
emerge-arm64-usr net-misc/openssh
```
=> profiles: accept keywords ~arm64 for openssh 8.1 for edge

.github/workflows/docker-apply-patch.sh, .github/workflows/go-apply-patch.sh, .github/workflows/kernel-apply-patch.sh, .github/workflows/runc-apply-patch.sh
Before starting to apply patches inside `coreos-overlay`, we need to check out base branches, also for `scripts` and `portage-stable`.
Otherwise, in case of Beta, Alpha, or Edge, `ebuild` commands could fail due to mismatch of ebuild files across multiple repos like `coreos-overlay` and `portage-stable`.
=> .github: check out correct base branches before applying patches

coreos-base/oem-azure/files/oem-release, coreos-base/oem-digitalocean/files/oem-release, coreos-base/oem-ec2-compat/files/oem-release, coreos-base/oem-gce/files/oem-release, coreos-base/oem-hyperv/files/oem-release, coreos-base/oem-packet/files/oem-release, coreos-base/oem-virtualbox/files/oem-release, coreos-base/oem-vmware/files/oem-release
The bug report URL was pointing to the CoreOS bug tracker.
Change it to Flatcar's bug tracker URL.
- Checkout this branch for coreos-overlay in your SDK
- Build the package and image if not done yet
- Generate the VM images with the printed command but add `--format OEMNAME` to generate a image with the OEM partition
- Mount or boot it and check the content of `/usr/share/oem/oem-release`
None
**Note:** Should be cherry-picked for `flatcar-master-(alpha|beta|edge)`.
=> coreos-base/oem*: Fix bug report URL

.github/workflows/setup-flatcar-sdk.sh
When setting up a Flatcar SDK from scratch, we need to also set up correct configs in `/etc/portage/make.conf`.
For example we need to set `PORTDIR=/mnt/host/source/src/third_party/portage-stable` instead of the default Gentoo configs like `PORTDIR=/var/gentoo/repos/gentoo`.
Otherwise `update_metadata` will fail in some cases, because portage cannot find the correct location of portage-stable.
Tested via a testing repo. It works.
=> .github: use correct make.conf when setting up Flatcar SDK

app-admin/mayday/mayday-9999.ebuild
This pulls in https://github.com/flatcar-linux/mayday/pull/8
to include "coredumpctl list" in the tar ball.
Note: Pick for alpha/beta/edge.
=> app-admin/mayday: Point to flatcar-master

sys-apps/systemd/systemd-9999.ebuild
With the latest systemd version, the lines that sed is removing now
include an exclamation mark, so adapt the sed command to accept both
formats.
These lines need to be removed so that the configuration set in
/usr/lib/tmpfiles.d/pam.conf file can be used (duplicate entries will
lead to systemd not doing anything).
Fixes: flatcar-linux/Flatcar#75
=> Adapt the sed command to the new file contents

sys-apps/systemd/systemd-9999.ebuild
This cherry-picks two commits already applied to flatcar-master
=> Merge changes from flatcar-master to fix missing /etc/pam.d in edge channel

app-admin/flannel-wrapper/files/50-flannel.network
When setting up flannel interfaces, use MACAddressPolicy=none, so that
the MAC Address used is the one set by flannel and not the one assigned
by systemd.
See https://github.com/coreos/flannel/issues/1155 for more information.
This fixes the issue we saw with the vxlan test
=> app-admin/flannel-wrapper: set MACAddressPolicy=none for flannel

app-admin/flannel-wrapper/files/50-flannel.link, app-admin/flannel-wrapper/files/50-flannel.network, app-admin/flannel-wrapper/flannel-wrapper-0.11.0.ebuild
When setting up flannel interfaces, use MACAddressPolicy=none, so that
the MAC Address used is the initial one set by the kernel and not the
one assigned by systemd.
See coreos/flannel#1155 for more information.
In #279 we tried adding the MACAddressPolicy=none setting to the
existing 50-flannel.network file. But the change should have been in a
.link file, not a .network file.
I manually built the edge image, deployed it in packet and verified that ping on the flannel interface worked.
=> app-admin/flannel-wrapper: Create a 50-flannel.link

.github/workflows/common.sh, .github/workflows/docker-apply-patch.sh, .github/workflows/go-apply-patch.sh, .github/workflows/kernel-apply-patch.sh, .github/workflows/runc-apply-patch.sh, .github/workflows/rust-apply-patch.sh, .github/workflows/rust-release-alpha.yml, .github/workflows/rust-release-edge.yml
Schedule daily Github actions for creating PRs for upstream Rust releases.
The Github workflow will create pull request for `dev-lang/rust` in `coreos-overlay`. At the same time, it will send a repository dispatch event to `flatcar-linux/portage-stable`, to update also `virtual/cargo`. We need to send different event types to distinguish alpha from edge.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/28, https://github.com/flatcar-linux/portage-stable/pull/44, https://github.com/flatcar-linux/portage-stable/pull/45, and https://github.com/flatcar-linux/coreos-overlay/pull/221.
=> .github: schedule daily Github actions for Rust

.github/workflows/kernel-apply-patch.sh
`kernel-apply-patch.sh` cannot detect the existing kernel version, if the version does not have a patchlevel, e.g. `5.6`. So the old kernel version variable becomes an empty string, and the final pull request has an empty field after the `from` string.
If the Manifest does not have a `patch-` line, try to read a `linux-` line again, to detect the correct kernel version.
=> .github: detect kernel version correctly

.github/workflows/kernel-releases-alpha.yml
Now that Kernel was updated to 5.4 in flatcar-master-alpha, we need to update also Kernel versions for Alpha in Github actions.
=> .github: update Kernel version to 5.4 for Alpha

.github/workflows/containerd-apply-patch.sh, .github/workflows/containerd-releases-alpha.yml, .github/workflows/containerd-releases-edge.yml, .github/workflows/docker-releases-alpha.yml, .github/workflows/docker-releases-edge.yml, .github/workflows/go-releases-alpha.yml, .github/workflows/go-releases-edge.yml, .github/workflows/runc-releases-alpha.yml, .github/workflows/runc-releases-edge.yml, .github/workflows/rust-release-alpha.yml, .github/workflows/rust-release-edge.yml
To get `containerd` in sync with upstream, we need to schedule weekly Github actions. It runs on Friday every week, only for Alpha and Edge.
Similar to those for Docker, we need to deal with torcx ebuilds as well, as they contain containerd versions.
Also change other Github actions so that they run weekly once to check for usual packages.
We do not need to run once in a day to check for updates from ordinary packages. Most releases happen once in more than a week.
Go on Mon, Rust on Tue, Docker on Wed, Runc on Thu.
Note, we still need to check for Kernel once in a day, as Kernel releases happen quite often.
=> .github: schedule weekly Github actions for containerd

coreos-base/oem-vmware/files/grub.cfg
The user can only login via SSH if no password was set and can't login
over the VGA console in the web UI. To login the user needs to press
reboot and then append flatcar.autologin to the kernel command line parameters
in GRUB each time. The user may also not know that this option even exists.
Set flatcar.autologin by default in the kernel command line parameters for
VMware so that users don't need to set this themselves.
Build the image and use it with VMware ESX or Workstation.
Tested on ESXi.
**Note:** Pick for other channels.
=> coreos-base/oem-vmware: Use flatcar.autologin for the console

profiles/coreos/targets/sdk/package.use
Now that `cross-{x86_64,aarch64}-cros-linux-gnu/gdb` was updated to 9.1, it needs exactly one of `python_single_target_python3_6` and `python_single_target_python3_7`.
Since python 3.7 is not available yet, we need to enable 3.6 and disable 3.7, for the SDK profile.
Without the fix, toolchain builds will fail like that:
```
!!! The ebuild selected to satisfy "cross-aarch64-cros-linux-gnu/gdb"
has unmet requirements.
- cross-aarch64-cros-linux-gnu/gdb-9.1-r1::x-crossdev USE="client nls python server -lzma -multitarget -source-highlight -test -vanilla -xml -xxhash"
PYTHON_SINGLE_TARGET="-python3_6 (-python3_7)" PYTHON_TARGETS="python3_6 (-python3_7)"
The following REQUIRED_USE flag constraints are unsatisfied:
python? ( exactly-one-of ( python_single_target_python3_6 …
```
=> profile: set python 3.6 single target for cross builds for alpha

profiles/coreos/targets/sdk/package.use
Now that `cross-{x86_64,aarch64}-cros-linux-gnu/gdb` was updated to 9.1, it needs exactly one of `python_single_target_python3_6` and `python_single_target_python3_7`.
Since python 3.7 is not available yet, we need to enable 3.6 and disable 3.7, for the SDK profile.
Without the fix, toolchain builds will fail like that:
```
!!! The ebuild selected to satisfy "cross-aarch64-cros-linux-gnu/gdb"
has unmet requirements.
- cross-aarch64-cros-linux-gnu/gdb-9.1-r1::x-crossdev USE="client nls python server -lzma -multitarget -source-highlight -test -vanilla -xml -xxhash"
PYTHON_SINGLE_TARGET="-python3_6 (-python3_7)" PYTHON_TARGETS="python3_6 (-python3_7)"
The following REQUIRED_USE flag constraints are unsatisfied:
python? ( exactly-one-of ( python_single_target_python3_6 …
```
=> profile: set python 3.6 single target for cross builds for edge

.github/workflows/containerd-releases-alpha.yml, .github/workflows/containerd-releases-edge.yml, .github/workflows/docker-releases-alpha.yml, .github/workflows/docker-releases-edge.yml, .github/workflows/go-releases-alpha.yml, .github/workflows/go-releases-edge.yml, .github/workflows/kernel-releases-alpha.yml, .github/workflows/kernel-releases-beta.yml, .github/workflows/kernel-releases-edge.yml, .github/workflows/kernel-releases-stable.yml, .github/workflows/runc-releases-alpha.yml, .github/workflows/runc-releases-edge.yml, .github/workflows/rust-release-alpha.yml, .github/workflows/rust-release-edge.yml, .github/workflows/setup-flatcar-sdk.sh
We do not need to specify a cork version from each Github action.
Simply detect the latest version in `setup-flatcar-sdk.sh`, before downloading cork binary file from Github.
Also remove the env variable for cork version from each Github action.
=> .github: detect latest cork version during SDK setup

profiles/coreos/base/package.accept_keywords
Now that edk2-ovmf was updated to 201905, we need to also fix edk2-ovmf
to 201905 for ~arm64, so we can avoid build errors.
```
sudo emerge -1 edk2-ovmf
emerge --emptytree -p -v --tree coreos-base/hard-host-depends coreos-devel/sdk-depends
```
=> profiles: bump edk2-ovmf to 201905 for alpha

profiles/coreos/base/package.accept_keywords
Now that edk2-ovmf was updated to 201905, we need to also fix edk2-ovmf
to 201905 for ~arm64, so we can avoid build errors.
```
sudo emerge -1 edk2-ovmf
emerge --emptytree -p -v --tree coreos-base/hard-host-depends coreos-devel/sdk-depends
```
=> profiles: bump edk2-ovmf to 201905 for edge

profiles/coreos/base/package.accept_keywords
Since fero-client pulls in `virtual/rust` and other rust-related packages, we need to enable keywords for fero-client.
```
emerge --emptytree -p -v coreos-base/hard-host-depends coreos-devel/sdk-depends
```
=> profiles: enable fero-client for alpha

profiles/coreos/base/package.accept_keywords
Since fero-client pulls in `virtual/rust` and other rust-related packages, we need to enable keywords for fero-client.
```
emerge --emptytree -p -v coreos-base/hard-host-depends coreos-devel/sdk-depends
```
=> profiles: enable fero-client for edge

coreos-base/oem-azure/files/grub.cfg
The user can only login via SSH if no password was set and can't login
over the serial console in the web UI. To login, the user needs to press
reboot and then append flatcar.autologin to the kernel command line parameters
in GRUB each time. The user may also not know that this option even exists.
Set flatcar.autologin by default in the kernel command line parameters for
Azure so that users don't need to set this themselves.
Deploy a VM on Azure with an image built from this branch (e.g., use `kola spawn --platform azure --azure-image-file FILENAME …`).
Click on the VM in the web UI and select _Serial console_ from the menu, there you see the prompt (hit Enter a few times if log messages were printed over the prompt).
I modified the file manually in the OEM partition and rebooted for it …
=> coreos-base/oem-azure: Use flatcar.autologin for the serial console

profiles/coreos/base/package.use
See https://github.com/flatcar-linux/Flatcar/issues/101
This PR adds ONIGURUMA regex libary to support regular expressions in jq tool
See https://github.com/flatcar-linux/Flatcar/issues/101 for the testcase
Tested with local SDK setup. After rebuild i see that it is linked with libonig library:
```
builder@localhost ~/trunk/src/scripts $ ldd /mnt/host/source/chroot/build/amd64-usr/usr/bin/jq
linux-vdso.so.1 (0x00007ffe54d57000)
libjq.so.1 => /usr/lib64/libjq.so.1 (0x00007efc495b8000)
libc.so.6 => /lib64/libc.so.6 (0x00007efc493e0000)
libm.so.6 => /lib64/libm.so.6 (0x00007efc49296000)
libonig.so.5 => /usr/lib64/libonig.so.5 (0x00007efc49205000)
/lib64/ld-linux-x86-64.so.2 (0x00007efc49614000)
```
Also test from my testcase is now passing:
```
builder@localhost ~/trunk/src/scripts $ echo …
```
=> Set oniguruma USE flag for the jq package

coreos-base/coreos-init/coreos-init-9999.ebuild
Pulls in https://github.com/flatcar-linux/init/pull/18 to describe
that setting OEM uses an OEM image.
Note: Pick for all channels.
=> coreos-base/coreos-init: Point to latest flatcar-master

.github/workflows/common.sh, .github/workflows/containerd-apply-patch.sh, .github/workflows/containerd-releases-alpha.yml, .github/workflows/containerd-releases-edge.yml, .github/workflows/docker-apply-patch.sh, .github/workflows/docker-releases-alpha.yml, .github/workflows/docker-releases-edge.yml, .github/workflows/go-apply-patch.sh, .github/workflows/go-releases-alpha.yml, .github/workflows/go-releases-edge.yml, .github/workflows/kernel-apply-patch.sh, .github/workflows/kernel-releases-alpha.yml, .github/workflows/kernel-releases-beta.yml, .github/workflows/kernel-releases-edge.yml, .github/workflows/kernel-releases-stable.yml, .github/workflows/runc-apply-patch.sh, .github/workflows/runc-releases-alpha.yml, .github/workflows/runc-releases-edge.yml, .github/workflows/rust-apply-patch.sh, .github/workflows/rust-release-alpha.yml, .github/workflows/rust-release-edge.yml
In case the target branch already exists, `checkout_branch()` needs to simply `exit 0`, so the subsequent steps could be skipped.
In that case, it has to set `UPDATE_NEEDED` to 0, so the Github action could avoiding creating another PR.
It resolves occasional issues that happen when subsequent PRs overwrite existing open PRs made on the very same version.
It would be no problem if there was no change in the PR.
However, if there was any manual change in the previous open PR, the change will be simply overwritten. That would be very unfortunate.
=> .github: skip branch checkout if it exists

sys-kernel/bootengine/bootengine-9999.ebuild
Fixes https://github.com/flatcar-linux/Flatcar/issues/83.
This is a follow up from https://github.com/flatcar-linux/bootengine/pull/12.
Fixes a race between switching root and unmounting a boot mountpoint with a tool existing only in the old root.
The repro is described in the issue linked above.
Same as in the PR linked above.
=> sys-kernel/bootengine: bump to fix the sysroot-boot service race

.github/workflows/common.sh, .github/workflows/containerd-apply-patch.sh, .github/workflows/docker-apply-patch.sh, .github/workflows/go-apply-patch.sh, .github/workflows/kernel-apply-patch.sh, .github/workflows/runc-apply-patch.sh, .github/workflows/rust-apply-patch.sh
`exit` command will simply fail the whole script, so it would not be possible to check for status of `checkout_branches`.
Instead, we need to use `return` for the error checks.
=> .github: correctly check status of checkout_branches

sys-apps/seismograph/seismograph-9999.ebuild
Pulls in https://github.com/flatcar-linux/seismograph/pull/4
to fix setting GPT labels with cgpt.
Note: For all channels and current Alpha release.
=> sys-apps/seismograph: Point to latest flatcar-master

sys-kernel/bootengine/bootengine-9999.ebuild
Pulls in https://github.com/flatcar-linux/bootengine/pull/13
=> sys-kernel/bootengine: Point to latest flatcar-master

coreos-base/update_engine/update_engine-9999.ebuild
Pulls in https://github.com/flatcar-linux/update_engine/pull/5
=> coreos-base/update_engine: Point to latest flatcar-master

.github/workflows/kernel-releases-beta.yml
Now that we updated Kernel to 5.4 for Beta, we also need to set Kernel
version to 5.4 in Github Actions.
This PR should be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/362.
=> .github: update Kernel version to 5.4 for beta

app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild, app-emulation/docker/docker-9999.ebuild, metadata/md5-cache/app-emulation/docker-19.03.8
Since docker-ce v18.09, the upstream repo github.com/docker/docker-ce has changed its way of version tagging, from `$VERSION-ce` to `$VERSION`.
As a result, e.g. for v19.03.8, https://github.com/docker/docker-ce/archive/v19.03.8-ce.tar.gz is not valid any more. It must be actually https://github.com/docker/docker-ce/archive/v19.03.8.tar.gz.
So we need to remove the suffix `-ce` from every version since v18.09.
=> app-emulation/docker: Fix URLs for docker-ce tarballs for alpha

app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild, app-emulation/docker/docker-9999.ebuild, metadata/md5-cache/app-emulation/docker-19.03.8
Since docker-ce v18.09, the upstream repo github.com/docker/docker-ce has changed its way of version tagging, from `$VERSION-ce` to `$VERSION`.
As a result, e.g. for v19.03.8, https://github.com/docker/docker-ce/archive/v19.03.8-ce.tar.gz is not valid any more. It must be actually https://github.com/docker/docker-ce/archive/v19.03.8.tar.gz.
So we need to remove the suffix `-ce` from every version since v18.09.
=> app-emulation/docker: Fix URLs for docker-ce tarballs for edge

.github/workflows/runc-apply-patch.sh
docker-runc ebuild has lines of runc versions with not only underscore (`_`) but also hyphen (`-`).
So when we replace the runc version, we need to also care about versions with hyphen, for example, `1.0.0-rc10`.
=> .github: fix version format in docker-runc

profiles/coreos/amd64/generic/package.use, profiles/coreos/arm64/package.provided, profiles/coreos/arm64/package.use, profiles/coreos/base/package.use, sys-auth/sssd/sssd-1.13.1-r7.ebuild
`net-dns/bind-tools` has been disabled since a long time, probably because of build errors around cross-compilation for ARM. However, bind-tools binaries should be at least included in ARM images.
So enable `bind-tools` again for ARM without `gssapi` included.
To do that, disable gssapi for bind-tools only in the ARM profile, and enable gssapi only in the AMD profile.
Now that bind-tools are built with gssapi only for AMD, without gssapi for ARM, we need to get the USE flag for `sys-auth/sssd` requirement relaxed. Profile for each architecture will instead choose whether to use gssapi.
```
emerge-arm64-usr net-dns/bind-tools sys-auth/sssd
```
=> profiles: enable bind-tools again for ARM for alpha

profiles/coreos/amd64/generic/package.use, profiles/coreos/arm64/package.provided, profiles/coreos/arm64/package.use, profiles/coreos/base/package.use, sys-auth/sssd/sssd-1.13.1-r7.ebuild
`net-dns/bind-tools` has been disabled since a long time, probably because of build errors around cross-compilation for ARM. However, bind-tools binaries should be at least included in ARM images.
So enable `bind-tools` again for ARM without `gssapi` included.
To do that, disable gssapi for bind-tools only in the ARM profile, and enable gssapi only in the AMD profile.
Now that bind-tools are built with gssapi only for AMD, without gssapi for ARM, we need to get the USE flag for `sys-auth/sssd` requirement relaxed. Profile for each architecture will instead choose whether to use gssapi.
```
emerge-arm64-usr net-dns/bind-tools sys-auth/sssd
```
=> profiles: enable bind-tools again for ARM for edge

profiles/coreos/arm64/package.accept_keywords
The port of the commit did introduce other arm64 flags than those
used in Beta.
Align them again.
=> net-firewall/conntrack-tools: Use same flags as Beta

sys-apps/systemd/systemd-9999.ebuild
With systemd 243, few of the services from whom the symlinks were created automatically are no longer created and a `systemctl preset-all` is recommended to run after the installation
From what I saw in the [Gentoo ebuild](https://github.com/flatcar-linux/coreos-overlay/blob/flatcar-master-alpha/sys-apps/systemd/systemd-9999.ebuild#L499-L500) - In case of installation, if the package is [replacing an outdated package](https://github.com/flatcar-linux/coreos-overlay/blob/flatcar-master-alpha/sys-apps/systemd/systemd-9999.ebuild#L497), it then enables the `getty` and `remote-fs`and then recommends running `preset-all`
On the other hand, I checked Fedora where it runs `systemctl preset-all` upon installation.
For fixing the issue …
=> sys-apps/systemd: Manually enable the getty service

app-admin/etcd-wrapper/files/etcd-wrapper, app-admin/flannel-wrapper/files/flannel-wrapper, app-admin/kubelet-wrapper/files/kubelet-wrapper
When 788f328dc752a75da08d4c6fc27d094ecb4807d5 introduced pulling from
docker by default, "--insecure-options=image" was added for all
docker registries. However, when the user also needs to set "http" as
in "--insecure-options=image,http" it will not be used because the
other argument is added as last disregarding the option was already
set by the user.
Check if the option was set by the user and only add it if it is not
provided. If the user forgets to add "image" then rkt will simply
fail and tell that this option is needed; thus no complex logic of
appending and detecting only "image" is needed. Do the same for the
"--trust-keys-from-https" option to be consistent in allowing to
overwrite it with "--trust-keys-from-https=false".
```
sudo KUBELET_IMAGE_TAG=v1.9.6_coreos.2 …
```
=> app-admin/*-wrapper: Only set arguments that weren't set

.github/workflows/rust-apply-patch.sh
We need to update rust versions also in multiple files in profiles, e.g. `package.accept_keywords`.
Otherwise `emerge rust` will fail, due to mismatches between rust versions, in profiles and the actual ebuilds.
=> .github: update rust versions also in profiles

profiles/coreos/arm64/package.use.force, profiles/coreos/base/package.use.force
When catalyst tries to fetch a file via https, wget sometimes fails to do so, with the following messages:
```
https://www.kernel.org/pub/software/scm/git/git-2.24.1.tar.xz: HTTPS
support not compiled in.
!!! Couldn't download 'git-2.24.1.tar.xz'. Aborting.
```
That probably happens because wget in some catalyst stages are compiled without `ssl` USE flag.
If a catalyst stage is lucky enough to rebuild wget with `ssl` before actually fetching a file, it would work well.
Though if not, it would fail.
It is not deterministic, and hard to reproduce.
So backport the [fix](https://github.com/gentoo/gentoo/commit/d141380b915d) from upstream Gentoo,  for both amd64 and arm64.
By setting `ssl` for wget in `package.use.force`, it is now not possible to disable `ssl` for wget.
More details: …
=> profiles: force to use ssl USE flag for wget

.github/workflows/kernel-releases-edge.yml
Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>
This should be merged after #433 is merged
=> .github/workflows: Update the kernel release edge version to 5.7

app-emulation/docker/docker-9999.ebuild
Since Docker >= 19.03.9 started to depend on `github.com/pkg/errors` v0.9.1 or newer, it is now necessary to set `go1.13` in `DOCKER_BUILDTAGS`.
Otherwise, it cannot find `Is` function.
See also https://github.com/pkg/errors/blob/v0.9.1/go113.go#L16 .
```
```
=> app-emulation/docker: set go1.13 in DOCKER_BUILDTAGS for edge

app-admin/etcd-wrapper/etcd-wrapper-3.3.20.ebuild, app-admin/etcd-wrapper/files/etcd-member.service
even though they're still building from quay.io/coreos/etcd? maybe
that'll change soon too?
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
etcd has been promoted to its own org now
click the links
Tested that the new links work. (and that the quay.io/coreos/etcd are  still correct as well)
=> etcd: update URL to its own org on github now

profiles/coreos/arm64/package.use.force, profiles/coreos/base/package.use.force
This reverts commit 517e23ebfe96137f1482ae42f8b29fc2f1b31317.
The new USE flag `ssl` for wget resulted in a strange issue.
`wget` started to pull in `dev-libs/openssl`, which has `bindist` in its USE flag.
The catalyst stages, however, need to install wget without `bindist`.
Such mismatches resulted in errors like:
```
!!! All ebuilds that could satisfy "dev-libs/openssl:0=" for /tmp/stage1root/ have been masked.
!!! One of the following masked packages is required to complete your request:
- dev-libs/openssl-1.0.2u::coreos (masked by: bindist in RESTRICT)
```
So to fix the issue, what needs to be done is basically:
```
ACCEPT_RESTRICT=bindist USE=-bindist emerge -pv openssl openssh
```
Unfortunately it is not possible to set `accept_restrict` configs under the coreos-overlay repo.
We …
=> Revert "profiles: force to use ssl USE flag for wget"

app-admin/locksmith/locksmith-9999.ebuild
Pulls in
https://github.com/flatcar-linux/locksmith/pull/4
```
emerge-amd64-usr -1 locksmith
./build_image
./image_to_vm […]
```
Boot up VM and check that `locksmithd` is running and `locksmithctl` binaries work.
Note: Pick for all channels.
=> app-admin/locksmith: Migrate to Go modules

.github/workflows/runc-apply-patch.sh, .github/workflows/runc-releases-alpha.yml, .github/workflows/runc-releases-edge.yml
So far Github actions have not changed existing `COMMIT_ID` variable in runc ebuilds.
As a result, the result PRs have correct versions with wrong commit hashes.
We need to replace `COMMIT_ID` with one that matches with the new version.
To do that, clone the repo completely, since it is not possible to get the commit hash by running `git rev-parse` on a shallow cloned repo.
Parse commit from a tag with an original version with `-` as its delimiter, e.g. `v1.0.0-rc91`, because a transformed tag like `v1.0.0_rc91` does not exist in the upstream repo.
=> .github: replace COMMIT_ID in runc ebuilds

dev-lang/rust/rust-1.44.1.ebuild
This collects the downstream crossdev patches we currently need in a single commit and applies it to the upstream Rust ebuild file.
Compile Rust in the SDK after setting up an arm64 board
None
Note: Should be adapted for the other channels
=> Apply rust changes

dev-lang/rust/rust-1.36.0.ebuild
This collects the downstream crossdev patches we currently need in a single commit and applies it to the upstream Rust ebuild file. It was needed due to a build failure in Edge but should be in all channels. The hope is that a single commit is easy to port in the future if it's also easy to find in the beginning of the ebuild header.
See https://github.com/flatcar-linux/coreos-overlay/pull/473
Note: Pick for Stable, too. The Edge PR was picked for Alpha.
Compile Rust in the SDK after setting up an arm64 board:
```
./setup_board --board arm64-usr
sudo emerge rust
```
None
=> Apply Rust changes for Beta and Stable

sys-apps/baselayout/baselayout-9999.ebuild, sys-apps/systemd/systemd-9999.ebuild
- Building systemd in the SDK bootstrap failed because the hwdb.d folder
did not exist. The upstream ebuild file has this guard:
https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-apps/systemd/systemd-245.5.ebuild#n390
- sys-apps/baselayout: Work around systemd-tmpfiles not finding libidn2
The baselayout ebuild file calls systemd-tmpfiles but despite that
the systemd ebuild file depends on libidn2 through a use flag, it was
not built early enough.
Ensure that libidn2 is built before baselayout wants to use it.
This change is only relevant for SDK builds.
The SDK built systemd but later the SDK build failed due to unrelated changes.
=> sys-apps/systemd: Guard deletion of hwdb.d folder behind use flag, sys-apps/baselayout: Work around systemd-tmpfiles not finding libidn2

coreos-base/oem-ec2-compat/files/base/base-ec2.ign, coreos-base/oem-ec2-compat/oem-ec2-compat-0.1.2.ebuild, coreos-devel/board-packages/board-packages-0.0.1.ebuild
The amazon-ssm-agent package was never built and caused the vm-matrix
job to find no binary package.
Build it as part of build_packages but don't install it on openstack
or brightbox images. The plan is to add it on EC2 but currently the
binaries are too large.
`./build_packages
…
./build_image
./image_to_vm.sh --format=ami_vmdk …
./image_to_vm.sh --format=openstack …
Images build and AWS AMI runs.
=> Build amazon-ssm-agent package but disable it for now

sys-kernel/bootengine/bootengine-9999.ebuild
This version of bootengine adds a new script, so on top of moving the CROS commit id pointer, we also need to add execution permissions to the new disk-uuid script.
Building an image with this change plus the change in flatcar-linux/scripts#82 leads to GRUB booting successfully on a c3.medium.x86 machine followed by the disk UUID getting randomized.
WIP notice: Due to issues with current flatcar-master-alpha, I wasn't yet able to fully test this change on all platforms, I only manually tested it on Packet. Once alpha is fixed, I'll test again on all platforms.
This needs to be submitted after flatcar-linux/bootengine#17 is in, and together with flatcar-linux/scripts#82
=> bootengine: move to version with disk randomization fix

.github/workflows/setup-flatcar-sdk.sh
The last cork release was signed with a different key.
Import the key to verify the download.
=> .github: Import second signing key

app-admin/toolbox/toolbox-9999.ebuild
This PR points the toolbox `CROS_WORKON_COMMIT` to the latest flatcar-master branch to include BPF fs and syscall support in toolbox (https://github.com/flatcar-linux/toolbox/pull/3).
=> toolbox: point to flatcar-master to add bpf fs support

sys-kernel/coreos-sources/coreos-sources-5.4.61.ebuild, sys-kernel/coreos-sources/files/5.4/z0005-fix-vdso32-for-arm.patch
This change adds a [kernel 5.9 upstream patch](https://lore.kernel.org/linux-arm-kernel/20200827234012.19757-1-fllinden@amazon.com/)  which fixes a vdso build error on ARM:
```
gcc: error: unrecognized argument in option ‘-mabi=aapcs-linux’
gcc: note: valid arguments to ‘-mabi=’ are: ms sysv
gcc: error: unrecognized argument in option ‘-mabi=aapcs-linux’
gcc: note: valid arguments to ‘-mabi=’ are: ms sysv
gcc: error: unrecognized argument in option ‘-mabi=aapcs-linux’
gcc: note: valid arguments to ‘-mabi=’ are: ms sysv
gcc: error: unrecognized command line option ‘-mfloat-abi=soft’
gcc: error: unrecognized command line option ‘-mfloat-abi=soft’
gcc: error: unrecognized command line option ‘-mfloat-abi=soft’
gcc: error: unrecognized command line option ‘-mlittle-endian’; did you mean …
```
=> sys-kernel/coreos-sources: fix vdso32 build for arm

README.md
The best practice established in this repository is to reset the
package	folder and import a new	version	from upstream without
modifications. In a separate commit the downstream changes are applied.
This makes it clear which downstream changes need to be	ported when
updating to a newer version in the future. Unfortunately this is not
always done which causes confusion and more work. As first step
document the process before we later look into more automation.
Follow the guide when updating a package
Ran the `update_ebuilds` command.
=> README.md: Document how	to update packages

coreos-base/coreos-init/coreos-init-9999.ebuild
This updates `CROS_WORKON_COMMIT` of `coreos-init` to include the new update subkey from https://github.com/flatcar-linux/init/pull/25.
Signed-off-by: Thilo Fromm <thilo@kinvolk.io>
=> coreos-init: add new subkey rsa4096/FCBEAB91

sys-kernel/coreos-sources/coreos-sources-5.4.62.ebuild, sys-kernel/coreos-sources/files/5.4/z0005-net_packet_fix_overflow_in_tpacket_rcv_patch.patch
A memory corruption vulnerability in AF_PACKET causes the kernel to
panic or enter undefined behavior, tracked as CVE-2020-14386.
While the proposed patch is not included in an upstream release,
include it as downstream patch.
Further information and PoC:
https://www.openwall.com/lists/oss-security/2020/09/03/3
**Note:** Will be picked for _main_.
A PoC was published on oss-security.
The PoC does not trigger a panic.
=> sys-kernel: Include patch for overflow in tpacket_rcv

.github/workflows/go-apply-patch.sh
Github Action for Go has had a bug when parsing the current Go version from `dev-lang/go/Manifest`, only when the current ebuild file has only major + minor versions, without patchlevel.
For example, it could parse well `1.13.15`, but not `1.15`.
We need to make it deal with both versions, `x.y.z` and `x.y`.
With this PR, for example, when `VERSION_SHORT` is `1.15` and the Manifest includes a tarball `go1.15.src.tar.gz`, we can confirm the new regexp works well like below:
```
$ sed -n "s/^DIST go\(1.15.*[0-9]*\)\.src.*/\1/p" dev-lang/go/Manifest
1.15
```
=> .github: fix regexp to get correct semver from Go ebuilds

.github/workflows/rust-apply-patch.sh, .github/workflows/rust-release-main.yml
Improve body text of each PR for `dev-lang/rust`, by mentioning that it should be merged together with its paired PR in portage-stable.
Explicitly name `dev-lang/rust` instead of `Rust`, because now there are `dev-lang/rust` as well as `virtual/rust`.
Rename the dispatched event-type name to `rust-pull-request-main`, as `cargo` has already disappeared.
Make the repository-dispatch action send additional client-payload with a field `coreos-overlay-pull-request-number`, which will be later used by the corresponding PR in portage-stable for adding a link back to the PR in coreos-overlay.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/103.
=> .github: improve body text of PR for dev-lang/rust

sys-apps/systemd/systemd-9999.ebuild
The latest [`v245-flatcar` commit](https://github.com/flatcar-linux/systemd/commit/d5568ff804c2bda9a3869aa249bb6300aa3be7dd) includes the following PRs:
1. https://github.com/flatcar-linux/systemd/pull/12 - Cherry-pick from v245-stable: Allow nameserver list to be emptied
2. https://github.com/flatcar-linux/systemd/pull/11 - sysctl.d/50-default.conf: remove *, .all source route settings
=> sys-apps/systemd: use latest v245-flatcar

sys-kernel/coreos-sources/coreos-sources-5.8.9.ebuild, sys-kernel/coreos-sources/files/5.8/z0001-kbuild-derive-relative-path-for-srctree-from-CURDIR.patch, sys-kernel/coreos-sources/files/5.8/z0002-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch, sys-kernel/coreos-sources/files/5.8/z0003-net-netfilter-add-nf_conntrack_ipv4-compat-module-fo.patch
These used to apply just fine with the `patch` utility, but `git am` was complaining (when creating the `v5.8.8-flatcar` branch for our linux repo):
```
$ git am ../coreos-overlay/main/sys-kernel/coreos-sources/files/5.8/z0003-net-netfilter-add-nf_conntrack_ipv4-compat-module-fo.patch
Applying: net/netfilter: add nf_conntrack_ipv4 compat module for kube-proxy
error: patch failed: net/netfilter/Makefile:24
error: net/netfilter/Makefile: patch does not apply
Patch failed at 0001 net/netfilter: add nf_conntrack_ipv4 compat module for kube-proxy
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run …
```
=> sys-kernel/coreos-sources: Regenerate the patches against 5.8.9

profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.use
Adjust profiles for `app-misc/jq` and `net-misc/rsync`, to correctly build the corresponding [PR](https://github.com/flatcar-linux/portage-stable/pull/104).
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/104.
```
```
TBD
=> profile: adjust profiles for jq, rsync

profiles/coreos/base/make.defaults
We've created flatcar mirrors to stop depending on coreos mirrors. This change switches to those mirrors instead of the deprecated coreos ones.
I've verified that the SDK job picked up this change when building from this branch.
This will need to be cherry picked to all active branches.
Needed for: kinvolk/PROJECT-flatcar-linux#333
=> Switch to our new mirrors

coreos-base/coreos/coreos-0.0.1.ebuild
The build for arm64 currently fails because it tries to build the
oslogin package but the package is marked as amd64-only.
Exclude the oslogin package from arm64 images.
Build an arm64 image.
None yet
=> coreos-base/coreos: Build and install oslogin for amd64 only

app-arch/torcx/torcx-9999.ebuild
This pulls in
https://github.com/flatcar-linux/torcx/pull/4
to set a fixed tmpfs size.
**Note:** Pick for 2605 and 2632
[Passing](http://localhost:9091/job/os/job/toolchains/579/cldsv/)
=> app-arch/torcx: Point to latest flatcar-master

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.use
Now that we cleaned up packages `net-libs/serf` and `dev-libs/apr-util`, we should also remove them from profiles.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/106.
```
```
Jenkins Ci passed
=> profiles: adjust to clean up serf, apr-util

sys-kernel/coreos-sources/files/5.8/z0001-kbuild-derive-relative-path-for-srctree-from-CURDIR.patch
Update srctree path to correctly populate the Makefile for sandbox
environments. The patch is to adjusted for 5.x kernels
Sayan ran a Jenkins job with this change and after running that, the image generated has this file:
```
core@localhost ~ $ cat /usr/lib64/modules/5.8.10-flatcar/build/Makefile 
include ../source/Makefile
```
Which is correct as it no longer includes the sandbox environment.
This change needs to be cherry-picked to flatcar-2605 and flatcar-2632
=> Update srctree path to correctly populate Makefile

sys-apps/systemd/systemd-9999.ebuild
Since v242 remote-fs.target was not enabled by default, so mounting NFS shares did not happen after the update from 2512 (which has systemd 241). The ebuild was enabling remote-fs though, by putting a symlink in `/etc/systemd/system/…`. But this change in `/etc/ is apparently propagated during update, so remote-fs.target ended up being not a dependent target during boot. So the PR tries harder at not enabling services through /etc, but through /lib.
The image is building for me at the moment, but:
```
find /build/amd64-usr/usr/lib/systemd/ | grep 'remote-fs'
/build/amd64-usr/usr/lib/systemd/system/remote-fs.target
/build/amd64-usr/usr/lib/systemd/system/remote-fs-pre.target …
```
=> Enable remote-fs

profiles/coreos/base/package.use, sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
The savedconfig feature reads and, if not set, generates a file under
/etc/portage/savedconfig/ to source a build configuration. We probably
don't want this and specially not on the final image, therefore,
disable reading and also don't write the file to the final image.
**Note:** Pick for 2605, 2632, and 2643
Build an image and check if `/etc/portage` exists which it shouldn't.
Built an image and saw that the file is gone.
=> sys-kernel/coreos-firmware: Disable savedconfig flag and file creation

sys-kernel/coreos-sources/files/5.8/z0001-kbuild-derive-relative-path-for-srctree-from-CURDIR.patch
``` bash
./build_image container
```
@marga-kinvolk tested it, and I did a local compile, need to test on Jenkins
Related #614
=> Adjust the `srctree` based on the presence of KBUILD_OUTPUT

profiles/coreos/base/package.accept_keywords
The ebuild is in the portage-stable repository but we need this patch in
coreos-overlay to avoid this error:
```
> The following keyword changes are necessary to proceed:
>  (see "package.accept_keywords" in the portage(5) man page for more details)
> # required by sys-apps/systemd-245-r3::coreos[seccomp]
> # required by app-misc/ca-certificates-3.27.1-r1::coreos
> # required by dev-libs/openssl-1.1.1g::coreos
> # required by net-misc/rsync-3.2.3::portage-stable[-libressl,ssl,-static]
> # required by sys-apps/portage-2.3.40-r1::coreos[-build]
> # required by app-admin/perl-cleaner-2.27::portage-stable
> # required by dev-lang/perl-5.26.2::portage-stable
> # required by sys-apps/help2man-1.45.1::portage-stable
> # required by sys-devel/automake-1.16.1-r1::portage-stable
> # required by …
```
=> Update libseccomp to 2.5.0

coreos-base/oem-qemu/files/grub.cfg, coreos-base/oem-qemu/files/oem-release, coreos-base/oem-qemu/metadata.xml, coreos-base/oem-qemu/oem-qemu-0.0.1.ebuild
Fix flatcar-linux/Flatcar#71
```
emerge-amd64-usr oem-qemu
./build_image
./image_to_vm.sh --format=qemu
```
Built a local image, and created a QEMU image. Verified in `/usr/share/oem/{grub.cfg|oem-release}`
=> oem-qemu: Add OEM package for QEMU

sys-apps/baselayout/baselayout-9999.ebuild
Because the --root option restricts systemd-tmpfiles to the passwd
database file in the package chroot it can't resolve the core user
and fails to set up the home folder from the baselayout-home.conf
directives.
Create the folder manually because creating a /etc/passwd file in
the package chroot would at installation overwrite the SDK user.
Run toolchains or SDK builds on Jenkins.
With the `2020.10.12+dev-flatcar-master-1196` SDK I was able to start builds.
=> sys-apps/baselayout: Ensure to create core home folder in the SDK

sys-apps/systemd/systemd-9999.ebuild
This reverts commit c414b38c7c56dafb05a86040443c634763527f05.
The real DNS server IP addresses should be in /etc/resolve.conf and not
just 127.0.0.53 because all cases that bind-mount /etc/resolve.conf
into a new network namespace can't reach the loopback interface that
resolved is listening on.
None
=> Revert "sys-apps/systemd: Drop the resolv.conf workaround"

coreos-base/coreos-init/coreos-init-9999.ebuild, sys-apps/baselayout/baselayout-9999.ebuild
This pulls in
https://github.com/flatcar-linux/init/pull/28 and
https://github.com/flatcar-linux/baselayout/pull/7
to ensure that the /etc/coreos to /etc/flatcar symlink always exists.
Fixes https://github.com/flatcar-linux/Flatcar/issues/190
*Note:* This will be included in all maintenance branches. In case of Stable this pulls in two harmless additional changes that won't affect behavior:
https://github.com/flatcar-linux/baselayout/pull/6
https://github.com/flatcar-linux/init/pull/27
See https://github.com/flatcar-linux/baselayout/pull/7
Tested with the `main` branch.
=> sys-apps/baselayout, coreos-base/coreos-init: Point to lastest state

coreos-base/coreos/coreos-0.0.1.ebuild
The diffutils package provides the "cmp" and "diff" tools which are
essential commands in shell scripts. They used to be pulled in by
audit but the update in
https://github.com/flatcar-linux/coreos-overlay/pull/537
caused them to be dropped.
Add them to the explicit list of base packages to ensure they are
installed.
**Note:** Will be picked to `flatcar-2661`
The final image should have the `cmp` and `diff` commands (and friends like `diff3` or `sdiff`).
None
=> coreos-base/coreos: Add diffutils to the base packages

coreos-base/coreos-init/coreos-init-9999.ebuild, sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in https://github.com/flatcar-linux/bootengine/pull/19
and https://github.com/flatcar-linux/init/pull/29
to exclude the bonded interface from networkd in Azure.
**Note:** May have to be picked to all branches, but I didn't verify if the current Stable is affected. Thus, just including it in 2661 for now.
Boot a machine as see if the systemd-networkd-wait-online.service failed.
[Built an image](http://localhost:9091/job/os/job/manifest/1216/console), all [tests passing](http://localhost:9091/job/os/job/kola/job/azure/194/console)
=> coreos-base/coreos-init, sys-kernel/bootengine: Update to latest state

coreos-base/afterburn/afterburn-9999.ebuild
This pulls in
https://github.com/flatcar-linux/afterburn/pull/10
to fix systemd-networkd-wait-online on Equinix Metal (fka Packet).
**Note:** Include in `flatcar-2661`
Running the kola tests suite should not give errors like this anymore:
```
failed basic checks: some systemd units failed:\n● systemd-networkd-wait-online.service loaded failed
```
[Here](http://localhost:9091/job/os/job/manifest/1223/cldsv/), looks good for t1.small, c2.medium, and c3.medium, but on the c3.small networkd sometimes has the bond0 interface stuck in `configuring` even though it is `routable` already - this goes away when restarting networkd and it looks like it is not robust enough for a corner case. We should probably report this as upstream bug.
=> coreos-base/afterburn: Point to latest commit

profiles/coreos/base/package.use
To be able to update `dev-util/gdbus-codegen` to 2.64.5, we need to specify a single target python3.6 for gdbus-codegen.
Without it, it is not possible to emerge gdbus-codegen, because it thinks there are multiple python single targets for the package.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/118.
CI passed
=> profiles: gdbus-codegen only for python 3.6

.github/workflows/setup-flatcar-sdk.sh
The key server currently doesn't work. Since the key is not used
currently but the key we have hosted on our web server, we can remove
this failing step to restore GitHub Actions.
Rerun GitHub Actions
Ran the commands to verify the cork binary.
=> .github: Remove fetching unused key from gpg server

coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild, coreos-base/coreos-init/coreos-init-9999.ebuild
Pulls in
https://github.com/flatcar-linux/coreos-cloudinit/pull/10
https://github.com/flatcar-linux/init/pull/30
to restore the systemd-networkd 243 behavior with
KeepConfiguration=dhcp-on-stop to prevent the network from going down
before the SIGTERM is broadcasted to orphaned processes not part of a
systemd unit.
**Note:** Should be merged for all maintenance branches (for Stable this also pulls in https://github.com/flatcar-linux/init/pull/29 which is good to have the unmanaged interface not shown as _configuring_ in `networkctl`)
See linked PRs
Ran kola tests on all platforms.
=> coreos-base/coreos-(cloud)init: Point to flatcar-master

profiles/coreos/targets/sdk/package.use
In the past we [enabled](https://github.com/flatcar-linux/coreos-overlay/commit/172d9311bacd) the USE flag `gssapi` only for amd64, not for arm64.
We did so to avoid build issues that only happened for arm64.
However, that change caused interesting side effects in the SDK, where bind-tools ended up being compiled without `gssapi`.
It means, tools like `nsupdate` in the SDK are not able to deal with certain commands like `realm`.
As a result, configure scripts in packages like `sys-auth/sssd` fail, because they cannot run commands like `echo realm | nsupdate`.
We should bring the `gssapi` USE flag back to the SDK, to avoid such issues in the future.
```
emerge bind-tools
```
local build
=> profiles: enable gssapi for bind-tools in SDK

.github/workflows/setup-flatcar-sdk.sh
The repo `github.com/flatcar-linux/mantle` has been moved to `github.com/kinvolk/mantle`.
However, Github Actions still fetch cork binaries from the original URL, by running `curl` without `-L`.
So the request does not get redirected to the new URL.
As a result, `CORK_VERSION` becomes null.
Fix it by replacing `flatcar-linux` with `kinvolk`, as well as adding `-L` to the curl command, just in case.
=> .github: fix mantle URL for downloading cork

app-crypt/trousers/files/trousers-0.3.14-CVE-2020-24330_CVE-2020-24331_CVE-2020-24332.patch, app-crypt/trousers/trousers-0.3.14-r2.ebuild
Add a [seclists patch](https://seclists.org/oss-sec/2020/q2/att-135/tcsd_fixes.patch) to `app-crypt/trousers-0.3.14-r2`.
```
emerge-amd64-usr trousers
```
=> trousers: add patch to fix CVE issues

eclass/coreos-go-utils.eclass
We need to filter not only `-Wl,-O1`, but also other flags like `-Wl,-O2`, `-Wl,-Og`, `-Wl,-Os`, etc.
Otherwise, SDK build would fail, for example, as its default `$LDFLAGS` includes `-Wl,-O2`.
We need to manually strip only the optimization element of comma-separated flags, e.g. from `-Wl,-O1,-s` to `-Wl,-s`.
To support multiple characters that can follow `-O`, e.g. `-Ofast`, we should use regexp like `[[:alnum:]]*`.
```
sudo emerge dev-lang/go:1.15
sudo FORCE_STAGES="stage4" ./bootstrap_sdk
```
SDK build passed in CI.
=> eclass: remove also other optimization flags with -Wl,-O*

sys-apps/systemd/systemd-9999.ebuild
This pulls in
https://github.com/kinvolk/systemd/pull/4
from the new repository, thus it only works with the new manifest
templates.
Run the kola test suite.
Running http://localhost:9091/job/os/job/manifest/1466/cldsv/
=> sys-apps/systemd: Update to the 245.8 stable point release

coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild, profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.use
To build Kernel with `CONFIG_DEBUG_INFO_BTF`, we need to make `pahole` in dwarves included in the Flatcar SDK.
To do that, we need to make it accept `~amd64` keywords for dwarves and binutils.
Also enable USE flag `python_single_target_python3_6` for dwarves.
See also https://github.com/kinvolk/Flatcar/issues/225 .
This PR should be merged together with https://github.com/kinvolk/portage-stable/pull/126.
```
sudo emerge dev-util/dwarves
```
CI passed http://localhost:9091/job/os/job/manifest/1484/cldsv/
=> profiles: make SDK include dev-util/dwarves

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/kinvolk/init/pull/31
to make extend-filesystems more robust against a race.
Kola tests passed [here](http://localhost:9091/job/os/job/manifest/1478/cldsv)
=> coreos-base/coreos-init: Update to latest repository state

sys-apps/systemd/systemd-9999.ebuild
Point to the latest commit in the v245 branch.
Refer to kinvolk/systemd#5 and https://github.com/kinvolk/systemd/commit/29cb7c447e3544e74b45b067909019893a5132d2
=> sys-apps/systemd: Point to the latest commit

sys-apps/baselayout/baselayout-9999.ebuild
This pulls in
https://github.com/kinvolk/baselayout/pull/8
to add tmpfile directives for for /opt and /opt/bin
Note: Will be picked for 2605, 2643, 2697
=> sys-apps/baselayout: Point to latest repo state

coreos-base/oem-azure-pro/files/base/README, coreos-base/oem-azure-pro/files/base/base.ign, coreos-base/oem-azure-pro/files/base/default.ign, coreos-base/oem-azure-pro/files/grub.cfg, coreos-base/oem-azure-pro/files/oem-release, coreos-base/oem-azure-pro/files/units/waagent.service, coreos-base/oem-azure-pro/metadata.xml, coreos-base/oem-azure-pro/oem-azure-pro-2.2.46.ebuild, coreos-devel/board-packages/board-packages-0.0.1.ebuild, x11-drivers/nvidia-drivers/files/bin/install-nvidia, x11-drivers/nvidia-drivers/files/bin/setup-nvidia, x11-drivers/nvidia-drivers/files/units/nvidia.service, x11-drivers/nvidia-drivers/nvidia-drivers-450.80.02.ebuild
This adds the support of GPU on Azure. This adds a new OEM `oem-azure-pro` which is essentially a superset of the `oem-azure`. The implementation is duplicated but later can be refactored to remove the duplication. This also adds the `nvidia-driver` ebuilds to install the NVIDIA during the boot process. 
```
./build_image
./image_to_vm --format=azure_pro
```
Boot and check the output of the command of `nvidia-smi`
Few bits are added are not tested. Also, The tests are done on the stable rebase, and not on the main. This PR needs to be picked to beta. 
To be merged with kinvolk/flatcar-scripts#103
Jenkins build http://localhost:9091/job/os/job/board/job/packages-matrix/2038/cldsv/ 
image-matrix rebuild …
=> Add the support for GPU on Azure

x11-drivers/nvidia-drivers/files/bin/setup-nvidia
The kola tests fails to download during the release because the
artifacts of the release has not been pushed to the website yet.
This adds the logic to check if the URL is 200, then only download
or else fallback to the GCS bucket url.
This commit also changes a bug with the check to see if nvidia
is installed or required.
```
./build_image
./image_to_vm --format=azure_pro
```
Boot and check the output of the command of `nvidia-smi`
Tested the script on an Azure box both with GPU and without.
Image matrix rebuild: http://localhost:9091/job/os/job/board/job/image-matrix/1641/ 
Note: this needs to be picked to `flatcar-2643` branch
=> x11-drivers/nvidia-drivers: Fix the dev container download URL

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/kinvolk/init/pull/32
to change the LTS motd information.
=> coreos-base/coreos-init: Point to latest repo state

.github/workflows/containerd-releases-main.yml, .github/workflows/docker-releases-main.yml, .github/workflows/go-releases-main.yml, .github/workflows/kernel-releases-alpha.yml, .github/workflows/kernel-releases-beta.yml, .github/workflows/kernel-releases-main.yml, .github/workflows/kernel-releases-stable.yml, .github/workflows/runc-releases-main.yml, .github/workflows/rust-release-main.yml
Github Actions for Rust started failing with following errors:
```
Error: Unable to process command '::set-env name=PULL_REQUEST_NUMBER::718' successfully.
Error: The `set-env` command is disabled. Please upgrade to using
Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`.
For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
It happens because we have used `peter-evans/create-pull-request@v2`, which did not have a bug fix for the set-env issue.
The bug was fixed in create-pull-request [v3.4.1](https://github.com/peter-evans/create-pull-request/releases/tag/v3.4.1).
So we just need to update the version to `v3`, which already …
=> .github: use create-pull-request@v3 to fix set-env issues

coreos-base/update_engine/update_engine-9999.ebuild
This pulls in
https://github.com/kinvolk/update_engine/pull/8
to support sending a machine alias to the update server.
=> coreos-base/update_engine: Point to latest repo state

app-editors/vim/vim-8.2.0360-r1.ebuild
A symlink `vimdiff` should not be created, if the USE flag `minimal` is enabled.
Otherwise running `vimdiff` results in failure like that:
```
$ vimdiff aaa bbb
This Vim was not compiled with the diff feature.
```
See also https://github.com/gentoo/gentoo/pull/18496.
Fixes https://github.com/kinvolk/Flatcar/issues/221.
```
emerge-amd64-usr app-editors/vim
```
=> app-editors/vim: do not create symlink vimdiff for minimal

profiles/coreos/base/package.use, profiles/coreos/targets/sdk/package.use
Qemu has enabled `jpeg` USE flag since the beginning, without any reason specified.
As a result, qemu pulls in unnecessary packages, `virtual/jpeg` as well as `media-libs/libjpeg-turbo`.
However, Flatcar runs qemu always with `-display none` option.
So the `jpeg` flag is not needed at all.
Simply remove `jpeg` USE flag from qemu.
This PR should be merged together with https://github.com/kinvolk/portage-stable/pull/133.
```
sudo FORCE_STAGES="stage4" bootstrap_sdk
```
SDK build passed. http://localhost:9091/job/os/job/manifest/1594/cldsv/
=> profiles: disable jpeg for qemu

.github/workflows/firmware-apply-patch.sh, .github/workflows/firmware-releases-main.yml
Add Github Actions for coreos-firmware, just like other Kernel packages, basically to detect new releases from the upstream [linux-firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git) repo.
Fixes https://github.com/kinvolk/Flatcar/issues/289.
=> .github: add Github Actions for auto-updating linux-firmware

app-emulation/containerd/files/config.toml
Kubernetes uses containerd through the cri plugin which currently is
disabled due to it listening on a TCP port. Now the plugin is not
listening on a TCP port anymore but uses the same socket as gRPC.
We have documented how to enable it in
https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/switching-from-docker-to-containerd-for-kubernetes/
but it should work by default.
Fixes https://github.com/kinvolk/Flatcar/issues/283
Note: Picked for Stable and Beta
The kubelet still needs to know the special socket location but otherwise no customizations should be needed to us containerd.
```
--container-runtime-endpoint=unix:///run/docker/libcontainerd/docker-containerd.sock
``` 
The change is the same as in https://kinvolk.io/docs/flatcar-container-linux/latest/container-run …
=> app-emulation/containerd: Enable the CRI plugin

sys-apps/baselayout/baselayout-9999.ebuild
This pulls in
https://github.com/kinvolk/baselayout/pull/13
to set sysctl rp_filter=0 and reorder how the configs are applied.
A branch flatcar-2605-2705 is used as maintenance branch.
Note: Should be picked for 2605 and 2705
=> sys-apps/baselayout: Point to flatcar-2605-2705 branch

sys-apps/systemd/systemd-9999.ebuild
...for applications that do not do nsswitch (https://github.com/kinvolk/baselayout/pull/10)
REQUIRES https://github.com/kinvolk/baselayout/pull/11
Goes in tandem with https://github.com/kinvolk/baselayout/pull/10
Set up Split-Horizon DNS as outlined in https://github.com/kinvolk/baselayout/pull/10 
Same tests as https://github.com/kinvolk/baselayout/pull/10 but with `dig` instead of ping to bypass nsswitch
Related: https://github.com/kinvolk/Flatcar/issues/285
=> Update systemd-9999.ebuild to use systemd-resolved's stub resolver

app-emulation/containerd/files/config.toml
Debug output clutters the logs which with K8s liveness/readiness probes
quickly becomes a problem.
Fixes https://github.com/kinvolk/Flatcar/issues/313
Run a cluster with liveness/readiness probes and see that the log output is reduced because it does not contain `level=debug` entries anymore.
None
=> app-emulation/containerd: Disable shim debug logs

coreos-base/afterburn/files/coreos-metadata-sshkeys@.service, coreos-base/afterburn/files/coreos-metadata.service
When the metadata server is unavailable for some time the service did
not retry. Also, the service was triggered possibly multiple times
each time another service pulled it in which can cause problems if,
e.g., the service experiences a failure and corrupts the existing file
which could have been kept because rerunning wasn't needed.
Fixes https://github.com/kinvolk/Flatcar/issues/311
Build and verify that all tests pass
None
=> coreos-base/afterburn: Restart on failure and keep unit active

sys-apps/systemd/systemd-9999.ebuild
Using only 127.0.0.53 for /etc/resolv.conf causes problems for
Kubernetes which is not systemd-resolved aware yet (the kubelet passes
on /etc/resolv.conf contents to containers).
Switch back for now to merging all DNS servers into /etc/resolv.conf
which breaks split DNS and we need to document how to make split DNS
work for those that want it.
(Reverts the change of https://github.com/flatcar-linux/coreos-overlay/pull/730)
Needs a docs PR and a kubelet upstream issue would also be nice
=> sys-apps/systemd: Switch back to using a merged /etc/resolv.conf

app-emulation/containerd/files/config.toml, app-emulation/containerd/files/containerd-1.0.0.service
The upstream socket is under /run/containerd/containerd.sock which many
tools like crictl will use by default and diverging causes users to
always have to configure a non-default location.
Switch to the upstream default while still keeping a symlink so that
users are not forced to update their configurations they had to do for
the non-default location. This also keeps Docker using the old socket
location as an assertion that the symlink works. The state directory
is also switch to the default location.
Build an image and run the tests
Manually created a drop-in config with the new contents.
=> app-emulation/containerd: Switch to default socket location

.github/workflows/containerd-apply-patch.sh, .github/workflows/containerd-releases-main.yml, .github/workflows/docker-releases-main.yml, .github/workflows/go-releases-main.yml, .github/workflows/kernel-apply-patch.sh, .github/workflows/kernel-releases-alpha.yml, .github/workflows/kernel-releases-beta.yml, .github/workflows/kernel-releases-main.yml, .github/workflows/kernel-releases-stable.yml, .github/workflows/runc-apply-patch.sh, .github/workflows/runc-releases-main.yml, .github/workflows/rust-apply-patch.sh, .github/workflows/rust-release-main.yml
1. pass env variables explicitly as string
Since Kernel 5.10, Github Actions simply stopped working.
What happens is that `KV_MAIN` gets passed as environmental variable to the inline script, but not as string but float, because it contains `.`.
Apparently the last digit of the misinterpreted float number is afterwards simply dropped by YAML parsing library used by GA.
As a result, `KV_MAIN` becomes `5.1` instead of `5.10`, `versionMain` becomes simply `5.10`, not `5.10.6`.
Then in the next steps, both `VERSION_NEW` and `VERSION_OLD` become `5.10`, and the script thinks it is already the latest version, so simply does not create a new pull request.
Simply set `KV_MAIN` or others explicitly as strings, by adding quotes, to avoid such issues.
2. Sscape dot correctly in sed expressions
So …
=> .github: fix env vars and sed expressions

dev-util/bsdiff/bsdiff-4.3-r8.ebuild, dev-util/bsdiff/files/bsdiff-4.3-CVE-2020-14315.patch
Fix a heap overflow vulnerability in bspatch included in bsdiff.
Originally the security issue was published as [FreeBSD-SA-16:29](https://www.freebsd.org/security/advisories/FreeBSD-SA-16:29.bspatch.asc), which pointed to a FreeBSD [patch](https://security.freebsd.org/patches/SA-16:29/bspatch.patch).
However, the patch was a set of huge changes including other unrelated changes.
That's why it was not simple at all to apply the patch to bsdiff.
Both Gentoo and Flatcar have not included the fix.
Fortunately X41 D-SEC [examined](https://www.x41-dsec.de/security/news/working/research/2020/07/15/bspatch/) the issue again, and nailed down to a simple patch that can be easily applied to other trees.
We simply take the patch with minimal changes.
See also …
=> dev-util/bsdiff: fix heap overflow vulnerability CVE-2020-14315

dev-lang/rust/files/1.49.0-gentoo-musl-target-specs.patch
The target has undergone signficant refactoring. It's no longer a
TargetResult, it's just a Target. And also the vendor is now part of the
options.
Did a toolchains+packages run on Jenkins, it passed.
=> dev-lang/rust: Move TargetResult to Target in our local patch

dev-lang/rust/rust-1.49.0.ebuild
I renamed the file in the previous commit (after running the CI), and forgot I needed to also rename it in the list of patches :-/
=> dev-lang/rust: Fix patch name

dev-libs/openssl/openssl-1.1.1g.ebuild
It's really a hindrance during bootstrap, and we would be looking into
ways of making an exception for openssl anyway. Using
package.accept_restrict file does not do the trick, apparently because
of catalyst using its own portage config.
This came up during building SDK stage1 with new portage. The error was like:
```
!!! All ebuilds that could satisfy "dev-libs/openssl:0=" for /tmp/stage1root/ have been masked.
!!! One of the following masked packages is required to complete your request:
- dev-libs/openssl-1.1.1g::coreos (masked by: bindist in RESTRICT)
```
It either stopped being racy with new portage or was simply quite much more likely to be triggered. With restriction removed, the build went further.
On a second thought, this restrict didn't make sense to me, because the logic …
=> dev-libs/openssl: Drop bindist from RESTRICT variable

profiles/coreos/base/package.use
When building `net-libs/nghttp2` needed by curl 7.74, build fails when checking for prerequisites of boost libs.
```
configure:20402: checking whether the Boost::ASIO library is available
configure:20433: x86_64-cros-linux-gnu-g++ -std=c++14 -c -O2 -pipe -mtune=generic -g   conftest.cpp >&5
configure:20433: $? = 0
configure:20447: result: yes
configure:20540: error: Could not find a version of the library!
```
To avoid such issues, we should disable the `cxx` USE flag for `net-libs/nghttp2`.
This PR should be merged together with https://github.com/kinvolk/portage-stable/pull/137.
```
emerge-amd64-usr net-misc/curl
```
CI passed http://localhost:9091/job/os/job/manifest/1816/cldsv/
=> profiles: disable cxx for net-libs/nghttp2

app-emulation/open-vmdk/open-vmdk-1.0.ebuild
Replace the use of deprecated git eclass with git-r3 and bump the
commit version to latest version. This version dropped a dependency on
jq.
It is a breaking change for users of mkova.sh, since it has changed
the order of parameters to allow passing multiple vmdk files to it.
I have made this commit for the portage update and it has pushed the build further.
I haven't found any use of the `mkova.sh` script in jenkins or build scripts. I haven't found any use of `vmdk-converter` anywhere either, so not sure why this package needs to be a part of SDK. But this is something to investigate later.
Test build: http://localhost:9091/job/os/job/manifest/1831/cldsv/
=> app-emulation/open-vmdk: Update

sys-apps/systemd/files/0007-core-use-max-for-DefaultTasksMax.patch
Updated the patch to remove some more uneccesary text related to DefaultTasksMax
```bash
emerge-amd64-usr sys-apps/systemd
./build_image
```
[Jenkins](http://localhost:9091/job/os/job/manifest/1855/cldsv/) build is running.
=> sys-apps/systemd: Fix the DefaultTasksMax patch to default to 100%

coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild, profiles/coreos/base/package.accept_keywords
It's unused. Used to be a dependency of ureadahead and upstart, which got dropped long time ago. I noticed it during updating portage by updating profiles, since gentoo is about to drop the library too and masked it.
To be merged together with https://github.com/kinvolk/portage-stable/pull/139.
Test build succeeded: http://localhost:9091/job/os/job/manifest/1860/cldsv/
=> Drop libnih

coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild, profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.use, profiles/coreos/targets/generic/package.use
As `dev-libs/nss` is not used anywhere, let's simply remove nss.
The only ebuild that pulls in is `net-misc/curl`, but only if the USE flag `nss` is enabled.
As the `nss` flag is disabled for curl, we do not need to keep `dev-libs/nss` at all.
According to the change, delete `dev-libs/nss` from profiles and sdk-depends.
This PR should be merged together with https://github.com/kinvolk/portage-stable/pull/141 .
```
./bootstrap_sdk
...
```
CI passed http://localhost:9091/job/os/job/manifest/1877/cldsv/
=> coreos-base,profiles: delete nss

app-admin/sudo/sudo-1.9.5_p2.ebuild
This Flatcar specific change to the sudo ebuild was missed when updating to sudo-1.9.5p2.
Unmerged perl, emerged sudo, and sudo chrooted into the cross root to run sudo there, validating it runs w/o perl.
```
$ emerge-amd64-usr --unmerge perl
$ emerge-amd64-usr sudo
$ sudo chroot /build/amd64-usr/ sudo ls
bin  boot  build  dev  etc  home  lib  lib64  media  mnt  opt  packages  proc  root  run  sbin  sys  tmp  usr  var
```
Cherry pick to 2605, 2705, 2765.
=> app-admin/sudo: remove perl dependency

sys-apps/baselayout/baselayout-9999.ebuild
This pulls in
https://github.com/kinvolk/baselayout/pull/16
to fix parsing of failed units shown as motd.
=> sys-apps/baselayout: fix failed unit parsing

sys-apps/baselayout/baselayout-9999.ebuild
This pulls in
https://github.com/kinvolk/baselayout/pull/16
to fix parsing of failed units shown as motd.
Same as https://github.com/kinvolk/coreos-overlay/pull/814 but using the baselayout branch for 2605.
=> sys-apps/baselayout: fix failed unit parsing for flatcar-2605 branch

app-crypt/trousers/files/tmpfiles.d/trousers.conf, app-crypt/trousers/trousers-0.3.14-r2.ebuild
The security patch that was brought in has stricter permission checks
which cause the service to fail:
ERROR: TCSD config file (/etc/tcsd.conf) must be user/group root/tss
Set the expected file ownership and permissions.
https://github.com/kinvolk/Flatcar/issues/335
**Note:** will be picked for all channels
I ran this [build](http://localhost:9091/job/os/job/manifest/1916/) and saw that the service is running successfully:
```
$ systemctl status tcsd
● tcsd.service - TCG Core Services Daemon
Loaded: loaded (/usr/lib/systemd/system/tcsd.service; disabled; vendor preset: disabled)
Active: active (running) since Fri 2021-01-29 18:16:47 UTC; 1min 59s ago
Main PID: 1027 (tcsd)
Tasks: 1 (limit: 38274)
Memory: 760.0K
CGroup: /system.slice/tcsd.service
└─1027 /usr/sbin/tcsd -f
Jan 29 18:16:47 …
```
=> app-crypt/trousers: use correct file permissions

sys-apps/systemd/systemd-9999.ebuild
The systemd.eclass was not finding the systemd pkg-config file to
figure out the system unit directory, so it was falling back to a
hardcoded default (`/lib/systemd/system`). In one case (when
overriding the `default.target` symlink), we tried to fix that by
specifying the `PKG_CONFIG_LIBDIR` environment variable, but that
still did not help.
Using functions from `systemd.eclass` in a systemd ebuild is working
only by chance here. This eclass is usually meant for ebuilds that
depend on systemd and rely on systemd being already installed in the
root filesystem.
The functions in `systemd.eclass` that need to figure out some values
from systemd's pkg-config file (like system unit directory) assume
that systemd is already installed in the root filesystem, which is not
the case when we …
=> sys-apps/systemd: Fix unit installation

sys-apps/baselayout/baselayout-9999.ebuild
This pulls in
https://github.com/kinvolk/baselayout/pull/15
=> sys-apps/baselayout: use correct GID for tss in /etc/passwd

coreos-base/flatcar-eks/files/bootstrap.patch, coreos-base/flatcar-eks/files/bootstrap.sh, coreos-base/flatcar-eks/files/eni-max-pods.txt
The bootstrapping script relies on `/etc/docker` existing, but this
directory doesn't exist on vanilla Flatcar. Add the missing call to
`mkdir -p /etc/docker` before the directory gets used.
Also, update the upstream files to their latest version.
=> flatcar-eks: add missing mkdir and update to latest versions

coreos-base/coreos-init/coreos-init-9999.ebuild, coreos-base/oem-azure-pro/files/oem-release, coreos-base/oem-ec2-compat/oem-ec2-compat-0.1.2.ebuild
- coreos-base/coreos-init: Show OEM in motd
This pulls in https://github.com/kinvolk/init/pull/34
- coreos-base/oem-*: add Pro to OEM name where applicable 
Using the change in https://github.com/kinvolk/init/pull/34
we can show the OEM on the motd, and by including "Pro" in the OEM
name we can also show whether it is a Pro image or not. Later this
may be revisited if the /usr/../os-release file is the place for it.
Build an OEM image and see the motd after login
None
=> coreos-base/coreos-init: Show OEM in motd

coreos-base/coreos/coreos-0.0.1.ebuild
x11-drivers/nvidia-drivers are installed only on amd64 arch, so
install x11-drivers/nvidia-metadata also only on amd64.
Test build: http://localhost:9091/job/os/job/manifest/1964/
=> coreos-base/coreos: Move nvidia-metadata to amd64-only RDEPENDS

sys-block/open-iscsi/files/iscsi-init.service
https://github.com/kinvolk/coreos-overlay/pull/791/files#r563735720
```
emerge-amd64-usr open-iscsi
```
Done locally, need to schedule a Jenkins build
=> sys-block/open-iscsi: Command substition in iscsi-init system service

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/kinvolk/init/pull/35
to add parameters for wget in bin/flatcar-install.
=> coreos-base/coreos-init: make wget more resilient in flatcar-install

sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/kinvolk/bootengine/pull/21
=> sys-kernel/bootengine: set hostname for EC2 and OpenStack from metadata

sys-kernel/dracut/dracut-044-r1.ebuild, sys-kernel/dracut/dracut-044-r3.ebuild, sys-kernel/dracut/dracut-045-r2.ebuild, sys-kernel/dracut/dracut-046-r1.ebuild, sys-kernel/dracut/dracut-047-r1.ebuild, sys-kernel/dracut/dracut-048-r1.ebuild, sys-kernel/dracut/dracut-048.ebuild
The kernel mirror was dropped from the thirdpartymirrors file in
profiles, so it's use needs to be replaced with an address to
kernel.org.
It's a quick hack to fix the issue without spending too much time on updating every single package. The change in SRC_URIs were done with `sed -i'' -e 's!mirror://kernel!https://www.kernel.org/pub!g' $(git grep 'mirror://kernel' | cut -f1 -d: | grep -e '\.\(eclass\|ebuild\)$' | sort -u)`.
Needs to be merged together with https://github.com/kinvolk/portage-stable/pull/148.
Test build: http://localhost:9091/job/os/job/manifest/2062/
=> sys-kernel/dracut: Drop the use of mirror://kernel

net-fs/samba/metadata.xml, net-fs/samba/samba-4.12.9-r2.ebuild, profiles/coreos/base/package.use
Now that portage was updated to the latest version, we should update `EAPI` to 7.
It is mainly to allow ebuilds to make `BDEPEND` contain real build-time dependencies, not runtime ones.
Introduce a USE flag `spotlight`, to be able to disable the spotlight backend by default, as it is not needed by Linux.
Introduce a USE flag `rededit`, to be able to disable the rededit tool if needed.
Introduce a USE flag `glusterfs`, to be able to disable the glusterfs by default.
Introduce a USE flag `ntvfs`, to be able to disable the ntvfs-fileserver by default.
Since the `docbook-xsl-stylesheets` and `libxslt` are needed only at build time, we should move those deps to `BDEPEND`.
`dev-libs/icu` is needed only if spotlight is enabled. If not enabled, we should not pull in icu.
To minimize the size of …
=> net-fs/samba: EAPI=7, new USE flags, remove deps on icu

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
This commit also removes some redundant accept_keywords
Tested local and Jenkins Build http://localhost:9091/job/os/job/manifest/2115/
To be merged with kinvolk/portage-stable#151
=> profiles: Add multipath-tools to ACCEPT_KEYWORDS

coreos-base/coreos-init/coreos-init-9999.ebuild
This change updates coreos-init to a version which includes
a new SSHD config to limit crypto to "known secure" algorithms only.
See https://github.com/kinvolk/init/pull/36 for details.
**Note** that I'll update this PR to point to the merge commit of the [source PR](https://github.com/kinvolk/init/pull/36) when that one gets merged. Bringing up this PR early so it can be reviewed in parallel to the source PR.
```
$ emerge-amd64-usr coreos-init
$ ./build_image --board=amd64-usr
$ ./image_to_vm.sh ...
```
Started QEmu image, SSH'd into image, then
```
core@localhost ~ $ sudo cat /etc/ssh/sshd_config 
Subsystem sftp internal-sftp
ClientAliveInterval 180
UseDNS no
UsePAM yes
PrintLastLog no # handled by PAM
PrintMotd no # handled by PAM
Ciphers …
```
=> coreos-base/coreos-init: SSHD: use secure crypto algos only

.github/workflows/kernel-releases-lts-2021.yml
The kernel version and maintenance branch stays the same for an LTS
stream. Since streams coexist for some time, they need their own GitHub
Actions.
None
=> .github: automate kernel updates

app-admin/sdnotify-proxy/sdnotify-proxy-9999.ebuild
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
Background for this is that i've deleted our https://github.com/kinvolk/sdnotify-proxy and properly forked from coreos/sdnotify-proxy
=> sdnotify: avoid the github redirect

app-admin/sdnotify-proxy/sdnotify-proxy-9999.ebuild
In https://github.com/kinvolk/coreos-overlay/pull/875 the repository
was switched to a fork from the archived upstream repository. However,
the ebuild was still using a reference to an old squashed Flatcar build
bot commit from the git-sync times that was only present in our old
repository.
Switch to a reference to the latest commit on the new repository which
in fact does not introduce any changes.
To be picked for all active branches
=> app-admin/sdnotify-proxy: use git ref of new repository

sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
When listing kernel modules to decide which firmware should be shipped
together with the image, we need to now list both compressed and
uncompressed module.
Fixes: kinvolk/Flatcar#359
CI currently running
=> sys-kernel/coreos-firmware: include firmware for compressed kernel modules

app-emulation/containerd/files/containerd-1.0.0.service, coreos-base/afterburn/files/coreos-metadata.service
While the execution of the unit may succeed by finding the executables
by searching the current PATH, calling `systemd-analyze verify` on the
units fails because this requires an absolute path.
Fixes: kinvolk/Flatcar#360
CI currently running
=> Add explicit paths to coreos-metadata and containerd executables in their unit files

app-emulation/containerd/files/containerd-1.0.0.service
This unit is post-processed for torcx purposes and adding absolute paths breaks execution.
Needs to be cherry picked to flatcar-2765 and flatcar-2801
=> Revert adding explicit path to the containerd unit

dev-util/catalyst/catalyst-3.0.14-r1.ebuild, dev-util/catalyst/files/0005-chroot-funcs-use-python3-for-debug-output.patch, profiles/coreos/amd64/sdk/make.defaults
This change adds the USE flag cros_host to the
SDK's make.default, as part of a larger fix for the SDK bootstrap build.
The SDK bootstrap build was broken in stage 1 since package upgrades
were allowed to leak into that phase.
We now limit stage 1 to only "known good" package ebuilds, which caused
downstream breakage from missing flags in the stage 2 SDK bootstrapping.
This change fixes that breakage.
This change further contains a patch for catalyst to explicitly call python3 in 
chroot-functions.sh for portage related debug output.
Needed in combination with
* portage-stable: https://github.com/kinvolk/portage-stable/pull/152
* flatcar-scripts: https://github.com/kinvolk/flatcar-scripts/pull/123 (the main PR)
```
$ cork enter
$ sudo ./bootstrap_sdk
```
SDK CI build (manifest #2158) …
=> fix sdk bootstrap: use python3 in catalyst chroot-functions, set cros_host USE when bootstrapping

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/kinvolk/init/pull/38
to set predictable network interface names as alternative interface
names for virtio devices, and also add a special hardcoded ens4v1
name for GCE because the special udev rule to rename the device
stopped working after the systemd 247 update.
Note: Backport to 2765 when merging (may need a flatcar-2765 branch in `init`)
See https://github.com/kinvolk/init/pull/38
=> coreos-base/coreos-init: use alternative interface names for virtio

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/kinvolk/init/pull/38
to set predictable network interface names as alternative interface
names for virtio devices, and also add a special hardcoded ens4v1
name for GCE because the special udev rule to rename the device
stopped working after the systemd 247 update.
A branch flatcar-2765 was created in the init repository to backport
only this change.
See https://github.com/kinvolk/coreos-overlay/pull/899
=> coreos-base/coreos-init: use alternative interface names for virtio (flatcar-2765)

app-admin/etcd-wrapper/etcd-wrapper-3.3.25.ebuild, app-admin/etcd-wrapper/files/etcd-member.service, app-admin/etcd-wrapper/files/etcd-wrapper, app-admin/flannel-wrapper/files/flannel-docker-opts.service, app-admin/flannel-wrapper/files/flannel-wrapper, app-admin/flannel-wrapper/files/flanneld.service, app-admin/flannel-wrapper/flannel-wrapper-0.12.0.ebuild
As rkt is deprecated we need to run the Etcd and Flannel container with Docker
or Podman. The etcd/flannel-wrapper script is based on rkt arguments and
can't be used in a compatible way but we cannot remove it since ct
explicitly uses it in the ExecStart directive when writing out a
drop-in file once flannel settings are given in a Container Linux
Config.
A better way to run the Flannel/etcd container image is Podman because
Flannel depends on etcd but wants to be run before Docker so that it
can set up the Docker networking. Etcd and Flannel are part of the
Container Linux Config specification and thus can't be removed easily.
For now we have to resort to running these services with Docker and try
to restart Docker for the Flannel options to take effect (but that also
terminates the etcd …
=> app-admin/etcd-wrapper: use docker for the etcd service and drop etcd-wrapper

sys-apps/baselayout/baselayout-9999.ebuild
This pulls in
https://github.com/kinvolk/baselayout/pull/17
to enable the pam_faillock module as replacement for pam_tally2.
The "faillock" binary can be used to see the login attempts and
account lock status which before was available with the pam_tally
command. While the tally defaults did not temporarily lock the
account on wrong password login attempts, this is done by default
with faillock. However, the default behavior was relaxed to allow
more wrong attempts and have a shorter lock time span.
=> sys-apps/baselayout: enable pam_faillock with relaxed defaults

profiles/coreos/base/package.accept_keywords
To be merged along with https://github.com/kinvolk/portage-stable/pull/157
```bash
emerge-amd64-usr app-arch/zstd
```
Locally tested. Jenkins Build passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2284/
=> app-arch/zstd: Add app-arch/zstd to ACCEPT_KEYWORDS

dev-libs/openssl/files/openssl-1.1.1k-ca-certificate-check-bypass-fix.patch, dev-libs/openssl/files/openssl-1.1.1k-release-changes.patch, dev-libs/openssl/files/openssl-1.1.1k-teach-tlsproxy-encrypt-etm-records.patch, dev-libs/openssl/openssl-1.1.1k.ebuild, profiles/coreos/base/package.unmask
```bash
emerge-amd64-usr openssl
```
Locally Tested and Jenkins build passed.
=> dev-libs/openssl: Add the patch for openssl-1.1.1k release

sys-kernel/bootengine/bootengine-9999.ebuild
This change pulls in the latest bootengine version, that enables ISCSI
support in dracut and avoids tearing down the network when using netroot
See https://github.com/kinvolk/bootengine/pull/22 for more information.
This was already tested and it worked fine, this is just the PR for pulling in the change to coreos-overlay.
=> sys-kernel/bootengine: Enable iSCSI netroot devices on Flatcar

app-admin/updateservicectl/updateservicectl-9999.ebuild, app-emulation/acbuild/acbuild-9999.ebuild, app-emulation/cri-tools/cri-tools-1.19.0.ebuild, eclass/coreos-go-depend.eclass, eclass/coreos-go.eclass
Set the default Go version to 1.16 in coreos-go eclass files, to make ebuilds work with Go 1.16 by default.
Simply remove `COREOS_GO_VERSION` from the ebuild of `app-emulation/cri-tools`, as cri-tools does not belong to special cases of Go versions like Docker.
Set `COREOS_GO111MODULE` to `off` in `app-emulation/acbuild` and `app-admin/updateservicectl` to fix build failures. These packages do not support Go module, because of their old source code.
```
./boostrap_sdk
```
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2464/cldsv/
=> Set the default Go version to 1.16

profiles/coreos/base/package.accept_keywords
To be able to build gnutls 3.7.1, which is still not stable, we need to accept keywords `~amd64` and `~arm64`.
This PR should be merged together with https://github.com/kinvolk/portage-stable/pull/164 .
```
emerge-amd64-usr net-libs/gnutls
```
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2465/cldsv/
=> profiles: accept keywords for net-libs/gnutls

sys-kernel/bootengine/bootengine-9999.ebuild
Having the hostname units as required by the initrd.target meant that if
the unit failed (for example because the network was or the metadata
service were down), the machine wouldn't start. By making it a "wants"
rather than a "requires" we allow this unit to fail without disrupting
the whole boot.
This already tested when it got committed to the bootengine repo, this change is just the update of the commit in the coreos-overlay repo.
=> sys-kernel/bootengine: make hostname units optional

coreos-base/oem-gce/files/units/oem-gce.service
The GCE daemon container was run with rkt from an ACI tar ball.
To replace rkt with systemd-nspawn, extract the tar ball to an image
and run the daemon as systemd-nspawn container.
For the release notes:
```
- GCE: The oem-gce.service was ported to use systemd-nspawn instead of rkt.
A one-time action is required to fetch the new service file because the OEM partition is not updated:
sudo curl -s -S -f -L -o /etc/systemd/system/oem-gce.service https://raw.githubusercontent.com/kinvolk/coreos-overlay/fe7b0047ef5b634ebe04c9627bbf1ce3008ee5fa/coreos-base/oem-gce/files/units/oem-gce.service && sudo systemctl daemon-reload && sudo systemctl restart oem-gce.service
```
Checked that service runs on a GCE instance with [this image](http://jenkins.infra.kinvolk.io:8080/job/os/job/board/job/packages- …
=> coreos-base/oem-gce: use systemd-nspawn to run the GCE daemon

sys-apps/systemd/files/0007-core-use-max-for-DefaultTasksMax.patch
The upstream changed the way it handles default value, and
make the property partially dynamic which made the previous patch not work
Local test not done yet. Jenkins CI [running](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2488/cldsv/)
=> sys-apps/systemd: Fix the patch to update DefaultTasksMax

profiles/coreos/base/package.accept_keywords
To be merged with https://github.com/kinvolk/portage-stable/pull/165
```bash
emerge-amd64-usr net-nds/openldap
```
Jenkins CI [running](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2513/cldsv/)
=> profiles: Add accept keywords for openldap

sys-apps/systemd/files/0007-core-use-max-for-DefaultTasksMax.patch
```bash
emerge-amd64-usr sys-apps/systemd
```
Locally tested.
=> sys-apps/systemd: Re-adjust the defaults tasks patch for v246

profiles/coreos/base/package.accept_keywords
To be merged with https://github.com/kinvolk/portage-stable/pull/167
```bash
emerge-amd64-usr net-misc/curl
```
Jenkins CI [running](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2515/cldsv/)
=> profiles: Update the accept keywords for curl 7.76.1

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in a behavior change in the flatcar-install script to
detect if a disk is used through a device mapper entry when searching
for free disks with -s.
https://github.com/kinvolk/init/pull/39
Fixes https://github.com/kinvolk/Flatcar/issues/332
=> coreos-base/coreos-init: flatcar-install, detect device mapper usage

coreos-base/coreos-init/coreos-init-9999.ebuild, sys-kernel/bootengine/bootengine-9999.ebuild
- sys-kernel/bootengine: network, don't manage the loopback interface
This pulls in a change in the systemd network unit to ignore the
loopback interface instead of managing its state which sometimes causes
the address to be lost.
https://github.com/kinvolk/bootengine/pull/24
- coreos-base/coreos-init: systemd/network, don't manage the loopback interface
This pulls in a change in the systemd network unit to ignore the
loopback interface instead of managing its state which sometimes causes
the address to be lost.
https://github.com/kinvolk/init/pull/40
=> network: don't manage the loopback interface

coreos-base/update_engine/update_engine-9999.ebuild
related to https://github.com/kinvolk/update_engine/pull/9
Signed-off-by: Mathieu Tortuyaux <mathieu@kinvolk.io>
```
emerge-amd64-usr coreos-base/update_engine
```
[jenkins](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2684/) - [GCS image](https://storage.googleapis.com/flatcar-jenkins/developer/developer/boards/amd64-usr/2021.05.25%2Bdev-flatcar-master-2684/flatcar_production_qemu_image.img.bz2) - it seems to work as expected, the payload and the `update_url` are correctly fetched. I'm trying to update the `kola` tests to correctly test this part.
=> coreos-base/update_engine: bump commit ID

profiles/coreos/base/package.accept_keywords
To be able to build `dev-libs/libxml2` 2.9.12-r2, we need to accept both `~amd64` and `~arm64` for libxml2.
This PR should be merged together with https://github.com/kinvolk/portage-stable/pull/171 .
```
emerge-amd64-usr dev-libs/libxml2
```
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2696/cldsv/
=> profiles: accept keywords ~amd64 and ~arm64 for libxml2 2.9.12-r2

sys-apps/baselayout/baselayout-9999.ebuild
The output of "systemctl list-units --state=failed --no-legend" still
contains the bullet point which is not expected and ends up being taken
as the unit name which was previously on the start of the line.
Filter the bullet point out to stay compatible with the old behavior in
case upstream would remove the bullet point again.
This pulls in
https://github.com/kinvolk/baselayout/pull/16/
=> sys-apps/baselayout: filter out bullet point when parsing failed units (for flatcar-2765)

profiles/coreos/base/package.accept_keywords
This reverts commit 8d56fd17957540e764ca491285776d2dbb73c38e.
`curl-7.77` is [stable](https://packages.gentoo.org/packages/net-misc/curl).
To be merged with: https://github.com/kinvolk/portage-stable/pull/175
- locally built:
```
core@localhost ~ $ curl --version
curl 7.77.0 (x86_64-cros-linux-gnu) libcurl/7.77.0 OpenSSL/1.1.1k zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps http https imap imaps mqtt pop3 pop3s rtsp smtp smtps tftp
Features: AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM SPNEGO SSL TLS-SRP UnixSockets
```
- [Jenkins](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2851/cldsv/): :green_circle:
=> Revert "profiles: Update the accept keywords for curl 7.76.1"

sys-apps/systemd/systemd-9999.ebuild
Now that lz4 was updated to 1.9.3-r1, systemd has to depend on lz4 >= 1.9.3-r1, so that its dependency graph during the SDK stage3 could be generated correctly.
Without that change, the preclean of SDK stage3 could fail because of an inverted dependency order between systemd and lz4, like following:
```
emerge --depclean --with-bdeps=y
...
* Dependencies could not be completely resolved due to
* the following required packages not being installed:
*
*   >=app-arch/lz4-0_p131:0/r131=[abi_x86_64(-)] pulled in by:
*     sys-apps/systemd-247.6
```
Stage3 first runs `emerge --quiet --usepkg --buildpkg --binpkg-respect-use=y --newuse -e --update --deep --with-bdeps=y @system`, which works well.
After that, only the stage3 (no other stages) runs preclean, which in fact runs `emerge --depclean …
=> sys-apps/systemd: depend on lz4 >= 1.9.3-r1

coreos-base/oem-ec2-compat/files/base/base-aws-pro.ign, coreos-base/oem-ec2-compat/oem-ec2-compat-0.1.2.ebuild
Build an AWS Pro image and check the logs of  `nvidia.service`
CI Passed http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2838/cldsv/
```
ip-172-31-6-218 core # nvidia-smi 
Tue Jun 29 15:28:43 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. | …
```
=> coreos-base/oem-ec2-compat: Add NVIDIA support for AWS Pro

sys-libs/glibc/glibc-2.33-r1.ebuild
We experience an issue with glibc-2.33 which causes all binaries in the
OS image to end up not stripped, which would increase the size of the OS
image threefold.
The change masks glibc-2.33 for all architectures, so the build will
default on glibc-2.32 until we have fixed the issue.
=> sys-libs/glibc-2.33: mask for now to un-break build

app-admin/updateservicectl/updateservicectl-9999.ebuild
Update commit to `6a4ff4ca879082c07353dd379439c437cbe27e18`, to sync with
the current main branch.
Pulls in https://github.com/kinvolk/updateservicectl/pull/6 .
Also update Go import paths to `github.com/kinvolk/updateservicectl`.
Also set `COREOS_GO_GO111MODULE=on` because updateservicectl now relies
on Go module.
(only in SDK)
```
sudo emerge app-admin/updateservicectl
```
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2976/cldsv/
=> app-admin/updateservicectl: sync with current main - 2021-07-05

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/kinvolk/init/pull/41
Run `ls /boot` and see that it works
http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2968/cldsv/
and manually with `kola spawn`:
```
[bound] core@jenkins-azure-bd0ba49349 ~ $ ls /boot
EFI  boot  flatcar  xen
[bound] core@jenkins-azure-bd0ba49349 ~ $ journalctl -f
-- Journal begins at Wed 2021-07-07 10:12:57 UTC. --
Jul 07 10:14:45 jenkins-azure-bd0ba49349 sshd[1291]: pam_unix(sshd:session): session opened for user core(uid=500) by (uid=0)
Jul 07 10:14:45 jenkins-azure-bd0ba49349 systemd[1]: Started Session 9 of user core.
Jul 07 10:14:45 jenkins-azure-bd0ba49349 systemd-logind[960]: New session 9 of user core.
Jul 07 10:15:48 jenkins-azure-bd0ba49349 systemd[1]: boot.automount: Got automount request for /boot, triggered by …
```
=> coreos-base/coreos-init: add udev systemd tag for Azure storage devices

profiles/coreos/base/package.accept_keywords
Signed-off-by: Mathieu Tortuyaux <mathieu@kinvolk.io>
related to: https://github.com/kinvolk/portage-stable/pull/185
- jenkins (:large_blue_circle:): http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2977/cldsv/
=> profiles: accept ~amd64 & ~arm64 for libgcrypt-1.9.3

profiles/coreos/base/package.use
Add telnet useflag directly in the package.use file
Tested by building the image and running the curl command `curl -v telnet://towel.blinkenlights.nl:23`
```
*   Trying 213.136.8.188:23...
*   Trying 2001:7b8:666:ffff::1:42:23...
* Immediate connect fail for 2001:7b8:666:ffff::1:42: Network is unreachable
```
=> net-misc/curl: enable telnet protocol support

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/kinvolk/init/pull/43
**Note:** To be ported to all channels, either with introducing separate branches for `init` or by bringing the following changes along:
https://github.com/kinvolk/init/pull/41
https://github.com/kinvolk/init/pull/42
=> coreos-base/coreos-init: prevent networkd interference with cilium_vxlan

app-arch/torcx/files/dockerd-wrapper.sh, app-emulation/docker/files/dockerd
In https://github.com/kinvolk/coreos-overlay/pull/1055 we disabled `SELinux` for Docker but we did not port this change to the deprecated scripts which enable by default `SELinux`.
We have a test for this `docker.lib-coreos-dockerd-compat` but we did not catch the failure because we explicitely set the `--selinux-enabled` to false - which overrides the default behavior of `dockerd` script. (see: https://github.com/kinvolk/mantle/commit/9101e7016fc1b52ed690e4201ece891b4f863a51#diff-52b597358285b8b043950f2001c39f118a56284357fb13493292ad11d9aa224cR183)
Closes: https://github.com/kinvolk/Flatcar/issues/457
=> docker/torcx: disable SELinux by default on `dockerd` wrapper script

coreos-base/oem-gce/files/units/oem-gce.service
With the switch from rkt to systemd-nspawn the ability for the service
to set the routing entries for the TCP load balancer got lost,
resulting in an unreachable LB as reported in
https://github.com/kinvolk/Flatcar/issues/459
The fix also reported there is to retain CAP_NET_ADMIN when starting
the service.
Regular release tests: http://localhost:9091/job/os/job/manifest/3159/cldsv/
=> coreos-base/oem-gce: grant CAP_NET_ADMIN to set routes for LB

sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/kinvolk/bootengine/pull/26
=> sys-kernel/bootengine: issue a kernel panic on dm-verity corruption

.github/workflows/containerd-apply-patch.sh, .github/workflows/docker-apply-patch.sh, .github/workflows/firmware-apply-patch.sh, .github/workflows/go-apply-patch.sh, .github/workflows/runc-apply-patch.sh, .github/workflows/rust-apply-patch.sh
Before passing runc versions to `sed '/-/!{s/$/_/}'`, we need to replace `_` with `-`, because runc tarball files already have names like `1.0.0_rc2`.
Without the fix, version sort would `1.0.0` come before `1.0.0_rc2`, which is not expected in the later steps.
Due to unnecessary wildcard listings, ebuild files including all rc or beta are being listed.
Since `VERSION_OLD` is already generated as a unique version, we do not need to list multiple files to filter by running `head -n1` etc. We just need to use only the specific ebuild.
Simply list only the unique ebuild file.
=> .github: list only ebuilds with a unique VERSION_OLD for runc

sys-apps/ignition/ignition-9999.ebuild
This pulls in
https://github.com/kinvolk/ignition/pull/22
=> sys-apps/ignition: Ignore filesystem format mismatches for the OEM partition

sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/kinvolk/bootengine/pull/27
See https://github.com/kinvolk/bootengine/pull/27
=> sys-kernel/bootengine: finish network-cleanup.service before rootfs switch

profiles/coreos/arm64/package.accept_keywords
```bash
emerge-amd64-usr app-arch/libarchive
```
CI is running, ~http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3170/cldsv/~
http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3187/cldsv/
To be merged with https://github.com/kinvolk/portage-stable/pull/192
=> profiles: Remove libarchive-3.3.1 from ACCEPT_KEYWORDS

app-emulation/amazon-ssm-agent/amazon-ssm-agent-2.3.1319.0-r1.ebuild, coreos-base/oem-ec2-compat/files/base/base-ec2.ign, coreos-base/oem-ec2-compat/oem-ec2-compat-0.1.2.ebuild
The binaries were too big to fit on our 128MB OEM partition. Now that the OEM partition is compressed-btrfs it fits again, so re-add the dependency to oem-ec2-compat.
The other half of the PR are cross-compilation fixes. The ebuild was not exporting GOARCH and was making use of latest go. When built for arm64, host binaries were produced. The ebuild has been fixed to cross-compile correctly.
Related: https://github.com/kinvolk/Flatcar/issues/107
```
emerge-arm64-usr amazon-ssm-agent
./build_image
./image_to_vm --format=ami
```
Build tested, and tested that the binaries fit on the OEM partition.
=> amazon-ssm-agent: re-add dependency to oem-ec2-compat

coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild, profiles/coreos/base/make.defaults, profiles/coreos/targets/sdk/make.defaults, profiles/coreos/targets/sdk/package.use
As we do not use ccache at all, we should simply clean up ccache from all of the code, to shrink size of the SDK.
This PR should be merged together with https://github.com/kinvolk/portage-stable/pull/161 .
CI passed: https://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2353/cldsv/
=> profiles: delete ccache completely

sys-apps/baselayout/baselayout-9999.ebuild
This pulls in
https://github.com/kinvolk/baselayout/pull/18
Backport to 2095, 2942, 2955
=> sys-apps/baselayout: fix sssd LDAP auth with sudo

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/kinvolk/init/pull/45
but from a backport branch "flatcar-2905-backport".
I had to introduce a new branch because the motd changes for cgroupv2 were already merged.
This here is going to be picked for flatcar-2905, flatcar-2942, and flatcar-2955
=> coreos-base/coreos-init: embed new subkey in flatcar-install

sec-policy/selinux-virt/files/virt.patch
In this PR, we provide another `virt` rules to have `flannel` correctly running with enforced SELinux.
```
emerge-amd64-usr -av sec-policy/selinux-virt
// run SELinux in enforced mode
// run kubernetes with Flannel as CNI
```
- ran the kola kubeadm flannel tests (from this PR: https://github.com/kinvolk/mantle/pull/196 or https://github.com/kinvolk/mantle/pull/205)
```
--- PASS: kubeadm.v1.21.0.flannel.base/node_readiness (30.97s)
--- PASS: kubeadm.v1.21.0.flannel.base/nginx_deployment (21.64s)
```
- CI :large_blue_circle: : http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3265/
Closes: https://github.com/kinvolk/Flatcar/issues/476
Also related to: https://github.com/flannel-io/flannel/issues/945, https://github.com/flannel-io/flannel/issues/709
@kinvolk/flatcar-maintainers how …
=> sec-policy/selinux-virt: add rules to run `flannel` with SELinux enforced mode

app-emulation/wa-linux-agent/wa-linux-agent-2.2.46.ebuild, coreos-base/oem-azure/oem-azure-2.2.46.ebuild, coreos-devel/board-packages/board-packages-0.0.1.ebuild
While not used at the moment we still can lift the restriction to only
compile for the amd64 board.
Build all packages and run the `image_to_vm.sh` script for Azure
=> Compile Azure OEM contents for all boards

coreos-base/coreos-init/coreos-init-9999.ebuild, coreos-base/coreos/coreos-0.0.1.ebuild
`emerge-amd64-usr coreos-base/coreos`
`./build_image`
Then checked in the flatcar instance that there is `lbzip2` in the.
=> Add app-arch/lbzip2 to the coreos ebuild dependencies

app-misc/ca-certificates/ca-certificates-3.27.1-r2.ebuild, app-misc/ca-certificates/files/certdata2pem.py
It produces files with the same contents as the python2 version of the
script, but the filename handling is a bit different wrt. filenames
with weird, non-unicode characters. But overall, it does not affect
anything.
I verified that the contents produces by the script are the same by running something like `sha512sum *.pem | cut -f1 -d' ' | sha512sum` (cut here is to only get the sum and discard the filename) in `/usr/share/ca-certificates` on images with pem files produced by old and new version of the script. The difference in filename handling is as below:
old:
new:
CI: http://localhost:9091/job/os/job/manifest/3443/cldsv/
=> app-misc/ca-certificates: Port the python script to python3

profiles/coreos/targets/generic/package.use
This change results in building the pam_tty_audit module additionally, nothing else.
Related to https://github.com/kinvolk/Flatcar/issues/485.
```
./build_image
```
=> profiles: enable 'audit' use flag for sys-libs/pam

coreos/config/env/dev-lang/perl
Current cross builds of perl segfault on simple operations such as `perl -V`.
This appears to be due to the cross-build not getting `-fwrapv -fno-strict-aliasing`
passed from the configure script. While we try to get this fixed upstream, we
can monkeypatch our old version of perl to fix this.
Upstream PR: https://github.com/gentoo/gentoo/pull/22167
Related issue: https://github.com/kinvolk/Flatcar/issues/490
```
emerge-amd64-usr perl
```
```
sudo mount --bind /dev /build/amd64-usr/dev
sudo chroot /build/amd64-usr/ perl -V
```
Output:
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = (unset),
LANG = "C.UTF8"
are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C"). …
```
=> coreos/config: add fix for perl cross-compilation

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/kinvolk/init/pull/47
to randomize OEM filesystem UUID if mounting fails, and to avoid trying
to install the QEMU qcow2 images.
=> coreos-base/coreos-init: flatcar-install random OEM FS UUID if duplicate

profiles/coreos/arm64/package.accept_keywords
Now that `sys-apps/policycoreutils` is [pulled in](https://github.com/kinvolk/coreos-overlay/pull/1240) explicitly for both architectures, we should be able to pull in its dependencies, e.g.
`sys-apps/semodule-utils`, `sys-libs/libselinux`, `sys-libs/libsemanage`,
`sys-libs/libsepol`.
In case of arm64, however, all the ebuilds have only `~arm64`. So we need to enable the keywords for the ebuilds.
Without the changes, build fails like:
```
!!! All ebuilds that could satisfy
">=sys-libs/libselinux-3.1:=[python?,python_targets_python3_6(-)?,-python_single_target_python3_6(-)]"
for /build/arm64-usr/ have been masked.
!!! One of the following masked packages is required to complete your
request:
- sys-libs/libselinux-9999::coreos (masked by: missing keyword)
- sys-libs/libselinux-3.2::coreos …
```
=> profiles: accept keyword ~arm64 for selinux

.github/workflows/setup-flatcar-sdk.sh
`Flatcar_Image_Signing_Key.asc` on https://www.flatcar-linux.org is
outdated, expired. That's why all Github Actions failed to run.
We need to fetch the image signing key from the correct URL,
https://kinvolk.io/flatcar-container-linux/security/image-signing-key/Flatcar_Image_Signing_Key.asc .
=> .github: fetch the correct Flatcar image signing key

sys-fs/mdadm/files/mdadm.service, sys-fs/mdadm/files/mdadm.timer, sys-fs/mdadm/files/mdadm.weekly, sys-fs/mdadm/mdadm-4.1.ebuild
Add a mdadm.timer unit and associate it with the mdadm package and remove the cron.weekly.
=> mdadm: migrate cron.weekly to systemd.timer

coreos-base/coreos/coreos-0.0.1.ebuild, profiles/coreos/amd64/generic/package.use, profiles/coreos/amd64/generic/use.mask, profiles/coreos/amd64/sdk/package.use, profiles/coreos/amd64/sdk/use.mask, profiles/coreos/arm64/package.use, profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.use, profiles/coreos/base/use.mask
Move the USE options out of the amd64 path, specify selinux
packages as explicit dependency, and add accept keywords.
Replaces https://github.com/kinvolk/coreos-overlay/pull/135
The goal is to enable the selinux tests again in kola.
Ongoing, have to check if selinux use flags get enabled and whether removing the kola exemption for selinux on arm64 works
http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3470/cldsv/
=> profiles: Enable selinux for all targets

coreos-base/coreos-init/coreos-init-9999.ebuild
Comes with https://github.com/kinvolk/init/pull/48. Will update the commit ID when the init PR gets merged.
CI: http://localhost:9091/job/os/job/manifest/3487/cldsv/
=> coreos-base/coreos-init: Port to python3

sys-auth/sssd/files/sssd-2.3.1-CVE-2021-3621.patch, sys-auth/sssd/sssd-2.3.1-r3.ebuild
This is a backport of the CVE-2021-3621 fix to 2.3.1. The fix is not present in any released version and 2.5.x ebuilds are not marked stable in Gentoo tree yet.
Only build tested. We don't have any sssd related tests.
=> sys-auth/sssd: fix CVE-2021-3621

profiles/coreos/base/package.accept_keywords
~The Gentoo upstream has not tested the package against [architectures](https://github.com/gentoo/gentoo/blob/6d0190c2229052c9bcc4c93d9729faf831f9e4e0/sys-devel/binutils/binutils-2.37.ebuild#L35-L36). It would not be a good idea to release before the upstream.~
To be merged with https://github.com/kinvolk/portage-stable/pull/191
~Jenkins Running, http://localhost:9091/job/os/job/manifest/3166/cldsv/~
Jenkins CI http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3534/cldsv/
=> profiles: Add binutils-2.37 to the accept_keywords

app-shells/bash/files/dot-bashrc
Added alias for bcc tool packages `tcpretrans tcpconnect tcpaccept biolatency ext4slower ext4dist` to run necessary debug tools
- `emerge-amd64-usr app-shells/bash`
- Run those alias in the image.
=> Add alias for bcc tools to run in docker container

profiles/coreos/base/make.defaults, profiles/coreos/base/package.use
Try to use `minimal` version of `Perl`.
jenkins (:large_blue_circle:): http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3603/cldsv/
To be merged with: https://github.com/flatcar-linux/portage-stable/pull/215
=> profiles/base/use: add `minimal` useflag to `dev-lang/perl`

.github/workflows/common.sh, .github/workflows/containerd-apply-patch.sh, .github/workflows/docker-apply-patch.sh, .github/workflows/firmware-apply-patch.sh, .github/workflows/go-apply-patch.sh, .github/workflows/runc-apply-patch.sh, .github/workflows/rust-apply-patch.sh
The bug fix https://github.com/flatcar-linux/coreos-overlay/pull/1129 caused a regression that Github Actions cannot determine a correct `$VERSION_OLD` if the old ebuild file has a suffix like `-r1`.
That's why recently Github Actions for firmware have failed to run.
We need to create a function to get a correct ebuild file name, by falling back to the most similar name, in case the expected ebuild file does not exist.
=> .github: get correct ebuild file name from old version

.github/workflows/common.sh, .github/workflows/containerd-apply-patch.sh, .github/workflows/containerd-releases-main.yml, .github/workflows/docker-apply-patch.sh, .github/workflows/docker-releases-main.yml, .github/workflows/firmware-apply-patch.sh, .github/workflows/firmware-releases-main.yml, .github/workflows/go-apply-patch.sh, .github/workflows/go-releases-main.yml, .github/workflows/kernel-apply-patch.sh, .github/workflows/kernel-releases-alpha.yml, .github/workflows/kernel-releases-beta.yml, .github/workflows/kernel-releases-lts-2021.yml, .github/workflows/kernel-releases-main.yml, .github/workflows/kernel-releases-stable.yml, .github/workflows/runc-apply-patch.sh, .github/workflows/runc-releases-main.yml, .github/workflows/rust-apply-patch.sh, .github/workflows/rust-release-main.yml, .github/workflows/vmware-apply-patch.sh, .github/workflows/vmware-releases-main.yml
Automatically update `coreos/open-vm-tools` as well as `coreos-base/oem-vmware`.
Get the latest open-vm-tools release number, and get its build number from the Github repo, and replace the old build number with the new one.
Also sync `coreos-base/oem-vmware` in line with `open-vm-tools`.
To do that, we need to also split git repo init part into `prepare_git_repo`, to prevent some corner cases, where applying multiple patches does not work because the latter overwrites the former patch.
We need to also clean up an unnecessary patch file.
=> .github: new Github workflow for open-vm-tools

sec-policy/selinux-base/selinux-base-2.20200818-r2.ebuild
selinux-base needs python with xml support, but the dependency was implicit through policycoreutils, and we removed that dependency downstream. This shows up during stage3 of bootstrap_sdk. Fix the issue by adding an explicit dependency and removing the previous attempt at fixing the issue (forcing sequential build, which does nothing).
`./boostrap_sdk`.
Will let CI run.
=> selinux-base: fix build issue during boostrap

app-admin/locksmith/locksmith-9999.ebuild, app-admin/mayday/mayday-9999.ebuild, app-admin/sdnotify-proxy/sdnotify-proxy-9999.ebuild, app-admin/toolbox/toolbox-9999.ebuild, app-admin/updateservicectl/updateservicectl-9999.ebuild, app-arch/torcx/torcx-9999.ebuild, app-crypt/go-tspi/go-tspi-9999.ebuild, app-emulation/acbuild/acbuild-9999.ebuild, app-emulation/actool/actool-9999.ebuild, coreos-base/afterburn/afterburn-9999.ebuild, coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild, coreos-base/coreos-init/coreos-init-9999.ebuild, coreos-base/emerge-gitclone/emerge-gitclone-9999.ebuild, coreos-base/nova-agent-watcher/nova-agent-watcher-9999.ebuild, coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild, coreos-base/update_engine/update_engine-9999.ebuild, coreos-devel/fero-client/fero-client-9999.ebuild, coreos-devel/mantle/mantle-9999.ebuild, profiles/coreos/arm64/package.accept_keywords, sys-apps/baselayout/baselayout-9999.ebuild, sys-apps/ignition/ignition-9999.ebuild, sys-apps/seismograph/seismograph-9999.ebuild, sys-boot/grub/grub-9999.ebuild, sys-boot/shim/shim-9999.ebuild, sys-kernel/bootengine/bootengine-9999.ebuild, sys-libs/nss-usrfiles/nss-usrfiles-9999.ebuild
Replace `git://` with `https://` for Github URLs, because Github now rejects an unauthenticated git access.
See also https://github.blog/2021-09-01-improving-git-protocol-security-github/.
* app-admin/locksmith
* app-admin/mayday
* app-admin/sdnotify-proxy
* app-admin/toolbox
* app-admin/updateservicectl
* app-arch/torcx
* app-crypt/go-tspi
* app-emulation/acbuild
* app-emulation/actool
* coreos-base/afterburn
* coreos-base/coreos-cloudinit
* coreos-base/coreos-init
* coreos-base/emerge-gitclone
* coreos-base/nova-agent-watcher
* coreos-base/update-ssh-keys
* coreos-base/update_engine
* coreos-devel/fero-client
* coreos-devel/mantle
* sys-apps/baselayout
* sys-apps/ignition
* sys-apps/seismograph
* sys-boot/grub
* sys-boot/shim
* sys-kernel/bootengine
* sys-libs/nss-usrfiles
This PR …
=> *: use https instead of git for Github URLs

profiles/coreos/base/package.accept_keywords
To be able to update `net-misc/wget` to 1.21.2, accept keywords for both `~amd64` and `~arm64`.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/233 .
```
emerge-amd64-usr net-misc/wget
```
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4010/cldsv
=> profiles: accept keywords for wget 1.21.2.

app-emulation/docker/docker-1.12.6-r8.ebuild, app-emulation/docker/docker-17.03.2-r1.ebuild, app-emulation/rkt/rkt-9999.ebuild, coreos-base/cros-devutils/cros-devutils-9999.ebuild
We need to fix more URLs in LTS 2605, including `docker`, `rkt`, and `cros-devutils`.
=> *: replace git:// with https:// for Github URLs

app-admin/locksmith/locksmith-9999.ebuild, app-admin/mayday/mayday-9999.ebuild, app-admin/sdnotify-proxy/sdnotify-proxy-9999.ebuild, app-admin/toolbox/toolbox-9999.ebuild, app-admin/updateservicectl/updateservicectl-9999.ebuild, app-arch/torcx/torcx-9999.ebuild, app-crypt/go-tspi/go-tspi-9999.ebuild, app-emulation/acbuild/acbuild-9999.ebuild, app-emulation/actool/actool-9999.ebuild, coreos-base/afterburn/afterburn-9999.ebuild, coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild, coreos-base/coreos-init/coreos-init-9999.ebuild, coreos-base/emerge-gitclone/emerge-gitclone-9999.ebuild, coreos-base/nova-agent-watcher/nova-agent-watcher-9999.ebuild, coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild, coreos-base/update_engine/update_engine-9999.ebuild, coreos-devel/fero-client/fero-client-9999.ebuild, coreos-devel/mantle/mantle-9999.ebuild, profiles/coreos/arm64/package.accept_keywords, sys-apps/baselayout/baselayout-9999.ebuild, sys-apps/ignition/ignition-9999.ebuild, sys-apps/seismograph/seismograph-9999.ebuild, sys-boot/grub/grub-9999.ebuild, sys-boot/shim/shim-9999.ebuild, sys-kernel/bootengine/bootengine-9999.ebuild, sys-libs/nss-usrfiles/nss-usrfiles-9999.ebuild
This PR reverts https://github.com/flatcar-linux/coreos-overlay/pull/1386, because the PR caused the SDK stage2 build to fail due to missing ssl in libcurl.
```
git fetch https://github.com/flatcar-linux/baselayout.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
fatal: unable to access 'https://github.com/flatcar-linux/baselayout.git/': Protocol "https" not supported or disabled in libcurl
```
Revert until we can fix the issue correctly in the future.
With https://github.com/flatcar-linux/portage-stable/pull/239.
=> Revert back to git:// URLs

app-admin/locksmith/locksmith-9999.ebuild, app-admin/mayday/mayday-9999.ebuild, app-admin/sdnotify-proxy/sdnotify-proxy-9999.ebuild, app-admin/toolbox/toolbox-9999.ebuild, app-admin/updateservicectl/updateservicectl-9999.ebuild, app-arch/torcx/torcx-9999.ebuild, app-crypt/go-tspi/go-tspi-9999.ebuild, app-emulation/acbuild/acbuild-9999.ebuild, app-emulation/actool/actool-9999.ebuild, coreos-base/afterburn/afterburn-9999.ebuild, coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild, coreos-base/coreos-init/coreos-init-9999.ebuild, coreos-base/emerge-gitclone/emerge-gitclone-9999.ebuild, coreos-base/nova-agent-watcher/nova-agent-watcher-9999.ebuild, coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild, coreos-base/update_engine/update_engine-9999.ebuild, coreos-devel/fero-client/fero-client-9999.ebuild, coreos-devel/mantle/mantle-9999.ebuild, profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/make.defaults, sys-apps/baselayout/baselayout-9999.ebuild, sys-apps/ignition/ignition-9999.ebuild, sys-apps/seismograph/seismograph-9999.ebuild, sys-boot/grub/grub-9999.ebuild, sys-boot/shim/shim-9999.ebuild, sys-kernel/bootengine/bootengine-9999.ebuild, sys-libs/nss-usrfiles/nss-usrfiles-9999.ebuild
(This PR is another attempt of https://github.com/flatcar-linux/coreos-overlay/pull/1386, which was reverted)
Replace `git://` with `https://` for Github URLs, because Github now rejects an unauthenticated git access.
See also https://github.blog/2021-09-01-improving-git-protocol-security-github/.
In addition, fix a build issue during SDK stage2, where git + libcurl could not fetch from `https://` URLs.
To resolve the issue, we need to install curl with `BOOTSTRAP_USE=ssl` before trying to install baselayout.
Also we need to set `CURL_SSL=openssl` as required by curl. Using a USE_EXPAND variable `curl_ssl_openssl` in `BOOTSTRAP_USE`, we can specify the correct `CURL_SSL` variable in curl.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/240.
CI …
=> *: *: use https instead of git for Github URLs (take 2)

coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild, profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.use, profiles/coreos/targets/sdk/package.accept_keywords, profiles/features/systemd/package.accept_keywords
Delete unnecessary ebuilds from accept_keywords.
Clean up unnecessary ebuilds from base accept_keywords like below.
Sort alphabetically.
* `app-crypt/efitools`: move to sdk
* `app-misc/jq`: move to arm64
* `cross-aarch64-cros-linux-gnu/gcc`: move 9.3.0-r1 to arm64
* `dev-lang/spidermonkey` is not needed any more.
* `dev-libs/protobuf` 3.5.2 is already stable.
* `dev-libs/elfutils`: specify explicit version 0.178
* `dev-python/boto`: specify explicit keywords ~amd64, ~arm64.
* `dev-util/dwarves`: specify explicit version 1.19
* `dev-util/perf` 5.8 is already stable.
* `net-misc/curl`: move 7.79.1 to arm64
* `net-nds/rpcbind`: specify explicit keywords ~amd64, ~arm64.
* `net-libs/libnftnl` 1.2.0-r1 is already stable.
* `net-libs/libmicrohttpd`: move from arm64, specify explicit keywords.
* …
=> profiles: delete unnecessary accept_keywords

profiles/coreos/base/package.use.mask
`app-editors/nano` with `USE=unicode` results in build failures in SDK stage1, because ncurses >= 6.2_p20210619 which does not have the USE flag at all.
To fix that, exclude the unicode USE flag from `packages.use.force` list, which is defined in portage-stable.
We can do that by setting the flag in `package.use.mask`.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/245.
CI passed http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4128/cldsv
(with specific SEED_SDK_{OVERLAY,PORTAGE}_GITREF values)
=> profiles: exclude unicode USE flag from app-editors/nano

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/targets/generic/package.provided
Should be merged with https://github.com/flatcar-linux/portage-stable/pull/242.
CI passed: http://localhost:9091/job/os/job/manifest/4109/cldsv/
=> profiles: Changes related to package updates in portage-stable (getting rid of EAPI 3)

profiles/coreos/arm64/package.accept_keywords
The recent keyword cleanup removed two keywords that are necessary to
bootstrap an arm64 sdk: open-vmdk and virtual/cdrtools. Restore them.
No real great way, because we don't have automated sdk bootstrap for arm64 yet.
Tested that `./boostrap_sdk stage4` starts instead of failing due to unmet dependencies.
=> profiles: add missing arm64 sdk keywords

profiles/coreos/arm64/package.accept_keywords
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4148/cldsv
=> dev-embedded/u-boot-tools: Update to v2021.04_rc2 for arm64

.github/workflows/cacerts-apply-patch.sh, .github/workflows/cacerts-releases-alpha.yml, .github/workflows/cacerts-releases-beta.yml, .github/workflows/cacerts-releases-lts-2021.yml, .github/workflows/cacerts-releases-main.yaml, .github/workflows/cacerts-releases-stable.yml
Automatically update `app-misc/ca-certificates`, a derivative of [nss](https://hg.mozilla.org/projects/nss).
To make things easier, we simply check for new releases on its [Github mirror](https://github.com/nss-dev/nss).
When the new latest tag is found, simply bump the version of ca-certificates ebuild.
Fixes https://github.com/flatcar-linux/Flatcar/issues/533.
=> .github: add Github Actions for ca-certificates

.github/workflows/cacerts-releases-main.yaml
Since every tag of the nss Github repo has `_` delimiters, we need to first use `sort -t_` for sorting, then after that we need to replace `_` with `.` by calling tr.
Without that conversion, the input ebuild file name will be wrong.
We fixed the issue in all other maintenance branches, but not in main.
Fix that also in main.
=> .github: fix version delimiter of ca-certs workflow for main

sec-policy/selinux-base-policy/files/unlabeled.patch, sec-policy/selinux-base-policy/selinux-base-policy-2.20200818-r2.ebuild
with this patch, we allow `unlabeled_t` to associate to tmpfs
filesystem.
It aims to solve the AVC we have with `torcx` with the
`torcx-generator`:
```
Nov 15 09:45:43 localhost audit[688]: AVC avc: denied { associate } for pid=688 comm="torcx-generator" name="docker" dev="tmpfs" ino=2 scontext=system_u:object_r:unlabeled_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=filesystem permissive=0
```
It has been not been caught earlier because it occurs
when the system boots with `SELinux` in `enforcing` mode.
This denial was preventing torcx to finish correctly its setup and so
Docker was not able to start.
<hr>
It has been reported in https://github.com/flatcar-linux/Flatcar/issues/544
CI :large_blue_circle: : …
=> sec-policy/selinux-base-policy: add capability to unlabeled_t

profiles/coreos/base/package.accept_keywords
To be able to update rsync to 3.2.3-r5, we need to accept keywords for both `~amd64` and `~arm64`.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/249 .
CI passed except SELinux failures: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4187/cldsv
=> profiles: accept keywords for rsync 3.2.3-r5

app-admin/logrotate/files/logrotate.service, app-admin/logrotate/logrotate-3.18.1-r1.ebuild
By accident the upstream files from the example folder got used,
instead of the downstream files that were added in the files/ folder.
Also, the configuration file didn't get installed.
Use the right paths to install the downstream files.
Check that logrotate doesn't fail
Pick for flatcar-3066
Booted https://bucket.release.flatcar-linux.net/flatcar-jenkins/developer/developer/boards/amd64-usr/2021.11.22+dev-flatcar-master-4222/flatcar_production_image.bin.bz2
and ran `sudo systemctl start logrotate.service` and `systemctl status logrotate.service` and it worked: `Process: 958 ExecStart=/usr/bin/logrotate /usr/share/logrotate/logrotate.conf (code=exited, status=0/SUCCESS)`
=> app-admin/logrotate: Correct downstream changes to take effect

profiles/coreos/base/package.accept_keywords
Signed-off-by: ArkaprabhaChakraborty <chakrabortyarkaprabha998@gmail.com>
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/243. 
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4221/cldsv
=> Upgrade net-libs/libmicrohttpd to 0.9.73

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
Now that gcc 9.4.0 already has stable keywords both amd64 and arm64, we do not need to accept keywords in profiles.
Simply delete.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/252 .
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4238/cldsv
=> profiles: delete unnecessary keywords for gcc

app-admin/etcd-wrapper/files/etcd-wrapper
`etcd` node's name was defined by `ETCD_NAME`, from `etcd/v3` the server
can't be started with both `ETCD_NAME` and `--name` supplied.
Which leads to three cases:
* `etcd-member.service` starts without further configuration, no issue
since only `ETCD_NAME=%m` is used
* `etcd-member.service` is overrided with a CLC without `name: ` key, no
issue since only `ETCD_NAME=%m` is used
* `etcd-member.service` is overrided with a CLC with a `name: ` key,
there is an issue since in the final service we will have both
`ETCD_NAME=%m` and `--name name-from-clc`
This patch conditionally unset the `ETCD_NAME` in case `--name/-name` is
supplied.
Closes: https://github.com/flatcar-linux/Flatcar/issues/547
<hr>
CI :large_blue_circle: : …
=> app-admin/etcd-wrapper: remove `ETCD_NAME`

changelog/security/2021-11-30-CVE-2020-14040.md, sys-apps/ignition/ignition-9999.ebuild
Update `golang.org/x/text` to 0.3.7, mainly to address [CVE-2020-14040](https://nvd.nist.gov/vuln/detail/CVE-2020-14040).
Pulls in https://github.com/flatcar-linux/ignition/pull/31
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4270/cldsv
=> sys-apps/ignition: update golang.org/x/text to 0.3.7

profiles/coreos/amd64/generic/package.use, profiles/coreos/arm64/generic/package.use, profiles/coreos/base/package.accept_keywords
Delete unnecessary keywords after updating vim to 8.2.3582.
Disable the USE flag `crypt` for vim, not to pull in unnecessary dependency libsodium.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/255.
=> profiles: adjust profiles for vim 8.2.3582

app-arch/torcx/files/docker-1.12-no.json, changelog/bugfixes/2021-12-01-torcx-docker-1.12-no-profile.md
When selecting the docker-1.12-no profile, torcx failed because the
profile looked for 19.03 instead of 20.10.
Make the docker-1.12-no profile identical to the vendor profile so
that we don't have to update it.
Check that
```
echo docker-1.12-no | sudo tee /etc/torcx/next-profile
sudo reboot
```
works again.
Backport to Stable, Beta, Alpha.
build scheduled, ran the above test
=> app-arch/torcx: Fix wrong reference to Docker 19.03

.github/workflows/cacerts-apply-patch.sh, .github/workflows/common.sh, .github/workflows/containerd-apply-patch.sh, .github/workflows/docker-apply-patch.sh, .github/workflows/firmware-apply-patch.sh, .github/workflows/go-apply-patch.sh, .github/workflows/kernel-apply-patch.sh, .github/workflows/runc-apply-patch.sh, .github/workflows/rust-apply-patch.sh, .github/workflows/vmware-apply-patch.sh
It's a bit dumb, as it only generates the update changelogs. If the update addresses some CVE, it needs to be added manually. The only smarts it has is that it will handle missing `changelog` directory gracefully.
This also adds some fixes:
- for docker job - add changes made in other packages too (torcx docker, docker-runc and docker-cli)
- for vmware job - update both open-vm-tools and coreos-base/oem-vmware under a single commit
=> Teach github actions to generate changelog entries

.github/workflows/kernel-apply-patch.sh
Tested on my fork. Results in a PR like this: https://github.com/krnowak/coreos-overlay/pull/2/files
=> .github: Try to get a lwn link for kernel release

changelog/changes/2021-12-06-update-engine-kured.md, coreos-base/update_engine/update_engine-9999.ebuild
This pulls in
https://github.com/flatcar-linux/update_engine/pull/15 to create the
Ubuntu-compatible /run/reboot-required flag file for kured.
see https://github.com/flatcar-linux/update_engine/pull/15
=> coreos-base/update_engine: Create reboot flag file for kured

changelog/security/2021-11-30-golang-text-ignition.md
We missed changelog for [CVE-2021-38561](https://nvd.nist.gov/vuln/detail/CVE-2021-38561) when updating `golang.org/x/text` to 0.3.7 in ignition.
=> changelog: add missing CVE for golang.org/x/text in ignition

profiles/coreos/amd64/generic/package.use, profiles/coreos/arm64/generic/package.use, profiles/coreos/base/package.accept_keywords
Delete unnecessary keywords after updating vim to 8.2.3582.
Disable the USE flag `crypt` for vim, not to pull in unnecessary dependency libsodium.
This issue was already addressed via https://github.com/flatcar-linux/coreos-overlay/pull/1455, but only for main.
That's why we need to fix it also in maintenance branches.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/260 .
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4355/cldsv
=> profiles: adjust profiles for vim 8.2.3582 for flatcar-3033,3066

changelog/bugfixes/2021-12-09-set-kubenet-cbr0-unmanaged.md, coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in https://github.com/flatcar-linux/init/pull/55 to set the
cbr0 interface to be excluded from networkd (unmanaged) because it is
set up manually by kubenet and not through DHCP.
See PR, will also start a test build just to be sure
=> coreos-base/coreos-init: prevent networkd interference with cbr0 iface

.github/workflows/mirror-calico.sh, .github/workflows/mirror-calico.yml, .github/workflows/mirror-to-ghcr.sh
this action will sync our ghcr calico images with upstream docker
images.
<hr>
`kubeadm.*.calico` tests are using Calico images from GHCR in order to circumvent Docker hub pulling rate limit, the issue is that we can't really pin the image tag used by Calico tests (see: https://github.com/projectcalico/calico/issues/5121) so each time Calico is releasing, CI is failing while images are not updated into GHCR.
It should be a temporary thing :tm: while https://github.com/projectcalico/calico/issues/5121 is being handled :) 
Script is based on internal custom scripts we were currently using. 
Tested on my fork: https://github.com/tormath1/coreos-overlay/actions/runs/1548773225
=> .github/wf: add mirror-calico action

changelog/bugfixes/2021-12-16-policycoreutils-fix-semodule-postinst.md, sys-apps/policycoreutils/policycoreutils-3.1-r3.ebuild
The policycoreutils ebuild calls `semodule` in postinst to update SELinux stores.
It does not, however, tells `semodule` the correct ROOT to use, so builds that go into `/build/[arch]-usr` end up updating the SDK's store.
Fixes 
libsemanage.semanage_commit_sandbox: Error while renaming /var/lib/selinux/targeted/active to /var/lib/selinux/targeted/previous. (Invalid cross-device link)
observed when using the SDK Container to build the OS image.
It now also updates the correct store, which it previously did not.
We should consider cherry-picking this patch to flatcar-3033, flatcar-3066, and flatcar-3087.
<hr>
CI (running): http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4397/cldsv/
=> sys-apps/policycoreutils: update correct SELinux store

changelog/bugfixes/2021-12-16-ensure-xtables-lock-exists.md, coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in https://github.com/flatcar-linux/init/pull/57
to make sure the /run/xtables.lock file exists for coordination of
xtables modifications.
Backport to Alpha, Beta, maybe also Stable but it needs to have its own init repo branch
see linked PR
=> coreos-base/coreos-init: ensure /run/xtables.lock exists

changelog/changes/2021-12-16-exclude-bridge-and-tunnels-from-DHCP.md, coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in [flatcar-linux/init#56](https://github.com/flatcar-linux/init/pull/56)
to find a generic way of preventing conflicts with CNI interfaces that
shouldn't use DHCP and were matched by name to be set Unmanaged.
started CI run, will maybe extend it to more platforms
=> coreos-base/coreos-init: exclude bridge ifaces from the DHCP config

changelog/changes/2021-12-21-iproute-with-elf.md, profiles/coreos/base/package.use
enables ELF support to e.g. allow tc to handle BPF filters.
It has been dropped in this commit: https://github.com/flatcar-linux/portage-stable/commit/406576c5e554e10950c82fa7f3692d62743958b2
<hr>
Close: https://github.com/flatcar-linux/Flatcar/issues/584
CI (running): http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4446/cldsv/
NOTE: This can be safely cherry-picked to maintenance branches
=> profiles/coreos/base: backport `iproute2` ELF support

changelog/README.md, changelog/bugfixes/2021-12-16-policycoreutils-fix-semodule-postinst.md
The used changelog entry format in
https://github.com/flatcar-linux/coreos-overlay/pull/1502 is not really
useful for the release notes. This paragraph is good for the PR
description or a commit message, but here should be a bullet point for
the release notes.
Replace the paragraph by a release notes bullet point.
Also contains the same README update as
https://github.com/flatcar-linux/portage-stable/pull/266
and 
https://github.com/flatcar-linux/scripts/pull/195
=> changelog: rewrite entry for PR 1502

.github/workflows/common.sh
All runs of the GitHub Action to update the kernel used the same
changelog name, which is a bit confusing when comparing the releases.
Append the version to the filename to avoid using the same name for the
maintenance updates of a channel releases and for the introduction of a
kernel update in main.
None
=> .github: Use different kernel changelog file name per version

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/targets/generic/package.use
Should be merged together with https://github.com/flatcar-linux/portage-stable/pull/246.
CI: http://localhost:9091/job/os/job/manifest/4408/cldsv/
=> profiles: Changes related to package updates in portage-stable (getting rid of EAPI 4)

profiles/coreos/base/package.use, sec-policy/selinux-base-policy/files/ping.patch, sec-policy/selinux-base-policy/selinux-base-policy-2.20200818-r2.ebuild, sec-policy/selinux-base/files/icmp-bind.patch, sec-policy/selinux-base/selinux-base-2.20200818-r2.ebuild
This adds a patch to selinux policy to allow `ping -I` and updates the use flags.
Needs to be merged together with https://github.com/flatcar-linux/portage-stable/pull/270.
CI: http://localhost:9091/job/os/job/manifest/4576/cldsv/
=> Changes for net-misc/iputils update

changelog/bugfixes/2022-01-13-policycoreutils-fix-root-path.md, sys-apps/policycoreutils/policycoreutils-3.1-r3.ebuild
root needs to be specified with -p instead of -S.
The policy dir (-S) defaults to (-p) + /var/lib/selinux/ + (-s).
Picked from upstream: https://github.com/gentoo/gentoo/commit/54a8322d1885f7f1bfe2718fb731d6e195f86466
Closes: https://github.com/flatcar-linux/Flatcar/issues/596
<hr>
Pick for `flatcar-3115` when merging
CI OK for amd64 - but not for ARM64, error with `iputils` but not related: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4585/cldsv/
=> sys-apps/policycoreutils: fix policy root path

.github/workflows/mirror-calico.yml
Workflow is currently failing because it finds the wrong tag, this commit fixes that.
```
$ git clone https://github.com/projectcalico/calico calico
$ git -C calico tag --sort=-authordate | head -1
v3.21.3
```
=> .github: find latest calico tag when mirroring

profiles/coreos/base/package.mask, profiles/coreos/base/package.unmask, profiles/coreos/base/package.use.mask, profiles/features/systemd/package.accept_keywords, sys-apps/portage/portage-3.0.28-r1.ebuild, sys-apps/systemd/systemd-9999.ebuild, sys-libs/ldb/ldb-2.3.0-r2.ebuild, sys-libs/timezone-data/timezone-data-2019b-r2.ebuild, sys-libs/timezone-data/timezone-data-2019c.ebuild
A bunch of things has changed recently:
- Crypt functionality in glibc was deprecated in favor of using libxcrypt. For now I'm reverting the deprecation, so we still keep using crypt from glibc, as the migration has some blockers for us (see #1543).
- uclibc was removed, so we need to drop all mentions of `elibc_uclibc`.
- Same with mintlib, so we need to drop all mentions of `elibc_mintlib`.
- `sys-apps/hwids` was deprecated in favor of `sys-apps/hwdata`, so we migrate to it
- systemd needed some small sync with gentoo in this regard
Needs to be merged together with https://github.com/flatcar-linux/portage-stable/pull/268.
CI: http://localhost:9091/job/os/job/manifest/4566/cldsv/
=> Drop obsolete stuff after updating profiles

changelog/bugfixes/2022-01-14-enable-icmpv6-router-adverts.md, changelog/bugfixes/2022-01-26-flatcar-update-user-env-var.md, coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/flatcar-linux/init/pull/58
(bin/flatcar-update: don't assume $USER is set up, only use $EUID)
and
https://github.com/flatcar-linux/init/pull/51
network: Enable the RAs to fix IPv6 address assignment
None for the RA change, this just got dragged in because there was no update for it separately - it's assumed to fix the IPv6 related bug reports and we need some more PRs to update the other components which have the change merged already
=> coreos-base/coreos-init/coreos-init: pull in latest changes

changelog/bugfixes/2022-01-14-enable-icmpv6-router-adverts.md, coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild, sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/flatcar-linux/coreos-cloudinit/pull/12
and
https://github.com/flatcar-linux/bootengine/pull/30
(https://github.com/flatcar-linux/init/pull/51 is already in)
to also accept Router Advertisements in our default DHCP network
configurations.
None
=> coreos-cloudinit and bootengine: accept IPv6 RA for default net configs

changelog/security/2022-01-27-polkit.md, sys-auth/polkit/files/polkit-0.120-CVE-2021-4034.patch, sys-auth/polkit/polkit-0.119-r2.ebuild
<hr>
To be cherry-picked to:
* flatcar-3066
* flatcar-3127
Related-To: https://github.com/flatcar-linux/Flatcar/issues/606
CI (:large_blue_circle:): http://localhost:9091/job/os/job/manifest/4708/cldsv/
=> sys-auth/polkit: backport patch for CVE-4034

profiles/coreos/base/package.accept_keywords
this is required to pull recent versions of vim which fix CVEs.
<hr>
* no changelog required
* to be merged with: https://github.com/flatcar-linux/portage-stable/pull/284
=> profiles/base: stabilize vim

coreos-base/update_engine/update_engine-9999.ebuild
This pulls in
https://github.com/flatcar-linux/update_engine/pull/16
to fix a small template error in the cgroup v2 migration notice.
Decide if we want to add this to Stable 3033 which would also pull in the creation of the kured `/run/reboot-required` file
None
=> coreos-base/update_engine: fix flatcar-postinst migration notice

changelog/bugfixes/2022-02-07-networkd-foreign-routes-cilium.md, sys-apps/systemd/files/0001-networkd-disable-managing-of-foreign-routes-rules-by-default.patch, sys-apps/systemd/systemd-9999.ebuild
This new downstream patch disables the ManageForeignRoutes and
ManageForeignRoutingPolicyRules systemd-netword settings by default to
ensure that CNIs don't get their routes or routing policy rules
discarded on network reconfiguration events.
https://github.com/flatcar-linux/Flatcar/issues/620
Also port to Stable, maybe while also bumping to the latest systemd point release.
Needs coordination with the systemd 250 update PR to ensure this doesn't get lost.
Manually tested turning one of the bonded interfaces down and it worked well
=> sys-apps/systemd: add downstream patch to disable foreign route mgmt

sys-auth/polkit/polkit-0.120-r2.ebuild
this option is superseeds by `js_engine` which defaults to duktape.
<hr>
* no changelog required
* tested via https://github.com/flatcar-linux/portage-stable/pull/285
* to be merged with: https://github.com/flatcar-linux/portage-stable/pull/285
=> sys-auth/polkit: remove `-Dwith-duktape`

changelog/changes/2022-02-15-auditd.md, sys-process/audit/audit-3.0.6.ebuild, sys-process/audit/files/audit-rules.tmpfiles
This includes the `auditd` binary and systemd unit as part of the
distro. While journald is also able to handle logs from the linux audit
subsystem, auditd provides audit-specific capabilities that are
necessary in deployments subject to regulatory compliance.
For one, an administrator is able to configure audit log writing policy
to ensure that logs land on disk and nothing is missed (`flush`). We
wouldn't want such policy through journald as it woudl sync and ensure
all logs which might be undesirable and too resource intensive. In
short, this allows us to configure different management policies for
audit logs compared to general logs.
It allows us to explicitly configure the node's reaction to errors such
as the disk beign full, the disk having other issues or space constraints.
While …
=> Add auditd package and systemd unit

profiles/coreos/base/package.use, profiles/coreos/targets/generic/package.use
SDK bootstrap is failing with:
Message: sbat-distro (from ID):
../systemd-stable-250.3/src/boot/efi/meson.build:189:24: ERROR: Problem encountered: Required sbat-distro option not set and autodetection failed
The gnuefi USE flag controls whether bootctl and systemd-boot are built, but we
only need those on the target. Currently the USE flag is set for SDK as well,
so move it to coreos/targets/generic.
Rebootstrap.
CI started: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4861/
=> profiles/coreos: move gnuefi systemd USE flag to target

profiles/coreos/targets/generic/make.defaults
In this PR, we add `/usr/bin/sqlite3` to `INSTALL_MASK` in order to skip `sqlite3` cli installation.
- CI (:large_blue_circle:): http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4888/cldsv/
- Not sure we need a changelog entry since sqlite3 has not been introduced yet in an alpha release.
=> dev-db/sqlite: skip `sqlite3` installation

sys-apps/baselayout/baselayout-9999.ebuild
This pulls in
https://github.com/flatcar-linux/baselayout/pull/23
to remove user entries which get safely	created through 
https://github.com/flatcar-linux/scripts/pull/227 
using the acct-user ID allocations for systemd-sysusers.
Only with https://github.com/flatcar-linux/scripts/pull/227
=> sys-apps/baselayout: remove duplicates of acct-user|group

sys-kernel/bootengine/bootengine-9999.ebuild
Bump `CROS_WORKON` to include https://github.com/flatcar-linux/bootengine/pull/36 to fix an issue with dracut in containerised builds.
This fix should be cherry-picked to all active maintenance branches, i.e. `flatcar-3033`, `flatcar-3066`, and `flatcar-3139`.
=> sys-kernel/bootengine: fix containerised builds

changelog/bugfixes/2022-02-16-ignition-udev-race.md, sys-apps/ignition/ignition-9999.ebuild
This pulls in
https://github.com/flatcar-linux/ignition/pull/35
to prevent boot failures such as fsck running while udev was still
processing the disk changes, and thus failing when the /dev/disk/
symlink is shortly gone.
Change to referencing the merge commit before merging this here
Port to all channels
For Stable this also means to pick https://github.com/flatcar-linux/coreos-overlay/pull/1412 and https://github.com/flatcar-linux/coreos-overlay/pull/1453
See linked PR
=> sys-apps/ignition: prevent races with udev

coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild, sys-auth/polkit/polkit-0.120-r2.ebuild
* mark sys-boot/shim as amd64 only dependency (the package doesn't build for arm64)
* polkit dependency on duktape needs to be stricter when using binpkgs
CI running.
=> build fixes (shim/polkit)

profiles/coreos/arm64/package.accept_keywords
Needs to be merged together with https://github.com/flatcar-linux/portage-stable/pull/299.
CI: http://localhost:9091/job/os/job/manifest/4960/cldsv/
=> Accept keyword cleanup for packages from 2015

coreos-base/oem-azure-pro/files/grub.cfg, coreos-base/oem-azure/files/grub.cfg
Both architectures and VM generations.
CI running
=> core-base/oem-azure(-pro): enable earlycon on all platforms

changelog/bugfixes/2022-03-02-kernel-ipsec-id0-revert.md, sys-kernel/coreos-sources/coreos-sources-5.15.25.ebuild, sys-kernel/coreos-sources/files/5.15/z0005-Revert-xfrm-state-and-policy-should-fail-if-XFRMA_IF.patch
The changes broke userspace (e.g., Cilium is affected because it used
id 0 for the dummy state https://github.com/cilium/cilium/pull/18789)
and we decided to revert them to give the affected software more time
to adapt (cf. https://marc.info/?t=164607426900002&r=1&w=2).
Test that, e.g.,
```
sudo ip link add ipsec0  type xfrm dev lo
```
works again.
Backport to all channels
[Ongoing](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5006/cldsv/)
=> sys-kernel: Revert change to forbid using xfrm id 0

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords, profiles/coreos/targets/generic/package.use
Needs to be merged together with https://github.com/flatcar-linux/portage-stable/pull/300.
~Blocked on https://github.com/flatcar-linux/coreos-overlay/pull/1674.~
CI passed: http://localhost:9091/job/os/job/manifest/4965/cldsv/
=> Accept keyword cleanup for packages from 2016

app-emulation/containerd/files/config.toml, changelog/changes/2022-03-08-containerd-selinux.md
This enables containerd to do appropriate SELinux labeling of containers
and files by default. This should not be problematic as Flatcar ships with
SELinux permissive by default.
This was based on the [sample config](https://github.com/containerd/cri/blob/deprecated/master/docs/config.md) provided by containerd
=> containerd: Enable SELinux labeling support by default

changelog/changes/2022-03-09-rngd.md, coreos-base/coreos/coreos-0.0.1.ebuild, profiles/coreos/arm64/package.accept_keywords
rng-tools does not appear to be necessary for booting in virtual machine
environments in 2022. Back in the day the boot process would block if
there was not enough entropy to seed the system random pool, but over
the years the linux kernel made sure that the pool is force seeded if
userspace does not do so one it's own. Remove rng-tool as it is not
needed and it would require work to make sure it works (detection of
tpm/hwrng/intel cpu instructions).
[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]
=> coreos-base/coreos: remove rng-tool dependency

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords, profiles/coreos/targets/generic/package.provided
Usual cleanup of profiles for package updates, 2017 edition.
~Blocked on #1678.~
Needs to be merged together with https://github.com/flatcar-linux/portage-stable/pull/301.
CI: http://localhost:9091/job/os/job/manifest/5080/cldsv/
=> Profile cleanups for updated packages from 2017

changelog/security/2022-03-11-go-1.17.8.md
Add missing security changelog CVE-2022-24921 for Go 1.17.8, done via PR https://github.com/flatcar-linux/coreos-overlay/pull/1697.
=> changelog: add security changelog for Go 1.17.8

sys-apps/ignition/ignition-9999.ebuild
This pulls in https://github.com/flatcar-linux/ignition/pull/38
for https://github.com/flatcar-linux/ign-converter/pull/5
to fix https://github.com/flatcar-linux/Flatcar/issues/666 which
is about a failing translation due to a too strict check.
Check that the following CLC works
```
storage:
files:
- path: /helloworld
links:
- path: /hello
target: /helloworld
```
[test build](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5093/cldsv/) and passing the above config worked. A new [kola test](https://github.com/flatcar-linux/mantle/pull/306) passed, too
↑ Not needed, we didn't release v3 support yet
=> sys-apps/ignition: fix link translation

coreos-base/coreos-init/coreos-init-9999.ebuild, sys-kernel/bootengine/bootengine-9999.ebuild
<hr>
It solves the booting issue on GCP with new version of Ignition.
This pulls:
* https://github.com/flatcar-linux/bootengine/pull/39
* https://github.com/flatcar-linux/init/pull/64
Not released yet - no changelog required.
CI (:large_blue_circle:): http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5069/cldsv/
=> ignition: support `gce` as OEM ID

changelog/bugfixes/2022-03-14-readd-initramfs-kernel-modules.md, sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/flatcar-linux/bootengine/pull/40
to add the kernel modules back that disappeared compared to Stable
3033.x.y with the 5.10 kernel.
Port to beta, alpha - maybe with a bootengine backport branch
[build passed](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5124/cldsv/), and manual checks in https://github.com/flatcar-linux/bootengine/pull/40
=> sys-kernel/bootengine: re-add missing modules

changelog/bugfixes/2022-03-14-kernel-msi-revert.md, sys-kernel/coreos-sources/coreos-sources-5.10.105.ebuild, sys-kernel/coreos-sources/files/5.10/z0006-PCI-MSI-Mask-MSI-X-vectors-only-on-success.patch
We bisected m4 networking failure down to a commit that has already been backported to all stable kernels. Revert the commit while upstream discussions happen.
If the ami from the test run is still around:
```
./bin/kola spawn --aws-type m4.large --board amd64-usr  --aws-iam-profile jenkins-test --platform=aws  --aws-ami=ami-03ecf733c5ca3afeb --aws-region=us-west-2 --verbose --aws-credentials-file ~/.aws/credentials
```
Successfully tested here: http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/aws/1242/tapResults/.
=> sys-kernel/coreos-sources: revert commit which breaks networking on M4 instances

coreos-devel/mantle/mantle-9999.ebuild
We have to update the commit ID now when a mantle PR gets merged
because the new pipeline uses it.
Pick for stable, beta, alpha
`sudo emerge mantle`
=> coreos-devel/mantle: bump to latest commit

profiles/coreos/base/package.use
sssd it being provided by flatcar and it was missing from the list.
This inclusion should appropriately label sssd-related files.
Related-Bug: https://github.com/flatcar-linux/Flatcar/issues/673
[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]
=> Add sssd to list of SELinux modules enabled

changelog/changes/2022-03-22-fips.md, profiles/coreos/base/make.defaults, profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.use
FIPS features will be enabled for OpenSSL and Cryptsetup.
<hr>
Closes: https://github.com/flatcar-linux/Flatcar/issues/537
=> profiles/base: enable `fips` across the OS

eclass/coreos-go.eclass
The size contains not only of the /usr partition but also the /boot
partition require that we reduce the size of binaries as much as
possible.
Strip all Go binaries by default.
check that tests pass and that it actually reduced the image size and vmlinuz size
[onging](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5220/cldsv/)
↑ not needed I think
=> eclass/coreos-go.eclass: strip Go binaries by default

.github/workflows/setup-flatcar-sdk.sh
Our github actions use cork to create an sdk chroot, which pulls down bzipped
archives. The runners have 2 CPUs, so this unpacking could be faster if we
installed lbzip2. Cork transparently uses lbzip2.
[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]
=> .github/workflows: install lbzip2 to speed up sdk creation

profiles/coreos/base/package.use
As `sys-apps/shadow` has its own su binary, `sys-apps/util-linux` should not have its own su binary. Otherwise, build will simply fail.
Disable su USE flag for util-linux.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/310.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5192/cldsv
- Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) (see https://github.com/flatcar-linux/portage-stable/pull/310)
=> profiles: disable su USE flag for util-linux

.github/workflows/mantle-releases-main.yml
This action runs over main and the release branches and creates a PR that
updates mantle reference to the latest one. By using a fixed branch name,
rerunning the action will update/close an existing PR if new mantle commits
happen or if the PR becomes obsolete.
Wait until merged, and then it will run automatically on each commit or use workflow_dispatch.
Tested here: https://github.com/jepio/coreos-overlay
See this PR: https://github.com/jepio/coreos-overlay/pull/3.
=> github/workflows: add mantle update action

sys-kernel/coreos-sources/coreos-sources-5.15.32.ebuild, sys-kernel/coreos-sources/files/5.15/z0006-Drivers-hv-vmbus-Propagate-VMbus-coherence-to-each-V.patch, sys-kernel/coreos-sources/files/5.15/z0007-PCI-hv-Propagate-coherence-from-VMbus-device-to-PCI-.patch
Backport two patches that fix issues in determining whether a device is coherent with respect to the CPU under Hyper-V.
Source is https://lore.kernel.org/lkml/1648138492-2191-1-git-send-email-mikelley@microsoft.com/T/#u, they are scheduled for 5.18.
```
emerge-amd64-usr coreos-sources coreos-kernel coreos-modules
./build_image --board=amd64-usr
```
Testing passed here: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5236/cldsv/, only Azure is affected by these patches.
=> coreos-sources: backport hyperv coherence fixes

profiles/coreos/base/package.accept_keywords
As we update gnutls to 3.7.3-r1 which is already stable, there is no need to accept keywords for gnutls.
Delete.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/315.
- Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) (see https://github.com/flatcar-linux/portage-stable/pull/315)
=> profiles: delete keywords for gnutls

changelog/changes/2022-03-22-fips.md, profiles/coreos/base/make.defaults, profiles/coreos/base/package.use
see https://github.com/flatcar-linux/coreos-overlay/pull/1778
Merge with https://github.com/flatcar-linux/portage-stable/pull/317
[Done](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5294/), failures seem unrelated
=> Backport FIPS support for 3185

.github/workflows/common.sh, .github/workflows/rust-apply-patch.sh, .github/workflows/rust-release-main.yml, virtual/rust/metadata.xml, virtual/rust/rust-1.59.0.ebuild
See https://github.com/flatcar-linux/portage-stable/pull/313 for details. This PR updates the workflow to also update the imported virtual/rust package too.
Should be merged together with https://github.com/flatcar-linux/portage-stable/pull/313.
CI: http://localhost:9091/job/os/job/manifest/5241/cldsv/
=> Import virtual/rust to from portage-stable and update the rust workflow

profiles/coreos/base/package.accept_keywords
To be merged with https://github.com/flatcar-linux/portage-stable/pull/319
CI Passed http://jenkins.infra.kinvolk.io:8080/job/os/job/board/job/packages-matrix/8698/cldsv/
=> sys-libs/zlib: Add arches to package.accept_keywords

changelog/bugfixes/2022-04-12-skip-ensure-sysext.md, coreos-base/coreos-init/coreos-init-9999.ebuild, sys-apps/systemd/CHECKLIST.md
This pulls in https://github.com/flatcar-linux/init/pull/68 to skip
the ensure-sysext unit when systemd-sysext is skipped to prevent a
dependency failure being reported.
Closes: https://github.com/flatcar-linux/Flatcar/issues/710
backport to flatcar-3185 and -3200
Booted the built image and checked that `ensure-sysext.service was skipped because all trigger condition checks failed`
=> coreos-base/coreos-init: skip ensure-sysext unit

changelog/changes/2022-04-13-hostname-setup-with-afterburn.md, sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in https://github.com/flatcar-linux/bootengine/pull/43
to remove the afterburn /etc/hostname setup for EC2 and align the
afterburn /etc/hostname setup with upstream.
Test that the EC2 hostname gets set as expected, check that the DigitalOcean and Packet hostnames get set as expected
=> sys-kernel/bootengine: rework afterburn hostname setup

profiles/coreos/arm64/package.accept_keywords
Accept keywords ~arm64 for app-arch/libarchive 3.6.1.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/322.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5410/cldsv/
- Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) (see https://github.com/flatcar-linux/portage-stable/pull/322)
=> profiles: accept keywords ~arm64 for app-arch/libarchive 3.6.1

changelog/bugfixes/2022-04-14-systemd-sysext-oem-mount.md, coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in https://github.com/flatcar-linux/init/pull/69
to restore the OEM partition mount point after the /usr overlay is
done.
backport to flatcar-3185 and -3200
Tested with https://github.com/flatcar-linux/mantle/pull/324 (`/mantle/branch-builder/PR-324` and `systemd.sysext.simple`)
- Successfully tested on [qemu, gce, vmware esx, and azure](http://192.168.42.7:8080/job/os/job/manifest/5426/cldsv/) (a new build was started to test after rebasing) and manually as mentioned in the other PR
=> coreos-base/coreos-init: add systemd-sysext.service for OEM mount

changelog/bugfixes/2022-04-25-fix-dev-container-module-builds.md, coreos-base/coreos-dev/coreos-dev-0.1.0.ebuild, eclass/coreos-kernel.eclass, sys-kernel/coreos-sources/coreos-sources-5.15.35.ebuild
pahole is a build-time dependency of our kernel build, due to us setting
CONFIG_BTF_DEBUG_INFO. If pahole is missing, a `make modules_prepare` with our
kernel config results in symbols in the config changing. This will affect
people building kernel modules against coreos-sources in the developer
container, but not the SDK because pahole is already in sdk-depends.
Test the resulting developer container with nvidia.service on a GPU instance (e.g. NC6s_v3 in EastUS).
Modified this line: https://github.com/flatcar-linux/coreos-overlay/blob/main/x11-drivers/nvidia-drivers/files/bin/install-nvidia#L7 to be `emerge -gkv pahole coreos-sources` and verified that this allows the built modules to be probed. Without this, the module fails to load with this error message "module: x86/modules: Skipping …
=> Add missing pahole dependencies

coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild
The removal of the mantle ebuild file also meant that dnsmasq isn't
installed into the SDK anymore, yet we actually need it to run kola
QEMU tests in the SDK on the original CI pipeline. As long as the
original CI pipeline is kept, we have to keep kola's dependencies
like QEMU and dnsmasq around.
Build an SDK and run the kola tests from it with the original pipeline.
When merged this should fix the nightly failure.
Backport to all channels (incl 2605, 3033)
[here](http://192.168.42.7:8080/job/os/job/manifest/5509/cldsv/)
=> Move mantle's dnsmasq dependency to the SDK dependencies

.github/workflows/cacerts-releases-lts.yml, .github/workflows/kernel-releases-lts.yml
The GitHub Actions were defined for the LTS stream directly but we can
now follow the approach used for the other channels. This means that
in the future we could decide to create new Actions for 2022 by copying
the current one and modifying it when 2023 gets the new current LTS -
anyway some manual work would be required to set up Actions for both
old and new at the same time (we have no "previous" symlink on Origin).
We could retire the old LTS Actions immediately because the releases
don't occur on a fixed schedule but I think the automation is nice to
keep.
Merge when LTS 2022 is released
=> .github: add cacerts/kernel actions for current LTS

profiles/coreos/base/package.accept_keywords
We need to build 2.35.3 to address [CVE-2022-24765](https://nvd.nist.gov/vuln/detail/CVE-2022-24765).
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/325.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5571/cldsv/
- Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) (see https://github.com/flatcar-linux/portage-stable/pull/325)
=> profiles: accept keywords for git 2.35.3

profiles/coreos/base/package.accept_keywords
We need to allow `net-misc/rsync` 3.2.4-r1, to address security issues in its bundled zlib.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/326.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5572/cldsv/
- Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) (see https://github.com/flatcar-linux/portage-stable/pull/326)
=> profiles: accept keywords for net-misc/rsync

profiles/coreos/base/package.accept_keywords
Crossdev currently uses binutils 2.36 (stable), while the SDK and sysroot both
build binutils 2.37 due to keywording. Kernel modules built within the
developer container fail to load due to relocation errors. Add the same
keywords to cross-*/binutils packages so that the versions match.
Perform at least a stage4 bootstrap with sdk-new. Doesn't affect update_chroot because that prefers binpkgs in all cases.
Still testing in CI.
=> profiles: add keywords to cross-*/binutils as well

changelog/bugfixes/2022-05-11-create-etc-flatcar-update.conf.md, coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/flatcar-linux/init/pull/71
to create /etc/flatcar/update.conf if missing.
Backport to all channels (may need to use the init backport branches)
Checked the the built image doesn't have the file but it gets created on first boot and any other boot if it doesn't exist. Also checked that writing `/etc/coreos/update.conf` with Ignition will populate this file.
=> coreos-base/coreos-init: Ensure /etc/flatcar/update.conf exists

changelog/bugfixes/2022-05-22-bootengine.md, sys-kernel/bootengine/bootengine-9999.ebuild
this pulls:
* https://github.com/flatcar-linux/bootengine/pull/45
<hr>
On Matrix, we got a report of a user unable to boot Flatcar with Ignition on a bare metal setup. By default `pxe` is set by `ignition-generator` but with recent Ignition upgrade, we need to update `pxe` to `metal`.
Not sure how we could test this except manually :thinking: it has been confirmed on Matrix that `flatcar.oem.id=metal` fixes the issue.
TODO: Backport on : 
* flatcar-3227
* flatcar-3185
=> sys-kernel/bootengine: bump commit ID

profiles/coreos/arm64/package.accept_keywords
To be able to build curl 7.83.1 for arm64, we need to accept keywords for `~arm64`.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/330.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5663/cldsv/
- Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) (see https://github.com/flatcar-linux/portage-stable/pull/330)
=> profiles: accept keywords ~arm64 for curl 7.83.1

changelog/bugfixes/2022-05-22-ignition-networkd.md, sys-apps/ignition/files/0017-mod-update-ign-converter.patch, sys-apps/ignition/ignition-9999.ebuild
this pulls networkd conversion support. (https://github.com/flatcar-linux/ign-converter/pull/6)
<hr>
- closes: https://github.com/flatcar-linux/Flatcar/issues/741
- To be tested with: https://github.com/flatcar-linux/mantle/pull/334
To be backported on:
* flatcar-3185
* flatcar-3227
=> sys-apps/ignition: upgrade ign-converter dependency

changelog/changes/2022-05-12-bootengine.md, sys-kernel/bootengine/bootengine-9999.ebuild
<hr>
This pulls the following PR:
* https://github.com/flatcar-linux/bootengine/pull/44
To be tested with:
* https://github.com/flatcar-linux/mantle/pull/329
Closes: https://github.com/flatcar-linux/Flatcar/issues/717
=> sys-kernel/bootengine: pull network kargs

changelog/bugfixes/2022-05-23-gcp-shutdown.md, coreos-base/oem-gce/files/units/oem-gce.service
In the [`init.sh`](https://github.com/flatcar-linux/coreos-overlay/blob/main/coreos-base/coreos-oem-gce/files/manglefs.sh) of the OEM GCE container, we have the following
section:
```bash
wait -n "${daemon_pids[@]}" || :
kill "${daemon_pids[@]}" || :
test -n "$stopping" || exit 1
exec /usr/bin/google_metadata_script_runner --script-type shutdown
```
`shutdown` script was not executed because container was receiving a
`SIGKILL`, the started processes was not properly terminated.
According to the `systemd-nspawn` manual:
```bash
If --boot is not used and this option is not specified
the container's processes are terminated abruptly via SIGKILL
```
<hr>
Added a `shutdown-script` to the GCP metadata server, edited the `oem-gce` to …
=> coreos-base/oem-gce: bring back shutdown scripts

coreos-base/coreos/coreos-0.0.1.ebuild, profiles/coreos/base/make.defaults, profiles/coreos/base/package.accept_keywords
Add `sys-power/acpid` to the explicit list of Flatcar's packages.
- CI(:green_heart:): http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5710/cldsv/
<hr>
Closes: https://github.com/flatcar-linux/Flatcar/issues/738
changelog in `::portage-stable`
=> sys-power/acpid: new package

profiles/coreos/base/package.accept_keywords
Now that `dev-libs/libxml2` 2.9.14 is stable, we do not need to accept keywords for that.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/333.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5814/cldsv/
-  Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) (see https://github.com/flatcar-linux/portage-stable/pull/333)
=> profiles: delete libxml2 keywords

changelog/changes/2022-06-10-arm64-cifsutils-realmd-sssd-adcli-gotspi.md, coreos-base/coreos/coreos-0.0.1.ebuild, profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
This change adds multiple tools to ARM64 which were formerly only
present in the X86-64 image.
Added for ARM64:
net-fs/cifs-utils
sys-auth/realmd
sys-auth/sssd
app-admin/adcli
app-crypt/go-tspi
This leaves only the xenserver-pv-version and xenstore packages exclusively on X86-64.
The change un-masks keywords `amd64` and `arm64` for `sys-libs/liburing-2.1-r2` and keyword `arm64` for `dev-libs/ding-libs-0.6.1-r1`, overwriting Gentoo upstream defaults in portage-stable.
Partially fixes https://github.com/flatcar-linux/Flatcar/issues/689.
Fixes https://github.com/flatcar-linux/Flatcar/issues/690.
Requires https://github.com/flatcar-linux/portage-stable/pull/334 .
Check out branch. Build the image.
```shell
./run_sdk_container -t 
./ build_packages --board=arm64-usr
./build_image …
```
=> Add ARM64 support for cifs-utils, realmd, sssd, adcli, go-tspi

changelog/changes/2022-06-10-arm64-cifsutils-realmd-sssd-adcli-gotspi.md, coreos-base/coreos/coreos-0.0.1.ebuild, profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
Back-port / cherry-pick of https://github.com/flatcar-linux/coreos-overlay/pull/1954 for flatcar-3227.
Requires https://github.com/flatcar-linux/portage-stable/pull/336.
Fixes https://github.com/flatcar-linux/Flatcar/issues/775.
This change adds multiple tools to ARM64 which were formerly only
present in the X86-64 image.
Added for ARM64:
net-fs/cifs-utils
sys-auth/realmd
app-admin/adcli
app-crypt/go-tspi
The change un-masks keywords amd64 and arm64 for sys-libs/liburing-2.1-r2 and keyword arm64 for dev-libs/ding-libs-0.6.1-r1, overwriting Gentoo upstream defaults in portage-stable.
Check out branch flatcar-3227. Build the image. Run the image, check for sssd.
```shell
./checkout flatcar-3227
./run_sdk_container -t 
./ build_packages --board=arm64-usr
./build_image --board=arm64-usr …
```
=> backport arm64 sssd and other tools to flatcar 3227

changelog/bugfixes/2022-06-30-remove-outdated-lts-motd.md, coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/flatcar-linux/init/pull/75
to update the LTS info that is printed on login.
To be backported to 3033 (and 2605 if possible)
=> coreos-base/coreos-init: Remove outdated LTS motd information

x11-drivers/nvidia-drivers/files/bin/install-nvidia, x11-drivers/nvidia-drivers/files/bin/setup-nvidia
This PR includes several enhancements to the setup-nvidia/install-nvidia scripts that we ship to build
Nvidia kernel modules on system. They include:
* faster decompression
* build against /lib/modules, not /usr/src/linux (skip emerging things)
* sysext compatible file layout (for potential future use)
* allow service to rerun after reboot and only load modules
* allow service to work after upgrades
* allow user to override driver version (TODO: add GPU docs flatcar-docs)
Build image and test on Azure Standard_NC6 or Standard_NC6s_v3 instances in EastUS.
Tested according to "how-to-use", would appreciate testing on other platforms.
=> nvidia driver build improvements

profiles/coreos/base/package.accept_keywords
Sync with Gentoo upstream to address the CVE, CVE-2022-27239, CVE-2022-29869
To be merged with https://github.com/flatcar-linux/portage-stable/pull/342
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5953/cldsv/
=> net-fs/cifs-utils: Add the package.accept_keywords for cifs-utils

changelog/bugfixes/2022-07-13-ignition-kargs.md, sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/flatcar-linux/bootengine/pull/47
which creates the grub.cfg file if it does not exist when the Ignition
kargs directive is used, preventing an error when it tried to read the
current settings from it.
Can be backported when using bootengine branches
see PR
=> sys-kernel/bootengine: Fix ignition kargs support by creating grub.cfg

profiles/coreos/arm64/package.accept_keywords
To be merged with https://github.com/flatcar-linux/portage-stable/pull/343
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/6065/cldsv/
=> profiles: remove outdated arm64 accept_keywords for curl

changelog/changes/2022-07-19-ncat.md, profiles/coreos/base/package.use
For compatiblity, it's good to have `nc` in the PATH too.
<hr>
See: https://github.com/flatcar-linux/portage-stable/pull/345
=> profiles: enable symlink for nmap

changelog/bugfixes/2022-07-26-restore-resolv-conf.md, sys-apps/systemd/systemd-250.3-r1.ebuild, sys-apps/systemd/systemd-250.3.ebuild
Our ebuild modifies the systemd owned tmpfiles.d entry that creates the
/etc/resolv.conf symlink to point to resolv.conf instead of stub-resolv.conf.
The file that contains that entry changed from etc.conf.in to
systemd-resolve.conf, so update the ebuild to touch that file.
Added new kola test: https://github.com/flatcar-linux/mantle/pull/346 which fails on main and succeeds on this branch.
=> sys-apps/systemd: fix tmpfile entry for resolv.conf link

coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
Otherwise it's not pulled in the SDK
<hr>
CI running (with SDK): http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/6188/cldsv/
=> coreos-base/hard-host-depends: add syft

changelog/bugfixes/2022-07-27-networkd.md, coreos-base/coreos-init/coreos-init-9999.ebuild
this pulls: https://github.com/flatcar-linux/init/pull/77
<hr>
- Closes: https://github.com/flatcar-linux/Flatcar/issues/808
=> coreos-base/init: keep static network configuration

sys-kernel/coreos-sources/coreos-sources-5.15.58.ebuild, sys-kernel/coreos-sources/files/5.15/z0001-kbuild-derive-relative-path-for-srctree-from-CURDIR.patch, sys-kernel/coreos-sources/files/5.15/z0002-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch, sys-kernel/coreos-sources/files/5.15/z0003-PCI-hv-Make-the-code-arch-neutral-by-adding-arch-spe.patch, sys-kernel/coreos-sources/files/5.15/z0004-PCI-hv-Add-arm64-Hyper-V-vPCI-support.patch, sys-kernel/coreos-sources/files/5.15/z0005-Drivers-hv-vmbus-Propagate-VMbus-coherence-to-each-V.patch, sys-kernel/coreos-sources/files/5.15/z0006-PCI-hv-Avoid-the-retarget-interrupt-hypercall-in-irq.patch, sys-kernel/coreos-sources/files/5.15/z0007-PCI-hv-Remove-unused-hv_set_msi_entry_from_desc.patch
The first hyperv patch needed a regeneration, while the last one could
be dropped as it was already backported to 5.15.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/80/cldsv/
CC: @jepio
=> sys-kernel/coreos-sources: Regenerate patches

changelog/bugfixes/2022-08-03-cloudinit.md, changelog/bugfixes/2022-08-03-systemd-networkd.md, coreos-base/coreos-init/coreos-init-9999.ebuild
<hr>
This pulls:
* https://github.com/flatcar-linux/init/pull/78
* https://github.com/flatcar-linux/init/pull/76
=> coreos-base/coreos-init: bump commit ID

profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.unmask
To be able to address [CVE-2022-29187](https://nvd.nist.gov/vuln/detail/CVE-2022-29187), we need to accept keywords and unmask `dev-vcs/gi`t 2.37.1.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/347.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/6285/cldsv/
- Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) (done in https://github.com/flatcar-linux/portage-stable/pull/347)
=> profiles: enable dev-vcs/git 2.37.1

changelog/changes/2022-08-11-new-image-signing-subkey.md, coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/flatcar-linux/init/pull/79
to updated the embedded pub key in flatcar-install to include the new
subkey that is used for signing new releases.
Backport together with backport branches in "init"
=> coreos-base/coreos-init: Add new image signing key to flatcar-install

profiles/coreos/amd64/generic/package.use, profiles/coreos/arm64/generic/package.use, profiles/coreos/base/package.accept_keywords, profiles/coreos/targets/generic/make.defaults
To be merged with https://github.com/flatcar-linux/portage-stable/pull/344
~Jenkins CI running: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/6101/cldsv/~
=> app-editors/vim,vim-core: Add accept_keywords for vim & vim-core

profiles/coreos/base/profile.bashrc, profiles/coreos/base/profile.bashrc.slsa-provenance
Add post install hooks to capture provenance metadata for every built package. The hooks are sourced by default by every package built with the coreos/base profile (or inheriting from it), but enabled only when GENERATE_SLSA_PROVENANCE=true is defined. This is intended to be enabled for board packages (including toolchains).
The hooks need access to some metadata beyond what is available in the temporary build directory: hashes of commits of scripts/coreos-overlay/portage-stable and sdk version currently in use.
Together with https://github.com/flatcar-linux/scripts/pull/378, build a full image including toolchains.
http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/6068/cldsv/
=> Record SLSA provenance data

.github/workflows/mirror-calico.yml
The https://docs.projectcalico.org/manifests/tigera-operator.yaml link we used so far returns 404.
=> .github: find latest calico tag from tigera operator using github API

changelog/bugfixes/2022-08-22-eks-support-for-versions-above-1.21.md, coreos-base/flatcar-eks/files/download-kubelet.sh
When an EC2 instance boots up with a flatcar image (even the latest) the kubelet fails.
The userdata defines (and should do so) that the `/etc/eks/bootstrap.sh` should run, which it does.
This seems to add a ExecStartPre to the kubelet.service:
`ExecStartPre=/usr/share/oem/eks/download-kubelet.sh`
Both the `bootstrap.sh` and the `download-kubelet.sh` are consistent with:
https://github.com/flatcar-linux/coreos-overlay/blob/main/coreos-base/flatcar-eks/files/bootstrap.sh
https://github.com/flatcar-linux/coreos-overlay/blob/main/coreos-base/flatcar-eks/files/download-kubelet.sh
The `download-kubelet.sh` fails with `Unsupported Kubernetes version` because in the case statement on line 24->50 (https://github.com/flatcar-linux/coreos-overlay/blob/main/coreos-base/flatcar-eks/files/download-kube …
=> Flatcar support for EKS on versions above 1.21

changelog/bugfixes/2022-08-29-vmware-wireguard.md, coreos-base/coreos-init/coreos-init-9999.ebuild
this pulls the wireguard exclusion from systemd-networkd management on VMWare to sync configuration file with `zz-default`. 
<hr>
Related PRs:
- https://github.com/flatcar-linux/mantle/pull/361
- https://github.com/flatcar-linux/init/pull/80
- https://github.com/flatcar-linux/Flatcar/issues/808
=> coreos-base/coreos-init: sync commit ID

changelog/bugfixes/2022-08-30-equinix-metal-serial.md, coreos-base/oem-packet/files/grub.cfg
The m3.small.x86 instance type had no serial console output because
ttyS0 was used because the GRUB CPU check didn't trigger. It seems that
most instances had i386 reported but this new one not (maybe EFI is
used here?).
Extend the GRUB check to cover both i386 and x86_64 when setting up the
serial console. For arm64 this still shouldn't be needed and the
defaults worked so far.
Test again on other instance types that the serial console works as expected.
Backport
On m3.small, c3.medium, s3.xlarge
=> coreos-base/oem-packet: Use i386 serial settings for x86_64 to fix m3

profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.use
To address [CVE-2022-29154](https://nvd.nist.gov/vuln/detail/CVE-2022-29154), we need to accept keywords `~amd64` and `~arm64` for rsync 3.2.6.
Since rsync 3.2.4, IUSE_CPU_FLAGS_X86="sse2" does not exist any more in upstream ebuilds.
So it is not necessary to disable `cpu_flags_x86_sse2` USE flag for avoiding cross toolchain build failures.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/356.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/304/cldsv/
=> profiles: accept keywords and clean up for rsync 3.2.6

.github/workflows/cacerts-apply-patch.sh, .github/workflows/cacerts-releases-alpha.yml, .github/workflows/cacerts-releases-beta.yml, .github/workflows/cacerts-releases-lts-2021.yml, .github/workflows/cacerts-releases-lts.yml, .github/workflows/cacerts-releases-main.yaml, .github/workflows/cacerts-releases-stable.yml, .github/workflows/common.sh, .github/workflows/containerd-apply-patch.sh, .github/workflows/containerd-releases-main.yml, .github/workflows/docker-apply-patch.sh, .github/workflows/docker-releases-main.yml, .github/workflows/firmware-apply-patch.sh, .github/workflows/firmware-releases-main.yml, .github/workflows/go-apply-patch.sh, .github/workflows/go-releases-main.yml, .github/workflows/kernel-apply-patch.sh, .github/workflows/kernel-releases-alpha.yml, .github/workflows/kernel-releases-beta.yml, .github/workflows/kernel-releases-lts-2021.yml, .github/workflows/kernel-releases-lts.yml, .github/workflows/kernel-releases-main.yml, .github/workflows/kernel-releases-stable.yml, .github/workflows/runc-apply-patch.sh, .github/workflows/runc-releases-main.yml, .github/workflows/rust-apply-patch.sh, .github/workflows/rust-release-main.yml, .github/workflows/setup-flatcar-sdk.sh, .github/workflows/vmware-apply-patch.sh, .github/workflows/vmware-releases-main.yml
Now that Flatcar SDK does not support cork of mantle any more, we need to migrate the Github Actions of coreos-overlay to the new container SDK based approach.
Simply download a container image of the latest Flatcar release, run the container, generate patches from there.
Note, since the Flatcar scripts repo of LTS-2021 still does not have necessary Container SDK scripts like run_sdk_container, we need to skip checking out a specific base branch in case of LTS-2021.
Fixes https://github.com/flatcar-linux/Flatcar/issues/844
tested almost all
=> .github: migrate to SDK container based Github Actions

changelog/bugfixes/2022-09-13-gettext.md, changelog/updates/2022-09-13-gettext.md, coreos-base/coreos/coreos-0.0.1.ebuild
This Flatcar dependency needs to be now explicitly pulled in the OS since this commit: https://github.com/flatcar-linux/coreos-overlay/pull/1724/commits/4a06200e9d92dc8066425cfc18dd6b7c5aa99131
<hr>
```
14:05:51  +/usr/bin/envsubst
...
14:05:51  +/usr/bin/gettext
14:05:51  +/usr/bin/gettext.sh
14:05:51  +/usr/bin/gettextize
```
Closes: https://github.com/flatcar-linux/Flatcar/issues/849
=> coreos-base/coreos: add sys-devel/gettext

sys-apps/ignition/ignition-9999.ebuild
This pulls in https://github.com/flatcar/ignition/pull/40 to update the package name after the github org move.
none, I would say we only start the test build after all changes are prepared, it won't work otherwise
=> sys-apps/ignition: Use renamed package name

.github/workflows/common.sh, .github/workflows/go-apply-patch.sh
Recently Go Github Actions started not creating changelog at all.
Add the missing code to the go-apply-patch to correctly generate changelog.
If `git show-ref` returns an error, i.e. the branch already exists, then we should not create a pull request, but simply return error.
Otherwise, the Github Actions would always try to create pull requests even when the branch still exists.
Done
=> .github: fix Go changelog and git show-ref bug

changelog/changes/2022-09-30-kernel-strip.md, sys-kernel/coreos-modules/coreos-modules-5.15.70.ebuild
With `--strip-unneeded` some static symbols are also stripped from modules, making stacktraces incomplete, and making it harder to debug kernel issues. Switch to the default setting of `--strip-debug`, which keeps symbols intact and does not appear to lead to a measurable size increase of the /usr partition.
`emerge-amd64-usr coreos-modules coreos-kernel`
Booted image and checked:
```
$ grep kjournald /proc/kallsyms
0000000000000000 t kjournald2   [jbd2]
```
=> sys-kernel/coreos-module: use strip-debug instead of strip-unneeded

coreos/config/env/net-misc/curl, profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.unmask
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/306/
Needs to be merged together with https://github.com/flatcar/portage-stable/pull/366.
=> Profiles and environment overrides for packages refresh

changelog/updates/2022-10-10-go-update.md
Merged #2208, but forgot to add the security changelog.
=> changelog: Add an entry for go 1.18.7 update

coreos-base/coreos-init/coreos-init-9999.ebuild
Signed-off-by: Sayan Chowdhury <schowdhury@microsoft.com>
Jenkins CI Running. http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/327/
=> motd: Update the motd to notify about the deprecating LTS-2021

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.use
Needs to be merged together with https://github.com/flatcar/portage-stable/pull/368.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/321/cldsv
Nothing to changelog here.
Nothing interesting in image differences.
=> Profile changes for weekly package updates

profiles/coreos/amd64/sdk/package.accept_keywords, profiles/coreos/base/package.accept_keywords
- Adds accept keywords for libxml2, zlib and cmake.
- Drops accept keywords for git.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/337/cldsv
This is for https://github.com/flatcar/portage-stable/pull/371.
For changelog and differences, see portage-stable PR.
=> Profile changes for the weekly updates

changelog/security/2022-10-20-curl-update.md, changelog/updates/2022-10-20-curl-update.md, profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.use
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/339/cldsv
Nothing stands out: [amd64](http://jenkins.infra.kinvolk.io:8080/job/container/job/image_changes/364/console), [arm64](http://jenkins.infra.kinvolk.io:8080/job/container/job/image_changes/363/console)
=> profiles: Accept keywords for curl 7.85

changelog/changes/2022-10-19-openstack-metadata.md, coreos-base/oem-ec2-compat/files/base/openstack.ign, coreos-base/oem-ec2-compat/oem-ec2-compat-0.1.2-r2.ebuild
In this PR, we're enabling the `coreos-metadata-sshkeys@.service` for the OpenStack image in order to pull SSH keys from the OpenStack metadata server if no user configuration is provided.
Boot an instance on OpenStack without Ignition provided SSH keys. 
Manually tested with https://github.com/flatcar/mantle/pull/388
<hr>
Should fix: https://github.com/flatcar/Flatcar/issues/817
=> coreos-base/oem-ec2-compat: pull ssh keys from metadata server

profiles/coreos/arm64/parent
This solves several USE flag mismatches between arm64 and amd64 images. Most important changes are bzip2 and acl support in several packages, as well as hardening in GCC.
Exact impact will be determined through CI.
Rebuild board.
Needs a CI run.
=> profile/coreos/arm64: switch parent profile to 17.0/hardened

app-admin/toolbox/toolbox-9999.ebuild, changelog/changes/2022-10-27-toolbox.md
This pulls in
https://github.com/flatcar/toolbox/pull/7
to download and mount the image with containerd instead of requiring Docker.
Tested manually
=> app-admin/toolbox: Use containerd

profiles/coreos/base/package.accept_keywords
Accept keywords `~amd64`, `~arm64` for `sys-fs/multipath-tools` 0.9.3 to address [CVE-2022-41973](https://nvd.nist.gov/vuln/detail/CVE-2022-41973), [CVE-2022-41974](https://nvd.nist.gov/vuln/detail/CVE-2022-41974).
This PR should be merged together with https://github.com/flatcar/portage-stable/pull/381.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/668/cldsv/
=> profiles: accept keywords for multipath-tools 0.9.3

.github/workflows/containerd-apply-patch.sh, .github/workflows/containerd-releases-main.yml, .github/workflows/docker-apply-patch.sh, .github/workflows/docker-releases-main.yml, .github/workflows/firmware-apply-patch.sh, .github/workflows/firmware-releases-main.yml, .github/workflows/go-apply-patch.sh, .github/workflows/go-releases-main.yml, .github/workflows/mirror-calico.yml, .github/workflows/runc-apply-patch.sh, .github/workflows/runc-releases-main.yml, .github/workflows/rust-apply-patch.sh, .github/workflows/rust-release-main.yml, .github/workflows/setup-flatcar-sdk.sh, .github/workflows/vmware-apply-patch.sh, .github/workflows/vmware-releases-main.yml
Basically bump versions of the actions we use and use a recommended way of setting output. This is to avoid usage of the deprecated features (node 12 and the set-output stuff).
The node 12 deprecation: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
The set-output command deprecation: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> github: Modernize the actions a bit

profiles/coreos/base/package.accept_keywords
Accept keywords for `app-arch/cpio` 2.13-r3, mainly to address [CVE-2021-38185](https://nvd.nist.gov/vuln/detail/CVE-2021-38185).
This PR should be merged together with https://github.com/flatcar/portage-stable/pull/390.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/415/cldsv/
- Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc. (not needed)
=> profiles: accept keywords for app-arch/cpio 2.13-r3

changelog/bugfixes/2022-12-06-kernel-bug-847.md, sys-kernel/coreos-sources/coreos-sources-5.15.79.ebuild, sys-kernel/coreos-sources/files/5.15/z0008-ext4-Fix-deadlock-due-to-mbcache-en.patch
This PR adds the patch that fixes flatcar/flatcar#847, while we wait for the patch to get merged upstream.
Rebuild
[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]
=> sys-kernel/coreos-sources: Add backport of bugfix for #847

profiles/coreos/arm64/package.accept_keywords
Should be merged together with https://github.com/flatcar/portage-stable/pull/397.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/444/cldsv
The updated package is stable for both amd64 and arm64.
=> profiles: Drop accept keywords for app-arch/libarchive

changelog/bugfixes/2022-01-09-initrd-setup-root.md, sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
c8399e42bb9651c3c108f916f6645557ab41884b which is a backport of the relevant parts of https://github.com/flatcar/bootengine/pull/50 to fix https://github.com/flatcar/Flatcar/issues/944
This should also be picked for Beta 3432 and Alpha 3446 (and any newly branched Alpha if merged afterwards).
[here](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1025/cldsv/)
and with `./flatcar_production_pxe.sh  -append 'flatcar.autologin'`
=> sys-kernel/bootengine: Always run initrd-setup-root

sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/flatcar/bootengine/pull/50
to select the active sysext images for OEMs or Flatcar extensions that are coupled to the OS version. Systemd 252 is needed for the sysext images to load without error because earlier systemd versions were too strict about the final filename target name of a symlink.
Update git ref to bootengine repo merge commit before merging
See linked PR
I don't think we need a changelog because this is not yet resulting in a change for the user.
=> sys-kernel/bootengine: Manage systemd-sysext images for A/B booting

profiles/coreos/base/profile.bashrc
Add an ebuild phase hook that runs when pkg_postinst is about to be executed. The hook sets up the environment for acct-user packages to avoid modifications of the preexisting users - these are provided by our baselayout and usermod can't change anything there anyway (it complains that the user is not in /etc/passwd).
Should be merged together with https://github.com/flatcar/portage-stable/pull/404.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/529/cldsv/
=> profiles: Do not modify preexisting users

coreos/user-patches/app-portage/gentoolkit/0001-profile-Default-to-main-repo-name.patch, coreos/user-patches/app-portage/gentoolkit/README.md, coreos/user-patches/app-portage/portage-utils/0001-main-Print-the-ignored-parent-line-in-warning.patch, coreos/user-patches/app-portage/portage-utils/0002-main-Handle-empty-repo-names-in-parent-files.patch, coreos/user-patches/app-portage/portage-utils/README.md, coreos/user-patches/sys-devel/gcc-config/0001-gcc-config-Use-relative-paths-for-liblto-and-cc-syml.patch, coreos/user-patches/sys-devel/gcc-config/README.md
Patches for gentoolkit and portage-utils will be useful for my package automation work, gcc-config patch is a fix that renders a hack in scripts repo as unnecessary.
Should be merged together with https://github.com/flatcar/scripts/pull/626.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/525/cldsv/
=> coreos: Add patches for gentoolkit, portage-utils and gcc-config

profiles/coreos/arm64/package.accept_keywords
Accept keywords `~arm64` for `dev-vcs/git` 2.37.5, mainly to address [CVE-2022-23521](https://nvd.nist.gov/vuln/detail/CVE-2022-23521), [CVE-2022-41903](https://nvd.nist.gov/vuln/detail/CVE-2022-41903).
This PR should be merged together with https://github.com/flatcar/portage-stable/pull/407.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1101/cldsv/
=> profiles: accept keywords ~arm64 for dev-vcs/git 2.37.5 for flatcar-3446

profiles/coreos/arm64/package.accept_keywords
Accept keywords `~arm64` for `dev-vcs/git` 2.38.3, mainly to address [CVE-2022-23521](https://nvd.nist.gov/vuln/detail/CVE-2022-23521), [CVE-2022-41903](https://nvd.nist.gov/vuln/detail/CVE-2022-41903).
This PR should be merged together with https://github.com/flatcar/portage-stable/pull/408.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/541/cldsv/
=> profiles: accept keywords ~arm64 for dev-vcs/git 2.38.3 for main

changelog/bugfixes/2023-01-19-kernel-bug-847.md, sys-kernel/coreos-sources/coreos-sources-5.15.86.ebuild, sys-kernel/coreos-sources/files/5.15/z0008-ext4-Fix-deadlock-due-to-mbcache-en.patch
Users reported a deadlock in ext4 that occurs under loads after kernel 5.15.72. We debugged and found that this issue is also present upstream (6.x) and found a fix. The fix has been validated to fix the issue.
Apply the backport to our kernel sources, so that users can be unblocked from updating.
This will be included in Stable 3374.2.3 with Kernel 5.15.86. Although the upstream stable Kernel 5.15.87 already has the fix, we should stay with 5.15.86 at least for this Stable channel release, to keep a certain degree of stability.
See also https://github.com/flatcar/Flatcar/issues/847, https://github.com/flatcar/coreos-overlay/pull/2315.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1121/cldsv/
=> sys-kernel/coreos-sources: Add backport of bugfix for #847 for flatcar-3374

profiles/coreos/base/make.defaults, sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/flatcar/bootengine/pull/52
to reduce the size of the unified kernel image by starting Ignition/ Afterburn from the /usr partition.
This also requires to install the Ignition binary to /usr.
See linked PR
=> Rework initrd usr mount to start Ignition/Afterburn from there

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/flatcar/init/pull/87
to give a nicer skip message in the log and also make clear that this is not a bug.
None, just manual testing in the linked PR
=> coreos-base/coreos-init: Skip first boot helper if Ignition did not run

app-emulation/cri-tools/cri-tools-1.24.2.ebuild
As `flatcar-3374` branch does not have Go 1.19, build fails due to a missing Go runtime. Downgrade `COREOS_GO_VERSION` to go1.18 to fix the build issue.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1197/cldsv/
=> app-emulation/cri-tools: build with Go 1.18 for flatcar-3374

.github/workflows/docker-apply-patch.sh
Now that the upstream Docker release notes website has changed its structure, the URL for Docker release notes started to have a specific format of
```
https://docs.docker.com/engine/release-notes/MAJOR.MINOR/#COMBINEDFULLVERSION
```
Fix the URL to make it work correctly.
Tested via my fork.
- Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc. (not needed)
=> .github: fix URL of docker release notes

changelog/changes/2023-02-09-systemd.md, sys-apps/systemd/systemd-252.5.ebuild
The boot log only showed the unit descriptions which made it hard to know what unit was meant.
Switch to the combined unit status reporting that includes the unit name.
[Done](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1256/cldsv/) ← Requires [mantle kola changes](https://github.com/flatcar/mantle/pull/411) because the journal log line for `cl.network.initramfs.second-boot` changes
=> Apply new Flatcar change of using the combined systemd log format

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.mask
Since the new USE flag `cet` became the default in profiles of portage-stable, SDK bootstrap using gcc 11.3.1_p20221209 started to fail at `sys-libs/glibc`.
```
in function `dl_open_worker_begin':
dl-open.c:(.text+0xab4c): undefined reference to `_dl_cet_open_check'
```
That is because gcc is not correctly configured for CET.
That issue was fixed in recent upstream GCC versions, e.g. 11.3.1_p20221209-r1 or 11.3.1_p20230120-r1.
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=016184c289f2cc6c6ade496a700a12f135fbae07
https://gitweb.gentoo.org/proj/gcc-patches.git/commit/?id=15daf0510a5fab17cd556261d688a6618391a0c1
However, gcc of Flatcar, 11.3.1_p20221209, does not have the fix.
Update `sys-devel/gcc` to 11.3.1_p20230120-r1 to fix that issue.
Also accept ~arm64 to keep the same version …
=> profiles: update sys-devel/gcc to 11.3.1_p20230120-r1

changelog/bugfixes/2023-02-20-preserve-kubernetes-interfaces.md, coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/flatcar/init/pull/89
to set the Kubernetes interfaces nodelocaldns and kube-ipvs0 as Unmanaged in networkd to prevent configuration conflicts.
We can backport it (down to LTS or rather Stable to prevent regressions in LTS?) with backports branches for the "init" repo.
[Kola on all platforms](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1331/cldsv/)
=> coreos-base/coreos-init: Exclude K8s' special interfaces

app-emulation/containerd/containerd-9999.ebuild
Since containerd 1.6.18, containerd is built with Go 1.19 by default. Following that, update the default Go version to 1.19.
See also https://github.com/containerd/containerd/commit/54ead5b7b71a.
Note: docker, docker-cli, docker-proxy, docker-runc still need Go 1.18.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1342/cldsv/
=> app-emulation/containerd: default to Go 1.19

coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/flatcar/init/pull/90
to fix the dummy interface exclusion rule in the default networkd unit. It was supposed to work before but didn't. With it we wouldn't have needed the special exclusions for Kubernetes interfaces.
Manual in linked PR
=> coreos-base/coreos-init: Fix dummy dev default networkd unit exclusion

profiles/coreos/arm64/package.accept_keywords
Accept keyword `~arm64` for `net-dns/dnsmasq` 2.89, to keep the same version 2.89 for both arches, addressing [CVE-2022-0934](https://nvd.nist.gov/vuln/detail/CVE-2022-0934).
This PR should be merged together with https://github.com/flatcar/portage-stable/pull/421.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/662/cldsv/
=> profiles: accept keyword ~arm64 for net-dns/dnsmasq 2.89

profiles/coreos/base/package.accept_keywords
To be merged with https://github.com/flatcar/portage-stable/pull/422
~CI Passed http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1348/cldsv/~
CI Running http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1366/cldsv/
=> profiles: Add KEYWORDS to update intel-microcode to 20230214_p20230212

changelog/changes/2023-02-20-etc-overlayfs.md, sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/flatcar/bootengine/pull/53
to provide files in /etc through an overlay mount from /usr/share/flatcar/etc - essentially giving us a 3-way merge of config files that allows us to update /etc while keeping user changes.
Together with https://github.com/flatcar/scripts/pull/666
See https://github.com/flatcar/bootengine/pull/53
=> sys-kernel/bootengine: Set up /etc as overlay mount

changelog/changes/2023-02-23-os-reset.md, coreos-base/coreos-init/coreos-init-9999.ebuild, sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/flatcar/bootengine/pull/55 and
https://github.com/flatcar/init/pull/91 for a `flatcar-reset` tool and boot logic for selective OS resets, cleaning the rootfs of old state while keeping wanted paths, e.g., when reconfiguring the system with Ignition.
Blocked on https://github.com/flatcar/coreos-overlay/pull/2482
See linked bootengine PR
=> Support selective OS resets

sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/flatcar/bootengine/pull/56
to ensure that even with a rerun from the initrd or with a deletion of /etc/passwd we are able to boot.
see linked PR
=> sys-kernel/bootengine: Make initrd-setup-root more resilient

sys-apps/baselayout/baselayout-9999.ebuild
This pulls in
https://github.com/flatcar/baselayout/pull/28 to fix a regression in https://github.com/flatcar/baselayout/pull/24 due to how systemd-tmpfiles' Z rule seems to cause unnecessary changes in files.
=> sys-apps/baselayout: Only relabel a minimal set of /etc files

changelog/changes/2023-03-08-systemd-elfutils.md, profiles/coreos/targets/generic/package.use
Elfutils is already part of the usr partition, but currently not enabled in systemd-coredump. Systemd-coredump therefore fails with:
elfutils disabled, parsing ELF objects not supported.
Enable the elfutils flag for systemd to make this work.
Dump core and check journal for messages.
Haven't tested, but will try it out once CI builds images.
=> profiles: Enable systemd[elfutils] USE flag for board

changelog/changes/2023-03-09-image-signing-key.md, coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in
https://github.com/flatcar/init/pull/92 to distribute the new sub key before we start signing with it from July.
Backport to all branches, via backport branch for init repo
=> coreos-base/coreos-init: Distribute new sub key

changelog/changes/2023-03-09-pigz.md, coreos-base/coreos/coreos-0.0.1.ebuild
For https://github.com/flatcar/Flatcar/issues/965
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1464/cldsv
=> coreos-base/coreos: Add pigz to production image

profiles/coreos/base/make.defaults
I'm not sure how this package slipped through the CI earlier, but now it couldn't be built because it's license was not accepted. Fix this by adding intel-ucode license to ACCEPT_LICENSE.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1471/cldsv
=> profiles: Accept license for sys-firmware/intel-microcode

changelog/bugfixes/2023-03-20-ignition-oem-partition.md, changelog/changes/2023-03-20-ignition-oem-files.md, sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/flatcar/bootengine/pull/58
to prevent the OEM mount point from showing up before Ignition mounts. It also makes it simpler to write files to the OEM partition without having to specify the partition first as initrd mount point.
Fixes https://github.com/flatcar/Flatcar/issues/979
See linked PR
=> sys-kernel/bootengine: Prevent OEM mount point from showing up early

coreos-base/emerge-gitclone/emerge-gitclone-9999.ebuild
This change bumps the CROS_WORKON_COMMIT of emerge-gitclone to include the latest flatcar-master tip. emerge-gitclone now supports developer OS versions and uses the version's git ref suffix to check out the correct scripts repo version.
See https://github.com/flatcar/flatcar-dev-util/commit/401e84df7b12b0f385879583003a7cc0bd9bbc60 for details.
The change should be cherry-picked to all active maintenance branches (including LTS) as it un-blocks running tests in github actions. See https://github.com/flatcar/scripts/pull/696#issuecomment-1482850809 for more details.
=> emerge-gitclone: bump to include support for git ref versions

changelog/bugfixes/2023-03-30-var-log-journal.md, sys-apps/baselayout/baselayout-9999.ebuild, sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in https://github.com/flatcar/bootengine/pull/60 and https://github.com/flatcar/baselayout/pull/29 to fix the persisting of the journal on first boot.
Backport to Alpha
See linked bootengine PR
=> Use tmpfiles to set up /var/log/journal/ from initrd

changelog/changes/2023-04-05-os-reset-backup.md, coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in https://github.com/flatcar/init/pull/94 to prevent data loss by having a preview mode and a backup/restore option.
Backport to Alpha
Manually in the linked PR
[CI](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1606/cldsv/)
=> coreos-base/coreos-init: Add preview/backup/restore to flatcar-reset
