coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
coreos-base/oem-azure/files/base/default.ign
coreos-base/oem-cloudsigma/files/cloud-config.yml
coreos-base/oem-cloudstack/files/cloud-config.yml
coreos-base/oem-cloudstack/files/cloudstack-coreos-cloudinit
coreos-base/oem-cloudstack/oem-cloudstack-0.0.4.ebuild
coreos-base/oem-digitalocean/files/base/default.ign
coreos-base/oem-ec2-compat/files/base/default.ign
coreos-base/oem-exoscale/files/cloud-config.yml
coreos-base/oem-exoscale/files/exoscale-coreos-cloudinit
coreos-base/oem-exoscale/oem-exoscale-0.0.5.ebuild
coreos-base/oem-gce/files/base/default.ign
coreos-base/oem-interoute/files/cloud-config.yml
coreos-base/oem-interoute/files/cloudstack-coreos-cloudinit
coreos-base/oem-interoute/oem-interoute-0.0.3-r1.ebuild
coreos-base/oem-niftycloud/files/cloud-config.yml
coreos-base/oem-niftycloud/files/niftycloud-coreos-cloudinit
coreos-base/oem-niftycloud/oem-niftycloud-0.0.3-r1.ebuild
coreos-base/oem-packet/files/base/default.ign
coreos-base/oem-rackspace-onmetal/files/cloud-config.yml
coreos-base/oem-vagrant/files/cloud-config.yml
coreos-base/oem-vmware/files/base/default.ign
eclass/coreos-go.eclass

There's no need to rename this since coreos-cloudinit is just the name of
the project.

 Change back flatcar-cloudinit to coreos-cloudinit

---

sys-apps/ignition/ignition-9999.ebuild

Pulls in
https://github.com/flatcar-linux/ignition/pull/10

sys-apps/ignition: Point to flatcar-master

---

sys-apps/baselayout/baselayout-9999.ebuild

Point to latest flatcar-master branch to include upstream commit.
Note: Update flatcar-master-alpha and edge, too.

sys-apps/baselayout: Pick upstream commit

---

.github/workflows/go-apply-patch.sh
.github/workflows/kernel-apply-patch.sh

We need to get metadata included in the generated pull requests.

.github: get metadata included in the generated PRs

---

app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild
app-emulation/docker-runc/files/0001-temporarily-disable-selinux.GetEnabled-error-checks.patch
profiles/coreos/amd64/generic/package.use
profiles/coreos/arm64/package.use

This reverts commit 210d750b39eb2a1e7319dbc445c131bb6e8d3f2d, reversing
changes made to 08771213dbe072daa07182f1b1fc51671471d9ef.
Note: Also need to be picked to `flatcar-build-2513.0.0`

Revert "Merge pull request #289 from flatcar-linux/dongsu/docker-runc-selinux-alpha"

---

sys-apps/systemd/systemd-9999.ebuild

Enable remote-fs for 2605

---

sys-apps/systemd/systemd-9999.ebuild

Enable remote-fs for 2632

---

eclass/coreos-kernel.eclass

DTC (Device Tree Compiler) source tree in Flatcar Kernel modules unnecessarily takes too much space, especially the `include-prefixes` directory.
```
$ sudo du -a /usr/lib64/modules/$(uname -r)/source/ | sort -n -r | head -n5
130100  /usr/lib64/modules/5.8.11-flatcar/source/
69180   /usr/lib64/modules/5.8.11-flatcar/source/include
56324   /usr/lib64/modules/5.8.11-flatcar/source/scripts
51384   /usr/lib64/modules/5.8.11-flatcar/source/scripts/dtc
50728   /usr/lib64/modules/5.8.11-flatcar/source/scripts/dtc/include-prefixes
$ sudo ls /usr/lib64/modules/$(uname -r)/source/scripts/dtc/include-prefixes/
arc  arm  arm64  c6x  dt-bindings  h8300  microblaze  mips  nios2 openrisc  powerpc  sh  xtensa
```
Most of them are for architectures that are not supported by Flatcar, so we can remove them …

eclass: exclude unnecessary architectures from DTC in Kernel

---

coreos-base/coreos-init/coreos-init-9999.ebuild

Needed for kinvolk/Flatcar#278

Track latest init commit

---

.github/workflows/kernel-apply-patch.sh

Some small fixes for stuff I have noticed when checking the kernel update workflow failure. Not yet tested, but should be harmless.

.github: Minor fixes in kernel update workflow

---

profiles/coreos/base/package.accept_keywords

upgraded libgcrypt to 1.9.4

---

changelog/README.md

Mention that it should be written as a bullet list. Also, match the
format to the example (put the version link inside parentheses).

changelog: Update the update changelog format

---

.github/workflows/common.sh
.github/workflows/kernel-apply-patch.sh

It happens that kernel update PRs are created faster than we merge
them. In such case we create version gaps in the changelog. Remedy
that by adding links to all the released kernel versions between the
current one and the just released one.
For an example of a PR created by these changes please see https://github.com/krnowak/coreos-overlay/pull/6

.github: Reflect more kernel versions in the changelog

---

profiles/coreos/base/package.accept_keywords

<hr>
To be merged with: https://github.com/flatcar-linux/portage-stable/pull/297
Stabilization request can be opened a few days after the release if not issue has been detected.

profiles/base: stabilize duktape

---

profiles/coreos/base/package.accept_keywords

<hr>
Let's submit a stabilization request after releasing alpha.
To be merged with: https://github.com/flatcar-linux/portage-stable/pull/298

profiles/base: stabilize libxml2

---

coreos/config/env/net-dns/bind-tools
profiles/coreos/arm64/package.accept_keywords
profiles/coreos/base/package.accept_keywords
profiles/coreos/base/package.use
profiles/coreos/targets/generic/package.use

Should be merged together with https://github.com/flatcar-linux/portage-stable/pull/320.
Please see the PR in portage-stable for more info.
CI: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5298/cldsv/

Profile cleanups for package updates, 2020 edition

---

changelog/changes/2022-09-08-emerge-gitclone.md
coreos-base/emerge-gitclone/emerge-gitclone-9999.ebuild

Signed-off-by: Sayan Chowdhury <schowdhury@microsoft.com>

emerge-gitclone: update workon_commit ref to latest commit

---

profiles/coreos/base/package.accept_keywords

Should be merged together with https://github.com/flatcar-linux/portage-stable/pull/359.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/239/clsdv

profiles: Add accept keywords for updated libxml2

---

.github/workflows/cacerts-apply-patch.sh
.github/workflows/cacerts-releases-lts-2021.yml
.github/workflows/common.sh
.github/workflows/containerd-apply-patch.sh
.github/workflows/docker-apply-patch.sh
.github/workflows/firmware-apply-patch.sh
.github/workflows/go-apply-patch.sh
.github/workflows/kernel-apply-patch.sh
.github/workflows/kernel-releases-lts-2021.yml
.github/workflows/runc-apply-patch.sh
.github/workflows/rust-apply-patch.sh
.github/workflows/vmware-apply-patch.sh

The workarounds are not needed any more.

.github: Revert old lts workarounds

---

profiles/coreos/amd64/sdk/package.accept_keywords
profiles/coreos/arm64/package.accept_keywords
profiles/coreos/base/package.accept_keywords
profiles/coreos/base/package.unmask

Should be merged together with https://github.com/flatcar/portage-stable/pull/377.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/349/cldsv.

Profile additions and cleanups for weekly update

---

profiles/coreos/base/package.accept_keywords
profiles/coreos/targets/generic/package.provided
profiles/coreos/targets/sdk/package.use

Should be merged together with https://github.com/flatcar/portage-stable/pull/384.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/408/cldsv

profiles: Cleanups for weekly package updates

---

profiles/coreos/base/package.accept_keywords

CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/416/cldsv
Should be merged together with https://github.com/flatcar/portage-stable/pull/388

profiles: Updates for weekly package updates

---

coreos/user-patches/README.md

See also https://github.com/flatcar/scripts/pull/607 for details.
Should be merged together with https://github.com/flatcar/scripts/pull/607.

coreos/user-patches: New directory for user-patches

---

profiles/coreos/base/make.defaults
profiles/coreos/base/package.use.force

CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/559/cldsv

profiles: Pick defaults for app-alternatives during bootstrap

---

profiles/coreos/base/use.mask

Mask cet use flag.
Two phase CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/648/cldsv

Disable CET on 3510

---

profiles/coreos/base/use.mask

Mask cet use flag.
Two phase CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/660/cldsv

Disable CET on 3493

---

profiles/coreos/arm64/package.accept_keywords
profiles/coreos/base/package.accept_keywords

To be merged with https://github.com/flatcar/portage-stable/pull/413
CI Passed http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/665/cldsv/

Weekly package updates 2023-02-08
